### ISSUE TITLE
Crash when running a dev checkout of EE3

### ISSUE THREAD

**Issue by xWTyrone** [pahimar/Equivalent-Exchange-3#1000]
EE3 crashes Minecraft when trying to load the aludel obj file with error 

net.minecraftforge.client.model.ModelFormatException: IO Exception reading model format

According to the WavefrontObject class, an attempt is done to load the texture in the try-catch block. Java throws an IOException with nothing further, thus crashing the game.

Full Log (FML): https://gist.github.com/xWTyrone/025b8a336c8ea1464b97

Supposed to occur:
FML finds the file and doesn't crash. (pretty obvious)

EDIT:
Commit SHA (for easy finding): b8ef89c72d9102f62781201ee8b0b5b975a0eb91

**Comment by Taifuru** [comment]
Hi, this i got this crash too. And i checked the minecraftforge github page. They fixed this issue. @pahimar just needs upgrade forge version 10.13.3.1399-1.7.10 to 10.13.4.1492-1.7.10. And then refresh the gradle. But there is a little problem. Despite the change of forge version. You can not start client using run configuration GradleStart. But if you run "gradle runClient" game doesn't crash.

PR #1003

**Comment by pahimar** [comment]
Closing because we've far gone past the minimum forge version to resolve this
