### ISSUE TITLE
Transumation Tablet not automatically updating transmutation list on searches

### ISSUE THREAD

**Issue by sctjkc01** [pahimar/Equivalent-Exchange-3#1001]
Is anyone else bothered by the [need to pull the book out and put it back in](https://youtu.be/WZ5H52bewhk?t=255)?  Because, to be frank, this still is bugging me, and I don't see it anywhere on the issue list.

I might even end up going through and figuring out how to fix it myself, once I get a dev area set up...

**Comment by pahimar** [comment]
You didn't look very hard then

https://github.com/pahimar/Equivalent-Exchange-3/issues/992

**Comment by sctjkc01** [comment]
I did see that mega-issue, but I didn't see that specific problem listed.
