### ISSUE TITLE
Research Disappears Mid-Session

### ISSUE THREAD

**Issue by rbandboy** [pahimar/Equivalent-Exchange-3#1005]
1.7.10-0.3.507 has a weird issue where research disappears from the alchemical tome from time to time, and will eat multiple of the same item in the research table.

Seems to be more reliable when the player is actively watching the research window, but I've observed several instances during the same session where select items were forgotten mid-session.

I assume this will be tracked with the issues on the unified ticket #989.

**Comment by pahimar** [comment]
Issue already being tracked in main Knowledge System ticket #989
