### ISSUE TITLE
Rain seeds have value of 24, converts to lapis, value of ~836

### ISSUE THREAD

**Issue by itanshi** [pahimar/Equivalent-Exchange-3#1006]
Now the Pneumaticraft seeds are discontinued in later updates of Pneumaticraft, but Agricraft greenhouses still plant them by some sort of random seed algorithm so not even sure who to report this to. Everyone?

**Comment by Wulfson** [comment]
Try mentioning it on something related to either of those mods?

**Comment by WolfAmaril** [comment]
There's a seed blacklist in the agricraft folder in you .config directory. Add the following to it and they won't show up anymore.

PneumatiCraft:plasticPlant:0
PneumatiCraft:plasticPlant:1
PneumatiCraft:plasticPlant:2
PneumatiCraft:plasticPlant:3
PneumatiCraft:plasticPlant:4
PneumatiCraft:plasticPlant:5
PneumatiCraft:plasticPlant:6
PneumatiCraft:plasticPlant:7
PneumatiCraft:plasticPlant:8
PneumatiCraft:plasticPlant:9
PneumatiCraft:plasticPlant:10
PneumatiCraft:plasticPlant:11
PneumatiCraft:plasticPlant:12
PneumatiCraft:plasticPlant:13
PneumatiCraft:plasticPlant:14
PneumatiCraft:plasticPlant:15
