### ISSUE TITLE
Balance

### ISSUE THREAD

**Issue by icimcrazy** [pahimar/Equivalent-Exchange-3#1007]
The value of clay may need to be dropped currently 64 emc. The clayconia from botania lets you convert sand (1 emc value) into clay at the cost of mana. A full transmutation table of clay produces 4 diamonds.

**Comment by noteclip** [comment]
I don't think that's a major issue. That could be left to the pack makers preference whether to disable the flower or to make the value of clay lower.

**Comment by pizzana** [comment]
EE3 shouldn't be hard-coded to be balanced with other mods. It already provides API and configutation files for them to modify EMC values and register custom recipes. It's up to the mod authors if they want to use it.
