### ISSUE TITLE
Emc values arent generating for all the fuels in my modpack help....

### ISSUE THREAD

**Issue by Cinder85** [pahimar/Equivalent-Exchange-3#1009]
its under 90 mods and ive been careful to add it after ive added all the other mods to see if that would fix it but sadly all three fuels arent generating emc values

**Comment by JCBurnside** [comment]
You have to make sure that the mods that make the fuels you are looking at have support for ee3.  If it uses one item anywhere in the crafting chain that has no emc then the item at the end won't have one.

**Comment by Cinder85** [comment]
i meant the ee3 fuels arent generating emc values @JCBurnside

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
