### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Curtis3321** [pahimar/Equivalent-Exchange-3#1015]
My server keeps getting this crash;

https://gist.github.com/Curtis3321/9a565b29e9b40cb7ac57

Any idea? anything I can disable? It only happens every so often, not all the time.

**Comment by 0zlw** [comment]
Very similar looking crash on our server repeatedly:

**Comment by Curtis3321** [comment]
Yeah, REALLY need some advice on it, crashing at the worst possible times.

**Comment by pahimar** [comment]
It's the shift click bug with the transmutation tablet

**Comment by Curtis3321** [comment]
Alright, any idea of a fix that I can do?

**Comment by pahimar** [comment]
None at the moment, its something that needs to be fixed in code.

You can avoid it by not shift clicking out of the tablet when the result would fill your inventory

**Comment by pahimar** [comment]
Duplicate issue, already tracked in https://github.com/pahimar/Equivalent-Exchange-3/issues/992
