### ISSUE TITLE
Chalk Size Conflict

### ISSUE THREAD

**Issue by MokahTGS** [pahimar/Equivalent-Exchange-3#1022]
There is something that is causing the chalk to stop responding to changing size via the keyboard.  Pressing V or shift+V has no effect.  I get the small symbol but cannot get the large symbol back...it just goes blank.

**Comment by MokahTGS** [comment]
I have also made sure there are NO other mods conflicting with the needed keys.  It just doesn't work.

**Comment by pahimar** [comment]
Can you upload a fml-client log to pastebin and link it here?

**Comment by MokahTGS** [comment]
https://dl.dropboxusercontent.com/u/9882100/Minecraft/fml-client-latest.7z

**Comment by MokahTGS** [comment]
So is there any way to get a tablet without the chalk?  This is completely broken now on our world and the chalk symbol is stuck at the small size.

**Comment by RottenSkillHD** [comment]
Has anyone figured out hoe to fix this problem i have the same thing that is annoying me.

**Comment by Plasmo322** [comment]
I've had the same problem but I fixed it by making it small enough to where it goes away and then I press shift + (keybind) and it works.

**Comment by yakri** [comment]
So. . . . EC is toast since making tablet is impossible?

**Comment by pahimar** [comment]
EC?

Making a tablet is not impossible

**Comment by border999** [comment]
On a somewhat related question. Is it possible to create a transmutation tablet on say... a wall? As in standing up embedded in the wall.

**Comment by reapersremorse** [comment]
I believe he ment emc.

**Comment by border999** [comment]
Just wanted to know. It's just an inquiry on an aesthetic idea for the transmutation tablet.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
