### ISSUE TITLE
Cannot open Calcinator GUI or Aludel GUI (on Mac)

### ISSUE THREAD

**Issue by jakemroman** [pahimar/Equivalent-Exchange-3#1025]
I've crafted a Calcinator and placed it, but the GUI will not open when I click it.
Same with the Aludel Base, and yes I put a glass bell on top.

I tried hopper-ing items inside but they don't accept them either

**Comment by Taifuru** [comment]
i think beacuse its not implemented yet

**Comment by jakemroman** [comment]
No, I saw a spotlight on the mod and he was able to open it.
VERSION: 0.02.234

**Comment by jakemroman** [comment]
Oh, does the fact that I am on mac matter???

**Comment by jakemroman** [comment]
Please fix this...

**Comment by pahimar** [comment]
Please upload a FML log so that I can see what version of the mod you are using

Look in your logs/ folder for fml-client-latest.log or something like that

**Comment by jakemroman** [comment]
ok

**Comment by jakemroman** [comment]
It does not support log files so try this:
http://pastebin.com/25QNgxna

**Comment by WolfAmaril** [comment]
You're on version 0.2.234, current version is 0.3.507.

Update

**Comment by jakemroman** [comment]
Thanks!

**Comment by jakemroman** [comment]
I can't find v0.3? The one on the Minecraft Forums is outdated.

**Comment by jakemroman** [comment]
Nice! It's fixed!
