### ISSUE TITLE
"java.lang.NullPointerException: Updating screen events" when taking out an RE Battery (IC2 Classic) from a transmutation tablet.

### ISSUE THREAD

**Issue by Ugaps** [pahimar/Equivalent-Exchange-3#1026]
Crashlog: http://pastebin.com/gceLZGBU

I am unsure as to what else to provide except the description of what I tried to do.

I crafted an RE Battery to set an EMC value for it. I was surprised that after using "/ee3 set-energy-value-current-item post 1218.5" the item still said "No exchange value". Then I crafted another one and saw that it actually DID have an EMC value. I put one of them on a research station to be able to transmute it. It worked fine, and when I came to take a battery out of my transmutation tablet the game crashed.

I suspect it's because of the way IC2 Classic handles batteries, though I cannot provide anymore details. If there's anything I can do to help, I'll try my best to do so.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
