### ISSUE TITLE
Dynamic EMC stopped working

### ISSUE THREAD

**Issue by heartlessfury** [pahimar/Equivalent-Exchange-3#1027]
None of the recipes is working anymore since yesterday i was setting the EMC values to fill all the recipes but for some reason the mod stopped calculating all any recipes like potions, blocks of metal or any other recipe
![2016-01-02_18 48 39](https://cloud.githubusercontent.com/assets/10078454/12076048/91e40fd8-b181-11e5-8336-3000f1ad3e10.png)

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
