### ISSUE TITLE
Crash after upgrading to 508 or 509

### ISSUE THREAD

**Issue by ravendm5** [pahimar/Equivalent-Exchange-3#1028]
Hello,
When upgrading from 507 to either 508 or 509 I've been getting this error when trying to load an existing world or when creating a new one.

http://pastebin.com/Bqy1yKWA

**Comment by pahimar** [comment]
Can you upload your FML log to pastebin?

**Comment by ravendm5** [comment]
Unfortunately I can't upload the whole file at once, but here is the part from where the errors start to the end.  The portion between the two pastes is a long string of [DynamicEMC Thread/INFO] [EE3/]: Unable to compute a value for object.  The attached zip contains the full log, but please let me know if there is a better way to get it to you.

http://pastebin.com/FSCVDmUt
http://pastebin.com/c6Jww10E

[fml-client-3.zip](https://github.com/pahimar/Equivalent-Exchange-3/files/79969/fml-client-3.zip)

**Comment by king05** [comment]
@ravendm5 use paste.ee and make a free account... tahn you can upload text up to 12 mb size... so you can paste the full log....

**Comment by ravendm5** [comment]
@king05 Thanks for that!

Here is the paste of the full log

https://paste.ee/r/pLfAM

**Comment by Taifuru** [comment]
I couldn't find any relation between EE3 and this crash report. Am i missing something ?

**Comment by cylek56** [comment]
The issue comes from EnderIo and Cofh Core

**Comment by Boy-Blue** [comment]
I had this same issue when adding ee3 509 to a pack. Worked fine before adding ee3, but after adding it it would crash. The report made it look like it was an issue with logistics pipes. When I removed logistics pipes it crashed with an issue with refined relocation. Adding ee3 507 works just fine though

**Comment by laz2727** [comment]
There are two possibly related stack traces, one just before the server
stop event and another one is a NEI plugin crashing (these tend to crash
the whole game if they feel like it).

**Comment by SkinHeadBaby** [comment]
i have the same crash to the last number i saw on the old issues that its the same as https://github.com/pahimar/Equivalent-Exchange-3/issues/918
im able to log in to the old world if i first create a new world and then try to log in the old one
i can then restart the game and log in successfuly but after a day or more i get the same error and i must create a new world again to log in

and pahi are you going to fix this for 1.7.10 or are you going to continue to 1.8.9 as you said on twitter i think

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
