### ISSUE TITLE
Can't start any World with new EE3 509

### ISSUE THREAD

**Issue by king05** [pahimar/Equivalent-Exchange-3#1029]
Hi, first of all a happy new year.
After I updated to the newest EE3 Version I can't start neither an existing world nor an new world.

https://dl.dropboxusercontent.com/u/30828902/No%20world%20start.avi

here you can see that i'm trying both, start an existing and a new world.. nothing is working. 
When i downgrade to EE3 version 507 it works fine. 

Hope you can help me.
Greetings from Germany,
king05

**Comment by Taifuru** [comment]
Can you upload your FML log to pastebin?

**Comment by king05** [comment]
It have to be paste.ee because the file was to large but here is the link:
https://paste.ee/r/GlUm5
After i quit the game, i have to kill the java.exe because the minecraft window disapear but the task was still active

**Comment by king05** [comment]
ok i found the problem... it was because of equivalent energistics... i'll report it to there.... but now i have the same issue than ravendm5 in #1028 ...
got the same crash...
Here is the pastebin link:
http://pastebin.com/fA5YjXte
