### ISSUE TITLE
Can't create a Transmutation Tablet on EE3 -1.7.10- 0.3.0.509

### ISSUE THREAD

**Issue by Jayboy789** [pahimar/Equivalent-Exchange-3#1030]
![6b6e9fa3777927f622eee60763ec5033](https://cloud.githubusercontent.com/assets/16620769/12215121/7915d6de-b6fa-11e5-8550-13934d155298.png)
And yes I did Shift Right click with an empty hand

**Comment by BraynStorm** [comment]
Yeah I tried everything but it doesn't work. Maybe they changed the way you create them? Who knows!

**Comment by iTitus** [comment]
Did not work for me either

**Comment by Plasmo322** [comment]
I have EE3 and it works for me. They certainly didn't change the way to make it. What version are you using? I'm using 1.4.7.37 universal for mc 1.7.10. If your using a later version I suggest you downgrade to the version I use above.

**Comment by pahimar** [comment]
The common trip up here is that after 507 there are 8 more transmutation circles added to the mod, and the texture is changed.

Probably best to stick to 507. I've pulled 508 and 509 from Curseforge
