### ISSUE TITLE
(Suggestion) Energy Condenser in Minecraft Configuration

### ISSUE THREAD

**Issue by jakemroman** [pahimar/Equivalent-Exchange-3#1031]
Sorry, dunno where else to post a suggestion, but I'm pretty sure that the main reason that most people get this mod is because of the old energy condenser. Anyway, yes it is definitely overpowered, however it should be an option to those who want it.

Thanks

**Comment by pahimar** [comment]
Other than asking for a config option for the condenser, I'm not sure what you are suggesting here. We don't have a condenser.
