### ISSUE TITLE
Alchemical Bag Screen Events

### ISSUE THREAD

**Issue by SirWoofie** [pahimar/Equivalent-Exchange-3#1032]
Oddly enough, this didn't crash my game, just my world. I created a new Mystcraft world, placed down a linkbook stand, then started lagging. I tried placing the linkbook on the stand, but nothing happened(lag). After that, I tried opening my Alchemical Bag(Small, I think) and the game closed my world! Placed me in the multiplayer section, so I guess the Internal Server crashed but my client didn't... I'll have to check that Mystcraft world.

LOG: http://paste.ee/p/6stZN
Check line 7798 and down.
If this is just a problem because I was lagging due to world generation, feel free to ignore this, or close it.

**Comment by pahimar** [comment]
Looks like your system was so lagged out it timed out syncing the inventory on open (which every GUI with an inventory does)

**Comment by SirWoofie** [comment]
Thanks for the clarification.
