### ISSUE TITLE
Minefactory reloaded and Thermal expansion pack breaking EMC exchange values?!!?

### ISSUE THREAD

**Issue by Plasmo322** [pahimar/Equivalent-Exchange-3#1033]
So I recently installed Thermal expansion, thermal foundation, CoFHCore, and minefactory reloaded and apparently one or more of them is conflicting with EMC exchange values from EE3 and the energy values that I set get RESET. Idk why it's happening or how to fix. Can someone please tell me how to fix this because I love/ cannot live without these mods, but I'm not willing to uninstall EE3 because I love that mod just as much as them. I'm using Minecraft 1.7.10 by the way.

**Comment by snacdaws** [comment]
edit the config so that it says abilities.onlyLoadFile=false
 and change "when mods change" to "always"
i'm using DW20 1.7 modpack with EE3 installed and that configuration seems to work for me

**Comment by Plasmo322** [comment]
Ok thanks. I already figured out the solution by downloading EE3 Help mod. It works just as fine and the emc values never reset.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
