### ISSUE TITLE
Issue with Research Station & Tome of Alchemical Knowledge and SimpleCondensers

### ISSUE THREAD

**Issue by G3Shawty** [pahimar/Equivalent-Exchange-3#1035]
When researching a particular item (lets say Cobblestone or Iron Ingot) looking at the Cobblestone in the book yields a [EMC value of 0](http://imgur.com/gjD8HdC), which brings me to my second issue. Placing the Book and cobble in the condenser when the book contains cobblestone listed does not output [cobblestone.](http://imgur.com/tZVq7UF)

One way I got around doing this is by researching everything I want, then telling my friend to restart his server (since he's running the server off his computer) when the server is back, all EMC values are in place and I can begin converting items into other items. This proved to be unreliable when I was unable to successfully reproduce multiple times.

Another Bug I found was I tried logging out with the book in my inventory and all the items I had researched were gone (when the values were zero). When I log out with the book NOT in my inventory the research disappears as well and only some reappear when I try to type them out. 

If you need more information please let me know and I will try to explain to the best of my abilities, thanks in advance.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
