### ISSUE TITLE
Tome losing all Research on Server log off

### ISSUE THREAD

**Issue by silverbreeze** [pahimar/Equivalent-Exchange-3#1036]
I am using the version of EE3 in the FTB Client Horizons: Daybreaker. Server hosted with Apex. 
The first time I notice was after a client crash caused by scrolling the Researched in the Tablet.

Simular to #1035 , but I haven't touched Condensors or anything beyond Alechmic chests, Vanilla stuff and Color Coded Ender Chest/Pouch set

I pull a Verbrant Dust from one of my chests and reResearched it
Disconnected cleanly
Reconnected...

Tome is empty.

Thanks 
Tom
@silverbreeze

**Comment by spannerman79** [comment]
The exact same as me so I know how you feel @silverbreeze 

I double checked everything - configs, running only EE3 - same issue.

**Comment by NoxInc** [comment]
Same for me.

**Comment by palaster** [comment]
If you are still having this problem check the issue here. https://github.com/pahimar/Equivalent-Exchange-3/issues/989

**Comment by palaster** [comment]
If you are still having this problem check out the info here. https://github.com/pahimar/Equivalent-Exchange-3/issues/989

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
