### ISSUE TITLE
i cant use the transmutation table

### ISSUE THREAD

**Issue by machomich123** [pahimar/Equivalent-Exchange-3#1038]
first i had a problem i couldn't draw the symbol but i fixed it and now i can't even use the god damn thing i don't know how to fix it and nobody has had the same problem as me! please help.....

**Comment by pahimar** [comment]
Gonna need a lot more details than just an angry rant, such as;
Mod list with versions
Logs
Possibly screenshots to show what you are doing (or video)

**Comment by machomich123** [comment]
i fixed it i just waited a couple of hours and then it worked thanks for
answering!


2016-03-13 20:10 GMT+01:00 Pahimar <notifications@github.com>:
