### ISSUE TITLE
DynamicEMC Generation

### ISSUE THREAD

**Issue by beareogaming** [pahimar/Equivalent-Exchange-3#1039]
For whatever reason my game continues to have the error below 

Equivalent Exchange 3/]: No energy value file to load values from, generating new values
[Equivalent Exchange 3/]: Beginning dynamic value computation
[/]: Exception in thread "DynamicEMC Thread" 
[/]: java.lang.NullPointerException
[/]: 	at net.minecraftforge.fluids.FluidRegistry.getFluidID(FluidRegistry.java:199)
[/]: 	at com.pahimar.ee3.util.FluidHelper$1.compare(FluidHelper.java:26)
[/]: 	at com.pahimar.ee3.util.FluidHelper$1.compare(FluidHelper.java:16)
[/]: 	at com.pahimar.ee3.util.FluidHelper.compare(FluidHelper.java:97)
[/]: 	at com.pahimar.ee3.exchange.WrappedStack$1.compare(WrappedStack.java:662)
[/]: 	at com.pahimar.ee3.exchange.WrappedStack$1.compare(WrappedStack.java:622)
[/]: 	at com.pahimar.ee3.exchange.WrappedStack.compareTo(WrappedStack.java:574)
[/]: 	at com.pahimar.ee3.exchange.WrappedStack.compareTo(WrappedStack.java:18)
[/]: 	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:35)
[/]: 	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:26)
[/]: 	at com.google.common.collect.SortedLists.binarySearch(SortedLists.java:272)
[/]: 	at com.google.common.collect.RegularImmutableSortedSet.indexOf(RegularImmutableSortedSet.java:274)
[/]: 	at com.google.common.collect.RegularImmutableSortedMap.get(RegularImmutableSortedMap.java:96)
[/]: 	at com.google.common.collect.ImmutableMap.containsKey(ImmutableMap.java:372)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.getEnergyValueFromMap(EnergyValueRegistry.java:199)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.getEnergyValue(EnergyValueRegistry.java:150)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.getEnergyValue(EnergyValueRegistry.java:135)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.hasEnergyValue(EnergyValueRegistry.java:125)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.computeStackMappings(EnergyValueRegistry.java:511)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.runDynamicEnergyValueResolution(EnergyValueRegistry.java:397)
[/]: 	at com.pahimar.ee3.exchange.EnergyValueRegistry.init(EnergyValueRegistry.java:343)
[/]: 	at com.pahimar.ee3.exchange.DynamicEnergyValueInitThread.run(DynamicEnergyValueInitThread.java:18)
[/]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Nincodedo** [comment]
What other mods do you have installed? Does the game crash when this happens and if so could you post the entire crashlog?

**Comment by beareogaming** [comment]
This does not cause a crash, instead only the most basic items get a emc value. Not even a bow or a piston gets emc, furnace, ext.  

I will post a mod list when I get home

**Comment by beareogaming** [comment]
mods include:
ArsMagica 2
AnimationAPI
AppliedEnergistics2
AsieLib
BackTools
BiomesOPlenty
BloodMagic
Botania
Buildcraft
Carpenter's Blocks
ChickenChunks
CoFHCore
EE3Help
Equivelant Exchange 3
EnderCore
EnderIO
EnderStorage
ExtraCells
ExtraTiC
extrautilities
fastcraft
FTBLib
FTBTweaks
FullscreenWindowed
GalacticraftCore
GalacticraftPlanets
GravityGun
HardcoreEnderExpansion
Hats
iChunUtil
ImmersiveEngineering
Industrialcraft 2
ironChests
Jabba
MagicalCrops
Mantle
mcjtylib
Mekanism
MineFactoryReloaded
MineTweaker3
MobDismemberment
Mod Tweaker2
Modular Powersuits
NeiAddons
NEIIntegration
NtherOres
NotEnoughItems
NotEnoughResources
Numina
OpenBlocks
OpenPeripherals
Opis (serverSide)
PneumaticCraft
PortalGun
ProjectRed
RailCraft
Reliquary
rftools
Ruins
Statues
Sync
TConstruct
Thaumcraft
ThaumicEnergistics
ThaumicExploration
ThaumicTinkerer
ThermalDynamics
ThermalExpansion
ThermalFoundation
Translocators (if dupe patched)
Twilight Forest
Waila
Witchery
WR-CBE

**Comment by LolindirElros** [comment]
This is happening to me too. It was working fine and then this started happening: even wool is missing an EMC value. And I'm sure it used to have EMC value because I used to use it.

Mod list:

Better Furnaces
Treecapitator
Backpack
Bibliocraft
Big Reactors
Biomes o Plenty
Chicken Chunks
Chisel
CodeChickenCore
CoFHCore
Dense Ores
EnderCore
Ender IO
Equivalent Exchange 3
Extra Utilities
Forestry
Hats
HatStand
iChunUtil
InventoryTweaks
Iron Chest
JABBA
JourneyMap
Legends Core
Mantle
MineFactory Reloaded
Morph
NEIAddons
NEIIntegration
NEI
OpenBlocks
OpenModsLib
OptiFine
Superheroes Unlimited
Tinkers Construct
TF2 Teleporter
Thaumcraft 4
Thaumic Exploration
Thermal Expansion
Thermal Foundation
Waila
Waila Harvestability

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
