### ISSUE TITLE
Energy

### ISSUE THREAD

**Issue by TH3GOD88** [pahimar/Equivalent-Exchange-3#1041]
It seems if I shift click too many items from the transmutation table; it will crash my server. Here is both the crash log and server log.
[crash-2016-04-10_21.24.01-server.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/212177/crash-2016-04-10_21.24.01-server.txt)
[2016-04-10-3.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/212180/2016-04-10-3.txt)

**Comment by pahimar** [comment]
Should be resolved with build 0.3.0.511
