### ISSUE TITLE
quick update requested to solve specific issue

### ISSUE THREAD

**Issue by border999** [pahimar/Equivalent-Exchange-3#1043]
https://github.com/BuiltBrokenModding/VoltzEngine/issues/35#issuecomment-217745960

**Comment by border999** [comment]
It's a problem with EE3 being unable to do something with ICBM and all the log information is at the provided link.

**Comment by border999** [comment]
Please get back to me quickly, I would like to be able to keep both mods in my modpack.

**Comment by pahimar** [comment]
Resolved in the linked issue

**Comment by border999** [comment]
Thanks.
