### ISSUE TITLE
Can't add EMC value to Tinkers' Construct Oreberry Bushes

### ISSUE THREAD

**Issue by Billeh007** [pahimar/Equivalent-Exchange-3#1044]
To be more specific, I can't get my book to learn them. I have a value assigned to them, it's showing up, and I can use them as EMC to create other items, but my book refuses to learn them. I am unable to place them in the spot for the book to learn, as if they were an item without an EMC value. Using the command to learn a specific item doesn't work either. 1.7.10-0.3.507

**Comment by pahimar** [comment]
Thats because currently EE3 marks all items that start with "ore" in their name as unlearnable.

**Comment by pahimar** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/init/Abilities.java#L13-L18
