### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by TH3GOD88** [pahimar/Equivalent-Exchange-3#1045]
So I downloaded the new release and it keeps crashing my game. I can't seem to fix it unless I go back to the 507 version. 

[fml-client-latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/271811/fml-client-latest.txt)
[crash-2016-05-18_23.45.53-client.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/271812/crash-2016-05-18_23.45.53-client.txt)

**Comment by Han363** [comment]
[crash-2016-05-19_13.57.46-client.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/271815/crash-2016-05-19_13.57.46-client.txt)

i have the same problem

**Comment by pahimar** [comment]
I see what's going on - I'll have a fix later this morning

**Comment by TH3GOD88** [comment]
Thank you Pahimar!

**Comment by border999** [comment]
Crashes also occurring with Chisel2-2.5.1.44  and 
https://github.com/BluSunrize/ImmersiveEngineering/issues/1143 
Immersive Engineering issue can be solved by disabling compatibility but Chisel has no such option. Just notifying you.

**Comment by mindforger** [comment]
@pahimar i think they will if you give them a hint :) or let them crash in a more explained manner 

i was looking in your changelog if anything was noted regaarding API and did not find any info, but then i came across this issue :)

**Comment by pahimar** [comment]
Eh, they'll notice it in the slew of work they have to do in updating to 1.9 :-p
