### ISSUE TITLE
Mod compatibility crash with version 512

### ISSUE THREAD

**Issue by wasweb** [pahimar/Equivalent-Exchange-3#1046]
I have a pack with a lot of mods so went ahead and tried the latest version of EE3. Unfortunately, it crashed after loading the world.
Mod version: 0.3.0.512
Crash log: https://www.dropbox.com/s/c3r4jaqbxd9zt76/crash-2016-05-19_16.14.02-server.txt

**Comment by pahimar** [comment]
The issue is here: https://github.com/pahimar/Equivalent-Exchange-3/blob/35841c20ae549f7c2ac493d2210f1a6665db91c9/src/main/java/com/pahimar/ee3/recipe/RecipeRegistry.java#L71-L79

The fix will be to add detection for multiple entries, rather than a blanket "add all"

**Comment by pahimar** [comment]
New build should be up shortly with a possible fix (0.3.0.513) - would you be able to test it with this same modset again and let me know if the issue is resolved?

**Comment by wasweb** [comment]
Yes, fixed. Thank you for your work!

**Comment by Keyarose** [comment]
Hello, I'm still getting this crash with the new version (0.3.0.513)

report: http://pastebin.com/yC2cCbXz

**Comment by kasper-tfg** [comment]
Hi, I am also still getting this crash server side with version 0.3.0.513.  
http://pastebin.com/wBMUzrHm

**Comment by SkinHeadBaby** [comment]
i dont have the same crash anymore i have this http://paste.ee/p/ePgOF
with the 0.3.0.513 version

**Comment by border999** [comment]
Same issue here, just with sangunite from Metallurgy. and here's another issue with Immersive Engineering too... http://pastebin.com/mCP54QpG

**Comment by pahimar** [comment]
@SkinHeadBaby I just tested with the same two versions of PneumaticCraft and BuildCraft and I was unable to reproduce with the same code in 0.3.0.513

**Comment by border999** [comment]
only took 2 hours to reopen this issue, looks like this github is back up.

**Comment by border999** [comment]
Hi Pahimar, how's the baby?

**Comment by pahimar** [comment]
@border999 this is not for other mods problems - please stick to posting logs for EE3 issues. It's also not for personal conversations.

**Comment by border999** [comment]
k, but the issue is still with how EE3 is processing other mods input.

**Comment by pahimar** [comment]
@border999 I deleted your comment because it has no bearing whatsoever on this issue

This is where it's crashing for some people - https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/recipe/RecipeRegistry.java#L88

Specifically, this has nothing to do with other mods "input." This has to do with a key constraint on the ImmutableMultimap which according to Guava's documentation should be fine. That's what I'm attempting to troubleshoot and debug. Using the same mods and versions as other people here I am unable to reproduce the error so currently I'm proofing the system even further in an attempt to resolve this.

**Comment by kasper-tfg** [comment]
When trying to gen a brand new world on a server with 0.3.0.513 I got this error:
http://pastebin.com/wZYXNnMR
Then I created a new world on 0.3.0.507 then once the world was created I changed over the version to .513 and then got this error:
http://pastebin.com/0wW5se9x
I don't appear to be getting these errors client side but will now go and check.

**Comment by border999** [comment]
this is my latest issue. http://pastebin.com/mCP54QpG

**Comment by pahimar** [comment]
@border999 that's the same crash as you posted earlier, which was pointed out to not be an EE3 crash. It's Immersive Engineering. Go report it there. If you continue to abuse the issues section like this I will be forced to block you from this repo.

@kasper-tfg thank you for that - I'll investigate both

**Comment by border999** [comment]
sorry about that. I can be a massive idiot at times. I won't take up anymore of your time.

**Comment by pahimar** [comment]
Just posted 0.3.0.514 with some more changes - could you all give it a try and let me know how it works for you?

**Comment by kasper-tfg** [comment]
Just tested 0.3.0.514 All appears OK at this time both client and server loaded up fine with already created worlds and new worlds.  Thanks your a legend.

**Comment by Keyarose** [comment]
0.3.0.514 works fine for me.  Thanks for the fix.
