### ISSUE TITLE
EquivalentExchange3-1.7.10-0.3.0.515 has issue with NEI

### ISSUE THREAD

**Issue by border999** [pahimar/Equivalent-Exchange-3#1047]
Here is the crash report for what happened when I attempted to look at Minium dust's recipe in NEI. http://pastebin.com/ridMuchm

**Comment by Han363** [comment]
i have the same problem 
[crash-2016-05-20_14.02.52-client.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/273856/crash-2016-05-20_14.02.52-client.txt)

it seems to only happen on pre existing worlds if i make a new world it works fine

**Comment by wasweb** [comment]
confirmed, crashes with an existing world

**Comment by wasweb** [comment]
I think it comes from the fact that Azure and Verdant dusts have been (more or less) [deprecated]  (https://github.com/pahimar/Equivalent-Exchange-3/commit/1fbc290025e1f8e0d6433ab50b22357024454bd3), but still, in a new world it shows as the recipe of Minium dust. Also, every item with less than 8192 EMC results in 1 Ash in the Calcinator, as I discovered.

**Comment by pahimar** [comment]
Try build 0.3.0.516 please
