### ISSUE TITLE
EE3 build 512+ incompatible with EE3 Helper

### ISSUE THREAD

**Issue by AlHollandiyah** [pahimar/Equivalent-Exchange-3#1048]
Hello,

I found that any build of EE3 higher then 507 (i.e. 512 and up) do not combine with [EE3 Helper](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2442409-ee3-helper-2-2a-in-game-emc-value-management-emc). As soon as both are in a modpack, no matter if there are 0 or 80 other mods, you can NOT load a map in single player anymore. I hope you can find out why this goes wrong and if it can be fixed! Thanks a lot!

**Comment by pahimar** [comment]
Escalated to the mod devs of EE3 Helper, as this is not an EE3 related issue
