### ISSUE TITLE
PlayerKnowledgeRegistry crashes

### ISSUE THREAD

**Issue by Han363** [pahimar/Equivalent-Exchange-3#1050]
on pre existing worlds everything i put into the Calcinator turns into ash
![image](https://cloud.githubusercontent.com/assets/5906444/15446538/60539f0c-1f67-11e6-8b21-0b4ac6ea8280.png)

also this crash happened when i exited to menu 
[crash-2016-05-21_15.14.46-server.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/275720/crash-2016-05-21_15.14.46-server.txt)

**Comment by pahimar** [comment]
Azure and Verdant dust are being deprecated/phased out. The Calcinator now works on a probability function of how likely you are to get a piece of Minium Dust from the inputs you put in. The probability is roughly (value of the item you are calcining / value of minium dust).

Code for it is here: https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/util/CalcinationHelper.java#L14-L32

As for the crash you experienced, that's a crash with the in progress research system rewrite. New builds this weekend should resolve it.

**Comment by pahimar** [comment]
Resolution:
https://github.com/pahimar/Equivalent-Exchange-3/commit/b9d8e00f4b1fd4ceaeab4498a737c80a0181ab49
