### ISSUE TITLE
Found A Bug

### ISSUE THREAD

**Issue by CamaroKing59** [pahimar/Equivalent-Exchange-3#1051]
http://pastebin.com/iAajQwsa

crashes client when exiting a single player world

**Comment by TH3GOD88** [comment]
Version 518 is out.

**Comment by pahimar** [comment]
Resolution:
https://github.com/pahimar/Equivalent-Exchange-3/commit/b9d8e00f4b1fd4ceaeab4498a737c80a0181ab49

Version 0.3.0.518 and above have the fix
