### ISSUE TITLE
Minium Dust

### ISSUE THREAD

**Issue by Han363** [pahimar/Equivalent-Exchange-3#1052]
I know you said that:
"Azure and Verdant dust are being deprecated/phased out. The Calcinator now works on a probability function of how likely you are to get a piece of Minium Dust from the inputs you put in. The probability is roughly (value of the item you are calcining / value of minium dust)."

but on a pre existing world I've put in a stack of diamond blocks in the Calcinator and haven't  gotten a single minimum dust, and when i do it on a new world it happens on the first try. also minimum dust does not have EMC value is that normal?

**Comment by pahimar** [comment]
Minium Dust should have a value, and that's likely why you are only getting ash and no Minium. Delete your energy-values.json and it will regenerate. Alternatively you could go into the config options and set it to regenerate 'Always' from 'As Needed'
