### ISSUE TITLE
518

### ISSUE THREAD

**Issue by TH3GOD88** [pahimar/Equivalent-Exchange-3#1053]
[fml-client-latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/276279/fml-client-latest.txt)
Goes back to the main menu.

**Comment by pahimar** [comment]
There is no crash in that log file. Perhaps its in the latest.log? What is the crash? What were you doing and how do you reproduce the crash?

**Comment by SkinHeadBaby** [comment]
TH3GOD88 i had the same problem with EE3 helper if you have the mod try removing it

**Comment by TH3GOD88** [comment]
[latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/276554/latest.txt)

**Comment by pahimar** [comment]
I still don't see a crash, and I have no idea what you are reporting. Can you explain what happen, what you were doing, and how to reproduce the crash?

**Comment by TH3GOD88** [comment]
Tried to start a single player world; it tries to load for five minutes; then it just goes back to the main menu.

**Comment by pahimar** [comment]
Try removing EE3Helper

**Comment by TH3GOD88** [comment]
Okay; that was the problem. Thank you two.
