### ISSUE TITLE
Dupe bug in EE 522

### ISSUE THREAD

**Issue by tahg** [pahimar/Equivalent-Exchange-3#1057]
The latest, and possibly earlier versions of EE has an issue with removing items and EMC from the table. See here:
[Video of bug](https://dl.dropboxusercontent.com/u/11334557/2016-05-24%2015-12-29.mp4)

**Comment by pahimar** [comment]
Pretty sure this is a rounding issue, and likely also what I'm seeing in #1054

**Comment by tahg** [comment]
If this helps at all, the issue only seems to happen when merging it an existing stack, (either the first suitable stack it finds is partly full, or clicking into your hand with some items already). This generally causes the Table not to remove any EMC.  If you're shift clicking and it finds an empty slot, or you're removing a single item by hand from the table, it works properly.

**Comment by pahimar** [comment]
This does not appear to be related at all to a rounding error. What I thought was a rounding error was actually a fault in the WrappedStack comparator causing the items I was testing this issue with to have bad values.

https://github.com/pahimar/Equivalent-Exchange-3/commit/79bf272f283f1bf3f40dcac2e6fdd913fb6171df

**Comment by tahg** [comment]
This issue still remains as of build 535. Forgive me if I'm coming off as rude for persisting with this.  As I said before, there seems to be an issue with merging stacks. I don't believe this particular bug to have anything to do with the EMC value for individual items.

**Comment by pahimar** [comment]
This is my last major issue before I can move back to MC 1.9 and I have a timeline where I have to have this out by. I am working on this issue today.

**Comment by pahimar** [comment]
Please try again with 0.3.0.540, I think there still may be a bug in there but it might be a bit better now

**Comment by pahimar** [comment]
I believe this is now resolved in 0.3.0.542
