### ISSUE TITLE
 EE3 0.3.0.544 Researching Verdunt &Azure Dust

### ISSUE THREAD

**Issue by HadesDurin** [pahimar/Equivalent-Exchange-3#1063]
After updating from 0.3.0.518 to latest version, i discover to learn all new from the bottom.
so i put stuff in the research table and as of EE3 items i cannot put Verdunt Dust and Azure Dust in it to get it researched.
ash, minium dust, the fuel and coal stuff is researchable for me.

**Comment by pahimar** [comment]
This is intended behaviour. Azure and Verdant dust are being phased out so I marked them as being not learnable. You can still use them as an inout in the Transmutation Tablet though.
