### ISSUE TITLE
Calcinator Only Creating Ash

### ISSUE THREAD

**Issue by Zekent** [pahimar/Equivalent-Exchange-3#1066]
I've tried everything I know how to, including installing/reinstalling the mod. I've tried deleting and reloading the EMC values json file. When I shift-hover over an item, it will state the EMC; but when it's done burning (even diamond) gives me ash.

**Comment by pahimar** [comment]
Check the value of Minium Dust. The calcinator produces minium dust as a percentage chance now (emc of item / emc of minium dust)

**Comment by pahimar** [comment]
Relevant code: https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/util/CalcinationHelper.java#L14-L33

**Comment by Zekent** [comment]
Thank you so much for your quick reply, and help!

**Comment by pahimar** [comment]
Did it end up working?

**Comment by Zekent** [comment]
Yes it did! My diamonds are now successfully converting to minium dust! Thank you so much!
