### ISSUE TITLE
Exchange value is gone

### ISSUE THREAD

**Issue by CitiesXL2815** [pahimar/Equivalent-Exchange-3#1067]
Pahimar the exchange value is gone, it was fine previous update and update today and it was no exchange value

**Comment by pahimar** [comment]
The exchange value for what? What is version of EE3 are you using?

**Comment by CitiesXL2815** [comment]
the new version released yesterday ee3-1.7.10-0.3.0.546 thats the version i'm using

**Comment by pahimar** [comment]
And what items have lost their EMC value?

**Comment by CitiesXL2815** [comment]
all of the items like diamonds and other items in every mod and mojang

**Comment by pahimar** [comment]
Please attach your fml-latest log with the extra energy value debug setting
in the ee3 config turned on

Also please attach your energy-values.json file

**Comment by CitiesXL2815** [comment]
[fml-client-latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/296488/fml-client-latest.txt)

[energy-values.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/296493/energy-values.txt)

do you want me to redo this and put it in .gist instead?

**Comment by border999** [comment]
happening with me too, seems this issue isn't confined to him.

**Comment by pahimar** [comment]
@border999 without the same logs and energy-values json file I cannot help or assume that you have the exact same issue

**Comment by pahimar** [comment]
@CitiesXL2815 looking at the files you've attached I see that EE3 is initializing values (in the fml-client-latest log) and storing them (energy-values). What items are you not seeing values for that you believe that you should be seeing? Are the items learnable in a research station or usable in a transmutation tablet?

**Comment by CitiesXL2815** [comment]
there are in the tablet, but the energy value is missing when you hover the cursor and hold shift

**Comment by pahimar** [comment]
So you can use them in the tablet as input, and you can take them out of the tablet as output right?

**Comment by CitiesXL2815** [comment]
haven't tried yet give me minute to load up

**Comment by CitiesXL2815** [comment]
i can take thing out of the tablet but can't learn anything like putting in the research station

**Comment by pahimar** [comment]
Can you tell me, specifically, what items you are trying to use. Right now you have been very vague, and we have shown that many things do have values and now we have items that do work in the transmutation tablet.

Can you also show me your knowledge-blacklist.json and your exchange-blacklist.json?

**Comment by CitiesXL2815** [comment]
[exchange-blacklist.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/296833/exchange-blacklist.txt)

[knowledge-blacklist.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/296834/knowledge-blacklist.txt)

**Comment by pahimar** [comment]
Ok and what items are you using?

**Comment by CitiesXL2815** [comment]
research item emerald, is that what your asking for using to research?

**Comment by pahimar** [comment]
I need to know specifically what you are doing that isn't doing what you expect. Describe it all. Use pictures.

**Comment by pahimar** [comment]
Is this FTB Inventions?

**Comment by CitiesXL2815** [comment]
no this pack is a private pack for testing, i use the FTB backup system, because i like to test and report the issues to mod DEV's

**Comment by pahimar** [comment]
I still need this: https://github.com/pahimar/Equivalent-Exchange-3/issues/1067#issuecomment-223475406

**Comment by CitiesXL2815** [comment]
so point beening pahimar is that i notice that bug when i hover my mouse over the item and it said no emc value, so i reported that bug to you so it gets fixed, i only jumped on for bit to see the changes in EE3 when it updated until today, but haven't jump on only for you to report the issues i'm having, so i hope this helps, if it doesnt idk what to say to describe it

**Comment by pahimar** [comment]
You have been very ambigious as to what items you are experiencing this behaviour with. It was only a little while ago you mentioned researching emeralds. Yet you also just said you could use the transmutation tablet with items. This corroborates the energy value file that you supplied with shows thousands of values. In the logs you supplied it also states that it loaded 3k+ items.

What I need from you is the information I asked so I can reproduce the issue and see why its happening. Until I get that I am inclined to believe that this is not a bug because I have no information to go on other than the files you have provided which do not show a problem to me at this time.

**Comment by CitiesXL2815** [comment]
i still don't understand, but there is one thing, i like to know how much energy value worth so i can learn it and use the energy value to exchange for diamond and other items that are learned, the energy value tells me that it can be learned and used to exchange, i think this is what you are still not looking for, (this is so hard) i can't think very hard what info you need, plus Watching direwolf20 videos him helping test mods that i want to do like him. maybe i'm to tired to think, sorry pahimar i hope this still helps, is it alright live stream for a bit to show you what's happening to the EMC value?

**Comment by Tikaji** [comment]
To add onto this issue, no exchange values are being loaded at all. I have created an instance where its just EE3 (version 546) and vanilla Minecraft and there are no exchange values in the game, including EE3 items. It appears that all values were calculated correctly when I look in the 'energy-values.json', but those are not being loaded into the game. When in game items, with the exception of the Alchenomicon, cannot be put into the Transmutation Table or Research Station.

I have attached the latest log.
[fml-client-latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/296917/fml-client-latest.txt)
Also it should be noted that on line 373 of the log, you are attempting to load a file that does not exist. The only file in the location specified is 'knowledge-blacklist.json'.

If you need anything else to help diagnose this feel free to ask.

**Comment by AlienXtream** [comment]
im having an issue where ALL emc values are missing in game. cant research anything, cant transmute anything. nothing

**Comment by M4thG33k** [comment]
I am also experiencing this issue; I added ee3 to a pack and every item says it has no exchange value. The files are generating, but they aren't being used (it appears). I can't research anything (including vanilla items) because they have no EMC value.

**Comment by CitiesXL2815** [comment]
thx pahimar your mod is awesome
