### ISSUE TITLE
Non Craftable Items

### ISSUE THREAD

**Issue by MrPotatoGaming** [pahimar/Equivalent-Exchange-3#1068]
Due to the removal of Verdant Dust and Azura dust anything that requires them to craft are currently unable to obtain. These include:  Alchemical Chest/Bag small/medium, alchemical coal (block), and mobius fuel (block). This can easily be fixed with MineTweaker so it isn't a highly important issue - just wanted to let you know incase it was overlooked.

**Comment by pahimar** [comment]
The fuels blocks are still craftable with Minium Dust. As for the small and medium Alchemical Chests this is intended as the way the chest works will also be different in the near future.
