### ISSUE TITLE
How to fix free EMC loops?

### ISSUE THREAD

**Issue by LemADEC** [pahimar/Equivalent-Exchange-3#1070]
when adding other mods, it's quite frequent to have 'free EMC' loops. The most famous one being IC2 with blaze rods.
How can we force EMC value of an item to break those loops and balance a pack?
I can't find much information on that in the wiki nor in the config folder. Did I miss something?

**Comment by pahimar** [comment]
You can;
1) Use the the commands to set energy values on items to correct them to what they "should be" in that particular instance
2) Modify the values in the energy-values.json to do the same thing as in 1
3) Have mod authors that have custom crafting mechanics add code to their mod to notify EE3 (via the EE3 api) how their crafting mechanics work
