### ISSUE TITLE
dynamic EMC question

### ISSUE THREAD

**Issue by SkinHeadBaby** [pahimar/Equivalent-Exchange-3#1072]
hello there wanted to aks is there something in the dynamic EMC thing that makes some items for example oak wood planks have 0.003 EMC bricks block to be 0.007 and similar things while the oak logs have 32 emc and normal item bricks have 64 emc also wool for some reason has 0 emc
maybe when some integration with some other mod ?
since this doesnt happen with only EE3

**Comment by pahimar** [comment]
I don't understand what you are saying

**Comment by SkinHeadBaby** [comment]
Sorry, my english isnt that good.
So oak wood planks have 0.003 emc and they must have 8 emc and bricks have 0.007 emc instead of 256, 
Wool blocks have 0 emc.
So is this caused by some kind of mod integration with another mod or is it a bug caused by another mod.

**Comment by pahimar** [comment]
Could you please upload your:
- latest.log
- fml-client-latest.log
- energy-values.json

**Comment by SkinHeadBaby** [comment]
When i get home i will since i am at work now

**Comment by SkinHeadBaby** [comment]
[energy-values.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/301877/energy-values.txt)

[fml-client-latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/301880/fml-client-latest.txt)
[latest.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/301881/latest.txt)
Here are the files.
I hope this is the corect energy-values.json since i couldnt get it to generate in the world save folder like it used to do before it is in the .minecraft\data\ee3\energy-values

**Comment by pahimar** [comment]
I think its mod interaction in that someone is adding a recipe that EE3 is aware of that is causing the smaller value.
