### ISSUE TITLE
Minium Stone Crashing Instance. 

### ISSUE THREAD

**Issue by Mageloop** [pahimar/Equivalent-Exchange-3#1074]
Hello there, 
In the FTB Inventions pack if you try to put the Minium Stone in the Transmutation Tablet it will crash the game instantly. 

Thanks for your time!

**Comment by zauberparacelsus** [comment]
I think you mean "crash", not crush.

**Comment by pahimar** [comment]
Tested this locally, and it works fine for me.

Please upload the following files after making your instance crash as you reported
- latest.log log file
- fml-client-latest.log log file
- energy-values.json file
