### ISSUE TITLE
server crashing on startup 

### ISSUE THREAD

**Issue by CalTheTroll** [pahimar/Equivalent-Exchange-3#1077]
im trying to run a server and ee3 keeps crashing it any fix at all 
[crash-2016-06-10_23.44.57-server.txt](https://github.com/pahimar/Equivalent-Exchange-3/files/309944/crash-2016-06-10_23.44.57-server.txt)

**Comment by pahimar** [comment]
Equivalent Exchange 3 is now a Java 8 mod, you need to update your Java from 7 to 8 in order to get this to work.

**Comment by CalTheTroll** [comment]
ok ill try it

**Comment by CalTheTroll** [comment]
now the server will not start up

**Comment by pahimar** [comment]
Without a crash log I can't help you.

**Comment by CalTheTroll** [comment]
loged in with root and it is saying 
ltop ftb servers # ./ServerStart.sh
Starting server
./ServerStart.sh: 18: ./ServerStart.sh: java: Permission denied
no log made

**Comment by pahimar** [comment]
Just need to resolve some file permissions on your system then. You should be able to sort that out :) If not I'd suggest taking this to the FTB forums for support as this isn't an EE3 related issue.
