### ISSUE TITLE
setting emc value

### ISSUE THREAD

**Issue by HadesDurin** [pahimar/Equivalent-Exchange-3#1080]
![2016-06-16_12 19 49](https://cloud.githubusercontent.com/assets/5231067/16113481/a3848930-33bc-11e6-9d66-dd96f6f5ee3f.png)
i try to give the object in my hand an emc value
so i type:
/ee3 set-energy-value-current-item <pre|global> 256
the result is thefirst red line in the screenshot
then i try 
/ee3 set-energy-value-current-item <pre|global> <256>
and get the second line which states that <256> is no valid number

what is the right way of adding the value since non of the two examples work and after searching the github and reviewing the wiki its not quoted properly how to add values as you intended it

**Comment by pahimar** [comment]
/ee3 set-energy-value-current-item, then you have to have either pre or
post, then the value.

**Comment by HadesDurin** [comment]
i missed above in both command lines the <pre|global>
/ee3 set-energy-value-current-item <pre|global> 256
and
/ee3 set-energy-value-current-item <pre|global> <256>
and as you can see both didn't work
so what did i do wrong?

**Comment by 50Wliu** [comment]
`/ee3 set-energy-value-current-item pre 256` for example.

**Comment by HadesDurin** [comment]
ok try it out to see if it works
