### ISSUE TITLE
Could Not Resolve MCP Dependency

### ISSUE THREAD

**Issue by AnZaNaMa** [pahimar/Equivalent-Exchange-3#1081]
I was curious as to the current state of EE3 for 1.9.4, so I decided to clone the branch and try to build it, but when I run setupDecompWorkspace, I'm getting [this](http://pastebin.com/dvcBZ909) error. I'm not too versed in all this maven/gradle stuff, so I'm not quite sure how to fix it. Help is appreciated.

**Comment by pahimar** [comment]
Just keep rerunning the command. This is not an EE3 related issue.
