### ISSUE TITLE
EE3 Calculating Item Values using mods?

### ISSUE THREAD

**Issue by barkley8** [pahimar/Equivalent-Exchange-3#1084]
Was trying to calculate emc values in the inventions mod pack and noticed that some of the emc value of item need to be edited in order for it to work properly for me. I know how to change the emc value of an individual item but my question is can i make the system then calculate new emc values using the ones I set? For instance Rubber doesn't have an emc by default but if I set it to 64 and I set tin wire to 128 how can I make it calculate that insulated wire which requires only a crafting grid and one rubber and one tin? I set both rubber and tin and insulated tin wire to be exchangeable as well as learnable. I tried regen energy values but it doesn't calculate the emc value of tin wire, is there any way to fix this?
I understand that I will have to calculate the item values of items that are not made by the crafting table but I would not like to calculate the emc value of every item that can be crafted using items that have known emc.

**Comment by pahimar** [comment]
You need to set these values as pre-calculation values, then run the regenerate energy values command. For example;

While holding rubber
/ee3 set-energy-value-current-item pre 64 

While holding tin wire
/ee3 set-energy-value-current-item pre 128

Then
/ee3 regenerate-energy-values

**Comment by barkley8** [comment]
I did exactly that...

**Comment by FMC312** [comment]
@barkley8 EE3 will calculate the wire values after you do /ee3 regenerate-energy-values. just dropping information by, and letting you know if you havent,
although, I cannot save any Energy values using commands /ee3 set-energy-value-current-item pre
it will be gone after world restart. https://github.com/pahimar/Equivalent-Exchange-3/issues/1076
