### ISSUE TITLE
Custom energy values by OreDictionary string

### ISSUE THREAD

**Issue by pterolatypus** [pahimar/Equivalent-Exchange-3#1090]
Reading through the energy-values file and corresponding code, I saw that you have a system for mapping OreDictionary entries to Energy Values, but there doesn't seem to be a way to set these from in-game. Can we have a command for adding values to OD keys?

**Comment by FMC312** [comment]
i dont know if pahimar / xeno will add this feature because in https://github.com/pahimar/Equivalent-Exchange-3/issues/1078 Pahi says: "It's not correct to just assign the lowest value to all members of an ore dictionary entry as that has a trickle down effect on recipes using those items."

**Comment by pterolatypus** [comment]
Is that comment in the right place? Are you looking for #1056 or #1089?

**Comment by pahimar** [comment]
The plan is a full featured GUI for setting things like this in the 1.10+ version of the mod
