### ISSUE TITLE
Multiplayer Verdant Dust Missing

### ISSUE THREAD

**Issue by Apexii** [pahimar/Equivalent-Exchange-3#1091]
Latest ver. of EE3 (0.3.0.547) seems to have the verdant dust missing from the game. Found this bug in a multiplayer server.

**Comment by Apexii** [comment]
[https://i.gyazo.com/2bee1f6897c884f5b5051bbda978201d.png](url)

**Comment by Apexii** [comment]
Image of NEI
![proof](https://cloud.githubusercontent.com/assets/20236502/16512208/9fb58faa-3f0d-11e6-8c57-66ff54a5c73c.png)

**Comment by pahimar** [comment]
Not a bug. Verdant and Azure dust are being deprecated and won't exist in
later versions of EE3.

Please make sure to search the Github issue tracker before making a new
issue. You might find the answer you are looking for.
