### ISSUE TITLE
Aludel not working

### ISSUE THREAD

**Issue by YMIndustries** [pahimar/Equivalent-Exchange-3#1093]
Hi,

I'm trying to make Marble in my Aludel. It has an EMC value of 4, so theoretically I should be able to make it using 4 Ash, right? Well that wasn't working, so I used Minium Dust to test it out and it still didn't work.

Proof that I've researched Marble: http://i.imgur.com/eyPFjoX.png

Here's the Aludel not doing anything: http://i.imgur.com/K50Efys.png

This is in the FTB Inventions modpack. I'm not sure what version of EE3 it's running, but the "Tome of Alchemical Knowledge" is called the "Alchenomicon". Also NEI says there's only 22 recipes available using the Aludel, which seems incorrect.

Thanks,

YM

**Comment by pahimar** [comment]
I don't know who told you you could use the Aludel to make Marble, but you can't. That was never a recipe the Aludel did. The Aludel has a very small set of things that it makes. What you want is the Transmutation Tablet.

**Comment by YMIndustries** [comment]
Ah I'm sorry, I've been a bit confused by the mod. Last time I used EE there were still Energy Collectors and such.

**Comment by x3n0ph0b3** [comment]
No worries mate. Until like.. a month ago, me too. And I made the thing.
