### ISSUE TITLE
Question regarding Alchemical Tome creation.

### ISSUE THREAD

**Issue by border999** [pahimar/Equivalent-Exchange-3#1095]
In the current latest version of equivalent exchange for 1.7.10. I.E. EquivalentExchange3-1.7.10-0.3.0.547    
It seems that there is no actual way to start equivalent exchange as there doesn't seem to be a way to make either the Alchemical Tome or an actual route to create minium dust without cheating.
If this is because you are working on a new version where some part to these items creation is altered or removed, it would be fairly helpful for it to be pointed out and for assistance to be given on the matter.
Thank you in advance.

**Comment by pahimar** [comment]
When making new issues please search the GitHub issue tracker to see if you are reporting a new issue or if this has already been addressed

* https://github.com/pahimar/Equivalent-Exchange-3/issues/1052
* https://github.com/pahimar/Equivalent-Exchange-3/issues/1066
* https://github.com/pahimar/Equivalent-Exchange-3/issues/1079
* https://github.com/pahimar/Equivalent-Exchange-3/issues/1075

Also, I've addressed this on my Twitter and also on Reddit
* https://www.reddit.com/r/feedthebeast/comments/4m1zg3/ftb_inventions_released/d3smzaz
