### ISSUE TITLE
All recipes dont show and dont get proper dusts

### ISSUE THREAD

**Issue by Shortyrulz** [pahimar/Equivalent-Exchange-3#1098]
Yeah so I downloaded the mod and everything was working fine until I tried to get the minium dust I put a diamond and a emerald in the calcinator and both times I only got a ash dust and when I went in to creative to get the book manually I put the book on the research table and a emerald and nothing happened. I tried every item I had in the vanilla game and same result nothing happened not animation for the written. Please help really want to try this mod 

I am using the current version  
EquivalentExchange3-1.7.10-0.3.0.547.jar

**Comment by pahimar** [comment]
1. Check the EMC value of Minium Dust, and of Diamonds and Emeralds. The process with which Minium Dust is made is defined [here](https://www.reddit.com/r/feedthebeast/comments/4m1zg3/ftb_inventions_released/d3smzaz)
2. The Research Station will not learn an item until the book has been bound to a player. Assuming that you got the book from Creative mode (or NEI/JEI) like you said simply right click while you are holding the book to bind it to yourself. If you still cannot learn an item, check that it has an EMC value.
