### ISSUE TITLE
Null Pointer Exception with Thermal Expansion

### ISSUE THREAD

**Issue by Cyranos** [pahimar/Equivalent-Exchange-3#1100]
Hey @pahimar uhh would you be kind enough to fix this? I don't wont to inconvinience you but this annoys me a little bit. In ftb inventions I had to manually set the aqueous accumulator an emc value though every time I try to take one be it I click on it or shift click it I get a crash.

when just clicking on the item;
http://pastebin.com/exfD5bDY
When shift clicking item;
http://pastebin.com/bXDFGLTP

Obviously its 1.7.10 so it most likely wont be fixed but it would be nice.

**Comment by pahimar** [comment]
Won't fix, there are no new releases for MC 1.7.10.
