### ISSUE TITLE
Suggested balance nerf

### ISSUE THREAD

**Issue by charlesbevans** [pahimar/Equivalent-Exchange-3#1101]
Perhaps there could be a minimum energy value to transform objects from. In other words, some things are too simple to be generally useful. You can make as much cobble and dirt as you want, but all the cobble in the world couldn't make a wooden plank. Setting the EMC value in the config would let people increase or decrease the ease of EMC collection to suit their packs. (Without large-scale resource/cobble automation it becomes harder to get a lot of EMC and the cost of research becomes more noticeable.)
An option would be to allow small scale transmutation of low-value items on a different tablet, possibly 1x1. It would allow smoothing cobble back into stone and so on. It might even provide a good early game option, too weak to make powerful items but still allowing the creation of building materials, etc. (In this case, these low-EMC items should be known from the start so the book becomes a gateway to the next level.)

**Comment by pahimar** [comment]
There are plans on how to further allow people to tweak their preferred level of balance. We are not ready at this time to disclose them however. Please keep an eye out for future announcements :)
