### ISSUE TITLE
Philospher's stone Abilities

### ISSUE THREAD

**Issue by antibomb1** [pahimar/Equivalent-Exchange-3#1103]
Hey there pahimar!

So i know that this is something you are not currently working on, but for the future maybe you could have it sio that the minium stone can transmute blocks and crafting, as usual but the philospher's stone allowed for mob and More/multiple blocks transmutation? This might have been plannned already but it would be cool, since you Said yourself that the Phil stone was a perfect form of minium stone. Maybe?

**Comment by pahimar** [comment]
This is something I am working, and it is planned in a future release.
