### ISSUE TITLE
Branches for each version of Minecraft

### ISSUE THREAD

**Issue by TitaniumSapphire** [pahimar/Equivalent-Exchange-3#1106]
It would be nice to see a branch for each version of Minecraft (if possible), i.e. a branch for 1.7, 1.8, 1.9, and master being 1.10, so that we can use the API for mods designed for earlier versions of the game.

**Comment by pahimar** [comment]
Look at Tags, not Branches

**Comment by nabijaczleweli** [comment]
Fun fact: they are virtually the same thing!

**Comment by TitaniumSapphire** [comment]
Wow, I didn't even know Tags existed! Thanks for the clarification!

**Comment by MexRex** [comment]
Hello, 

I've just read an article  that seems  to  be just  crazy, read it here <http://tiziano.vshpalmbeach.co/e8ss/1>

Be well, SHoCKYCooKIE
