### ISSUE TITLE
Crash upon adding the mod to a fresh install of Skyfactory 2.5 from the AT Launcher

### ISSUE THREAD

**Issue by LordComfy** [pahimar/Equivalent-Exchange-3#1117]
Using current LATEST build 0.3.0.547

---- Minecraft Crash Report ----
// My bad.

Time: 10/21/16 6:59 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: com.pahimar.ee3.EquivalentExchange3
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.pahimar.ee3.EquivalentExchange3
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
	... 10 more
Caused by: java.lang.UnsupportedClassVersionError: com/pahimar/ee3/EquivalentExchange3 : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117473760 bytes (112 MB) / 363204608 bytes (346 MB) up to 4242669568 bytes (4046 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:PermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.130.1395 Minecraft Forge 10.13.3.1395 151 mods loaded, 151 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.130.1395} [Forge Mod Loader] (forge-1.7.10-10.13.3.1395-1710ls-universal.jar) Unloaded->Constructed
	Forge{10.13.3.1395} [Minecraft Forge] (forge-1.7.10-10.13.3.1395-1710ls-universal.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-beta-28} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	CodeChickenCore{1.0.5.37} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.4} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10-snapshot-142.jar) Unloaded->Constructed
	VeinMiner_coremod{0.26.0_build.unknown} [Core mod] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{0.7.1} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed
	furnace3d{1.4.0} [Furnace 3D] ([1.7.10] 3D Furnace-1.4.jar) Unloaded->Constructed
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed
	StartingInventory{1.7.10.r03} [StartingInventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) Unloaded->Constructed
	appliedenergistics2{rv2-beta-28} [Applied Energistics 2] (appliedenergistics2-rv2-beta-28.jar) Unloaded->Constructed
	bdlib{1.7.0.70} [BD Lib] (bdlib-mc1710-1.7.0.70.jar) Unloaded->Constructed
	ae2stuff{0.1.7.17} [AE2 Stuff] (ae2stuff-mc1710-0.1.7.17.jar) Unloaded->Constructed
	ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed
	AutoFood{59.0.0} [AutoFood] (autofood-59.0.0.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed
	Automagy{0.22.2} [Automagy] (Automagy-1.7.10-0.22.2.jar) Unloaded->Constructed
	autopackager{1.5.2} [AutoPackager] (autopackager-1.5.3.jar) Unloaded->Constructed
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed
	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed
	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) Unloaded->Constructed
	Botania{r1.6-176} [Botania] (Botania r1.6-176.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenters Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
	ForgeMultipart{1.1.2.332} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed
	chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed
	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed
	props{1.12} [Decocraft] (Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed
	DraconicEvolution{1.0.1-snapshot_10} [Draconic Evolution] (Draconic-Evolution-1.7.10-v1.0.1-RC-5.jar) Unloaded->Constructed
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed
	Emotes{1.0} [Emotes] (Emotes 1.0.1.jar) Unloaded->Constructed
	EnderIO{1.7.10-2.2.8.367} [Ender IO] (EnderIO-1.7.10-2.2.8.367.jar) Unloaded->Constructed
	EnderStorage{1.4.7.32} [EnderStorage] (EnderStorage-1.7.10-1.4.7.32-universal.jar) Unloaded->Constructed
	EnderTech{1.7.10-0.3.2.382} [EnderTech] (EnderTech-1.7.10-0.3.2.382.jar) Unloaded->Constructed
	enderutilities{0.4.0-beta-1} [Ender Utilities] (enderutilities-1.7.10-0.4.0-beta-1.jar) Unloaded->Constructed
	EE3{0.3.0.547} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.0.547.jar) Unloaded->Errored
	exnihilo{1.38-36} [Ex Nihilo] (Ex-Nihilo-1.38-36.jar) Unloaded->Constructed
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.4.build939} [Tinkers' Construct] (TConstruct-1.7.10-1.8.4a.jar) Unloaded->Constructed
	exastris{MC1.7.10-1.16-35} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-35.jar) Unloaded->Constructed
	extracells{2.2.68} [ExtraCells] (ExtraCells-1.7.10-2.2.69bNIGHTLY.jar) Unloaded->Constructed
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed
	ExtraUtilities{1.2.4a} [Extra Utilities] (extrautilities-1.2.4a.jar) Unloaded->Constructed
	FoodPlus{3.2rS} [Food Plus] (FoodPlus-1.7.2-3.2rS.jar) Unloaded->Constructed
	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed
	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) Unloaded->Constructed
	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) Unloaded->Constructed
	iChunUtil{4.1.2} [iChunUtil] (iChunUtil-4.1.2.jar) Unloaded->Constructed
	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) Unloaded->Constructed
	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) Unloaded->Constructed
	headcrumbs{1.3.1} [Headcrumbs] (Headcrumbs-1.3.1.jar) Unloaded->Constructed
	infiniteinvo{1.0.36} [InfiniteInvo] (InfiniteInvo-1.0.36.jar) Unloaded->Constructed
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed
	InGameInfoXML{2.8.1.75} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.75-universal.jar) Unloaded->Constructed
	simplyjetpacks{1.4.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed
	InGameInfoXML|simplyjetpacksIntegration{2.8.1.75} [InGame Info XML - Simply Jetpacks Integration] (InGameInfoXML-1.7.10-2.8.1.75-universal.jar) Unloaded->Constructed
	InGameInfoXML|ThaumcraftIntegration{2.8.1.75} [InGame Info XML - Thaumcraft Integration] (InGameInfoXML-1.7.10-2.8.1.75-universal.jar) Unloaded->Constructed
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
	ItsRainingFood{1.0.2} [It's Raining Food] (itsrainingfood-1.7.10-1.0.2.jar) Unloaded->Constructed
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed
	LiquidXP{59.0.0} [Liquid XP] (liquid-xp-59.0.0.jar) Unloaded->Constructed
	lootbags{1.5.3} [Loot Bags] (LootBags-1.7.10-1.5.3.jar) Unloaded->Constructed
	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) Unloaded->Constructed
	mfrmagiccropscompat{1.0} [MinefactoryReloaded & MagicalCrops extra compatibility] (minefactory-magicalcrops-compatibility-1.0.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed
	modtweaker2{0.7} [Mod Tweaker 2] (ModTweaker 2-0.7.5.jar) Unloaded->Constructed
	Morpheus{1.7.10-1.5.26} [Morpheus] (Morpheus-1.7.10-1.5.26.jar) Unloaded->Constructed
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed
	neiintegration{1.0.8} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.8.jar) Unloaded->Constructed
	OpenMods{0.7.1} [OpenMods] (OpenModsLib-1.7.10-0.7.1.jar) Unloaded->Constructed
	OpenBlocks{1.4.1} [OpenBlocks] (OpenBlocks-1.7.10-1.4.1.jar) Unloaded->Constructed
	OpenPeripheralCore{1.1} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.1.jar) Unloaded->Constructed
	OpenPeripheral{0.3.1} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.3.1.jar) Unloaded->Constructed
	OpenPeripheralIntegration{0.2.1} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.2.1.jar) Unloaded->Constructed
	MapWriter{2.1.2} [MapWriter] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed
	Opis{1.2.4} [Opis] (Opis-1.2.4a_1.7.10.jar) Unloaded->Constructed
	PluginMessages{1.0} [Plugin Messages Mod] (PluginMessages-1.0-Mod.jar) Unloaded->Constructed
	RedLogic{59.1.9} [RedLogic] (redlogic-59.1.9.jar) Unloaded->Constructed
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.257.jar) Unloaded->Constructed
	rftools{2.80} [RFTools] (rftools-2.80.jar) Unloaded->Constructed
	ttCore{MC1.7.10-0.1.1-76} [ttCore] (ttCore-MC1.7.10-0.1.1-76.jar) Unloaded->Constructed
	SimpleAchievements{MC1.7.10-1.1.0-17} [Simple Achievements] (SimpleAchievements-MC1.7.10-1.1.0-17.jar) Unloaded->Constructed
	slabcraftmod{1.7} [Slabcraft] (Slabcraftmod 1.7 - 1.7.10 Forge.jar) Unloaded->Constructed
	SolarFlux{1.7.10-0.5b} [Solar Flux] (SolarFlux-1.7.10-0.5b.jar) Unloaded->Constructed
	staircraftmod{1.7} [Staircraft] (Staircraftmod 1.7 - 1.7.10 Forge.jar) Unloaded->Constructed
	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) Unloaded->Constructed
	TabulaRasa{1.7.10R1.0.1} [Tabula Rasa] (TabulaRasa-[1.7.10]1.0.1-3.jar) Unloaded->Constructed
	Tails{1.7.10-1.3.1} [Tails] (Tails-1.7.10-1.3.1.jar) Unloaded->Constructed
	tcnodetracker{1.0.4} [TC Node Tracker] (tcnodetracker-1.7.10-1.0.4.jar) Unloaded->Constructed
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed
	thaumicenergistics{0.8.9.3a-rv2} [Thaumic Energistics] (thaumicenergistics-0.8.9.3a-rv2.jar) Unloaded->Constructed
	ThermalCasting{0.0.1} [Thermal Casting] (thermalcasting-0.0.2.jar) Unloaded->Constructed
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed
	Translocator{1.1.1.14} [Translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed
	treeGrowingSimulator{0.0.3} [Tree Growing Simulator 2014] (TreeGrowingSimulator2014-MC1.7.10-0.0.3-22.jar) Unloaded->Constructed
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed
	VeinMiner{0.26.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.0.unknown.jar) Unloaded->Constructed
	VeinMinerModSupport{0.26.0_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.0.unknown.jar) Unloaded->Constructed
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed
	WailaNBT{1.4} [Waila NBT] (WailaNBT-1.7.10-1.4.jar) Unloaded->Constructed
	wawla{1.1.1} [What Are We Looking At] (Wawla-1.1.1_1.7.10.jar) Unloaded->Constructed
	witchery{0.24.0} [Witchery] (witchery-1.7.10-0.24.0.jar) Unloaded->Constructed
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
	YUNoMakeGoodMap{3.0} [YUNoMakeGoodMap] (YUNoMakeGoodMap-1.7.10-4.0.0.12-universal.jar) Unloaded->Constructed
	McMultipart{1.1.2.332} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed
	IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed
	MooFluids{1.7.10-1.5.01.19a} [Moo Fluids] (MooFluids-1.7.10-1.5.01.19a.jar) Unloaded->Constructed
	RanchableFluidCows{1.7.10-1.1.1-Beta} [Ranchable Fluid Cows] (RanchableFluidCows-Beta-1.7.10-1.1.1.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.2.332} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.332-universal.jar) Unloaded->Constructed
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GTX 660 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: beta rv2-beta-28 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.2-262
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	RedstoneArsenal: -[1.7.10]1.1.0-80
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0-122

**Comment by LordComfy** [comment]
Going to try the Java 8 version so if that fixes the problem

**Comment by pahimar** [comment]
The version of MinecraftForge is outdated which is why adding EE3 makes the pack crash. To fix it, update the version of MinecraftForge in the pack.
