### ISSUE TITLE
calcinator not picking up items from buildcraft pipes

### ISSUE THREAD

**Issue by acesmaster1** [pahimar/Equivalent-Exchange-3#1118]
### What should have happened
i want the calcinator to take blocks from buildcraft pipes to automate making verdant dust and when i set it up the block just get spit out onto the floor i tried every face doesnt work i saw another post about it but like it took me down a road where i had no idea wtf i was doing i have newer versions in which im able to do it in single player but  version 1.7.10-0.3.507. is the only one that works with the server host im using    

### What steps do we have to follow so we can reproduce the issue
idk download and run it ???

### Version of Equivalent Exchange 3
EquivalentExchange3-1.7.10-0.3.507 running on forge-1.7.10-10.13.4.1614

**Comment by acesmaster1** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/issues/732 here a link to that other one which i think is the issue here but i got no idea how to fix

**Comment by pahimar** [comment]
Have your server host update their version of EE3 - they are using an old version and the only way to get the behaviour you are looking for is for them to have the latest version of EE3 for MC 1.7.10.
