### ISSUE TITLE
Research station breaks when learning silicon from EnderIO

### ISSUE THREAD

**Issue by Aerneth** [pahimar/Equivalent-Exchange-3#1126]
### What should have happened
The alchenomicon in the research station should have learned the silicon's exchange value (shift-hovering displayed that there was indeed an exchange energy value of 2).

### What actually happened
The black symbols on the pages of the research station filled in all at once (no animation) and the silicon sat there with no progress occurring toward the alchenomicon "learning" it. Removing the silicon or the alchenomicon or both did nothing, and the pages of the research table still had the complete set of symbols visible. The only fix was to break the research station and re-place it in the world or place a new item in to learn.

![capture](https://cloud.githubusercontent.com/assets/25599448/22674115/baa7eaee-eca3-11e6-81a1-010f88cd0930.PNG)

![capture2](https://cloud.githubusercontent.com/assets/25599448/22674245/801f1fd6-eca4-11e6-9d17-4266f737f0c2.PNG)

### What steps do we have to follow so we can reproduce the issue
Place silicon from EnderIO and the alchenomicon into the research table.

### Version of Equivalent Exchange 3
1.7.10-0.3.0.547

**Comment by Aerneth** [comment]
Same thing just happened with another item. Checked alchenomicon and the item was already learned, so this may be the cause.

**Comment by Taifuru** [comment]
I think @pahimar stopped working on 1.7.10 version

**Comment by Aerneth** [comment]
Ah didn't know that. Thanks!
