### ISSUE TITLE
Problem with Latest Tinker's Construct (Minecraft 1.12)

### ISSUE THREAD

**Issue by MikoKudou** [pahimar/Equivalent-Exchange-3#1135]
### What should have happened
Should have received the other 3 books on smelting etc, cannot make Aluminite
### What actually happened
only acquired the first book, and not Alumite is shown in my JEI inventory

**Comment by MikoKudou** [comment]
I've done everything I could possibly think of to get the other books and the ability to make the Alumite. Even downloading the latest version of Tinker's Construct.

**Comment by Nincodedo** [comment]
Umm... This is the Equivalent Exchange Github repo, not Tinker's.

**Comment by MikoKudou** [comment]
this is where I was directed for reporting problems for tinkers

**Comment by Nincodedo** [comment]
This is not where you should have been directed. The Tinker's Construct Github repo can be found here. https://github.com/SlimeKnights/TinkersConstruct/issues

**Comment by pahimar** [comment]
Wrong project
