### ISSUE TITLE
Derp being a derp.

### ISSUE THREAD

**Issue by DrZed** [pahimar/Equivalent-Exchange-3#1146]
All I truly request of you is permission to go ahead with this project for public and not just private. I will do it anyway for my private modpack but I would like to have permission to do it for the public as well.

I decompiled and deobfuscated the latest 1.7.10 code so that I can make the usual transmutations with the minium and philosophers stone work, and add a ritual to make the philosophers stone from the minium stone. I am requesting permission to both have the current source for 1.7.10 and to publicly release the mod with these following changes or have the plans that pahimar originally had to try and implement those.

I still use 1.7.10 and so do many people, 1.8+ ram usage is ridiculous and the load times from model baking is also ridiculous, although the savestate mod I'm working on should solve that issue by storing initialized game in a memory dump basically and just skipping to the model baking and texture loading phases.

Philosophers stone Ritual = Largest chalk circle on ash stone with buckets of blood under the n/s/e/w edges, (obtained from killing 10-1000(configurable) villagers with a bucket on hand) and the option to do my second option same circle with 100 default or more villagers in range of the circle. Drop the minium stone and right click the center block of the chalk circle.

Protomatter recipe = Undecided mostly but idea I'm going with is dropping Aeternalis block and 64 minium dust on a 5x5 chalk circle and activating it.

Dark Matter Tools = High durability or Infinite durability (configurable) tools with max mining level and ability to mine veins of ore, and whole trees.

Might add as configurable inclusion
=================
Red Matter Recipe = 64 Minium dust and 16 Dark Matter on 5x5 Chalk Circle.

Red Matter Tools = Unbreakable, max mining level, AOE Like the original ee2 tools. Damage and range configurable.

Not adding the rings, or the tablet, might add armor

If I add armor darkmatter will be high/infinite durability diamond armor basically
redmatter will give flight and be unbreakable

**Comment by DinnerBeef** [comment]
this is not an issue please do not post this here

**Comment by sebi2306** [comment]
As far as I can see, EE3 is licensed GPL 3 + LGPL 3, which means you shouldn't require permission to distribute your mod. Not sure what it means that both are included as if it were only GPL 3 licensed you would be obligated to license your mod as GPL 3, while the LGPL 3 license has no such requirement. For more information about the EE3's licensing check [COPYING](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/COPYING) and [COPYING.LESSER](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/COPYING.LESSER).

**Comment by Promises** [comment]
git checkout this commit: https://github.com/pahimar/Equivalent-Exchange-3/commit/63ac5b0819c15d372eeb7082a2935a001d01c494

last one for 1.7.10, and just take it from there

**Comment by DrZed** [comment]
If I get time off my current 2 projects I might fall back to minecraft and get this project going with my own flavour, I originally posted this to try and get Pahimars blessing to give a shot in pulling a Fullmetal Alchemist on it.

**Comment by Lomeli12** [comment]
@sebi2306 I'm assuming the LGPL 3 license is for the API, so that mods that add support for EE3 via the API aren't forced to use GPL 3.

**Comment by DrZed** [comment]
Also I decided to make it an addon, even if I have to use ASM when things get annoying. This thread is done, and useless imho.
