### ISSUE TITLE
Random EE3 Transmutation Circle Ideas

### ISSUE THREAD

**Issue by Elayus** [pahimar/Equivalent-Exchange-3#311]
So, let's say your transmuting some iron into gold using your minium stone, but you've forgotten to take the iron you need out of your induction smelter or left it in your project table, and you're too lazy to go get it now cause it's three flights up from where you are.
(This is where the idea comes in.) However, you remember that you placed a transmutation circle in the middle of the room, and create a temporary one on the floor just like it. Then you press a button on your keyboard and a hazy preview of that room with the iron in the smelter pops up and lets you interact with the machines, and chests that are in the room for a limited amount of time. Before the time runs out, you grab your iron, and transmute some gold, but the circle disappears under your feet when the time runs out also, the hazy preview disappears and you never had to leave the room you were originally standing in.

This is purely a hypothetical idea, of course, but would be cool for something like this to be in EE3. I wonder if it is even possible, and how much chunk loading could get in the way. Plus, I think if it is implemented, it should only let you grab materials, rather than weapons because of griefing and such.

The other idea I had was to make a block of stone pop up from a circle in front of you like they always do in FMA or like the "defend" ring from kamen rider wizard's land dragon form, if anyone knows what I'm talking about. Anyways, this would be useful in case you need to put your sword on your hotbar because you forgot to place it there after the last one broke, or if you need to retreat strategically. 

These are purely hypothetical ideas, so questions and comments are welcome. I hope my ideas aren't too bad.

**Comment by border999** [comment]
As for the idea of using a transmutation rice to get around, I was wondering if any of you would consider it possible to program in the Portal of Truth from Fullmetal Alchemist Brotherhood. It would be a very interesting idea considering the fact that a philosophers stone is made with human lives, and the method of accessing the portal is by attempting to make a person. A.K.A Human transmutation.
