### ISSUE TITLE
Finish Minium Stone

### ISSUE THREAD

**Issue by pahimar** [pahimar/Equivalent-Exchange-3#582]
Finish Minium Stone:
- Method to create it
- Limited recipes
- Minium Shards (random chance) on destruction of stone

**Comment by border999** [comment]
Red water is created when you fail in the  attempt to create a philosopher stone, it is a faulty version of a stone, though I am VERY interested to see how Pahimar is going to code the sacrificing of players lives to create his stone. Maybe a mass transmutation circle with a player and many animals inside, or something that would allow a player to survive the transmutation.

**Comment by border999** [comment]
then again you could sacrifice a villager
