### ISSUE TITLE
Calcinator won't accept items from any form of automated transport.

### ISSUE THREAD

**Issue by NullMagic** [pahimar/Equivalent-Exchange-3#732]
The calcinator is unable to accept items from Extra Utilities Transfer (and retrieval) nodes, Buildcraft Pipes, Thaumcraft Golems, Infinitubes Teleposers, Translocators Item Translocator, and Vanilla Hoppers.

However, it is capable of outputting to any of these from it's output slot, meaning only partial automation is possible.

I'm not sure if this is a bug, or intended, however I'd like to suggest that they be capable of receiving items to be calcinated from the top and fuel from the bottom, since many mods, magical and technological, tend to include some form of automated item transport.

**Comment by sebi2306** [comment]
According to [this Guide](http://bedrockminer.jimdo.com/modding-tutorials/basic-modding/multi-texture-blocks/) and [TileEntityCalcinator.java](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/tileentity/TileEntityCalcinator.java) its input is the top:  "public static final int INPUT_INVENTORY_INDEX = 1;"
"Face 1 (Top Face)"

**Comment by iTitus** [comment]
I think you missunderstood something here, the constants are the slot indices (or slot IDs) of the specified slots.

**Comment by sebi2306** [comment]
Derp. I thought it was that because of this 
```
  @Override
    public int[] getAccessibleSlotsFromSide(int side)
    {
        return side == ForgeDirection.DOWN.ordinal() ? new int[]{FUEL_INVENTORY_INDEX, OUTPUT_LEFT_INVENTORY_INDEX, OUTPUT_RIGHT_INVENTORY_INDEX} : new int[]{INPUT_INVENTORY_INDEX, OUTPUT_LEFT_INVENTORY_INDEX, OUTPUT_RIGHT_INVENTORY_INDEX};
    }
```
Well I am just a wannabe modder it's good to be corrected by other people. Thank you Sir!

**Comment by iTitus** [comment]
Brought me to the false track some time ago, too. It is a good style to express these with constants. @pahimar is a good engineer :D

**Comment by sebi2306** [comment]
Too bad he stopped Let's Mod Reboot :(

**Comment by martejj** [comment]
For automation of any kind to work on the Calcinator the Boolean return of the method isItemValidForSlot() in TileEntityCalcinator (line 188) must be changed to true. This is for allowing other blocks like hoppers to drop items into the TileEntity's inventory. Though im not sure if this is on purpose because he has got automation on other blocks.

**Comment by NullMagic** [comment]
I have considered that it might be on purpose, but it'd be really nice to know if it is or not, given how quickly he seems to close complaints/reports about things that are on purpose I've, up until now, just chosen to assume that either he'll get to it when he gets to it or he hasn't yet decided what he wants to do with it.

**Comment by pahimar** [comment]
The Calcinator supports ISidedInventory and therefore should easily support automation

**Comment by tortmancomith** [comment]
i have the same issue as all of the above in anti material mod pack i went in creative and tried all methods of getting fuel to the calcinator. no system or pipe will add to the fuel slot. Pahimar i'm glad to see the mod moving forward and wish you the best wherever that may be. You and the mod are legendary to mine craft and modding in general. test is with build 1.7.1.0-0.2.461.

**Comment by NullMagic** [comment]
I have also tested this just now with the latest version, the calcinator will still not accept anything piped in through any means of transportation.

**Comment by hawken93** [comment]
This bug must have been prematurely closed. What good is ISidedInventory support if there is a typo preventing it from working as martejj pointed out?

**Comment by pahimar** [comment]
@hawken93 I'm confused - what typo? Also no one has reported this being an issue in months. Are you experiencing an issue with this? If so I need details like version of EE3 and Forge.

**Comment by hawken93** [comment]
Ah, sorry... I was playing around with EquivalentExchange3 0.3.507 and I couldn't seem to get any pipes in/out working, so I assumed that it was this bug.. I guess I will test it some more :)

**Comment by hawken93** [comment]
@pahimar WIth this mentioned version I have tested the calcinator with a vanilla hopper from the sides and top, none of which inserts items, is it expected behavior? :)

**Comment by hawken93** [comment]
@pahimar I have looked at the code now and this function seems to explain it to me:
    @Override
    public boolean isItemValidForSlot(int slotIndex, ItemStack itemStack) { return false; }
So I guess that I know roughly how this function should be implemented, so I guess I will try to set up an environment in which I can compile your mod :) I will get back to you if I can make it work! :)

**Comment by hawken93** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/pull/1042
Yay, this seems to work for me :)
I also want to thank you for making this great mod :)
