### ISSUE TITLE
Minium stone

### ISSUE THREAD

**Issue by CubeWrench202** [pahimar/Equivalent-Exchange-3#746]
Hello mr pahimar,can you add some utilities to the minium stone?
- Transmute blocks right-clicking on them (Cobblestone into Stone/Wood in other types of wood/wools into other types of wools,etc).
- Portable crafting table pressing "C".
That is all,it is simple to do,however these utilities were previously in early versions of EE3, but for some reason were removed , thanks for listening :3 , and good job in EE3 Mr.Pahimar!.

**Comment by Fawdrell** [comment]
I think that the philosopher stone will do that...

**Comment by CubeWrench202** [comment]
Come on pahi :V
