### ISSUE TITLE
Quick question for Pahimar:(Non-centralised glyphs in Arrays)

### ISSUE THREAD

**Issue by WolfAmaril** [pahimar/Equivalent-Exchange-3#748]
Given the way alchemical arrays and Dummy blocks currently interact, will the completed version of EE3 allow for arrays with non centralized-glyphs like the one below? ![non-central glyphs](https://cloud.githubusercontent.com/assets/7891004/4688163/9f4a97a6-5669-11e4-953b-ab23c1f830d4.png)

**Comment by pahimar** [comment]
I think for complexities sake this is best left closed
