### ISSUE TITLE
[Question] What is the future of EE3?

### ISSUE THREAD

**Issue by CubeWrench202** [pahimar/Equivalent-Exchange-3#756]
Since you don't have free time to work on EE3, can you tell us a 60% of what you have planned?

**Comment by pahimar** [comment]
1) Presumptuous that I don't have free time to work on EE3. I've been working on it for weeks now in private because I've gotten tired of having to explain every little change to the mod here on git hub. 
2) This is not an issue. This is a request for info. Closing this and locking.
