### ISSUE TITLE
[Dev] NEI Issue

### ISSUE THREAD

**Issue by palaster** [pahimar/Equivalent-Exchange-3#757]
When running the newest commit, when creating a new world, it crashes with an error from nei. You might think how is this my problem. I think were running an outdated version of nei. And, could we possible update, cause I haven't be able to test changes.

This is the Crash:
FML-C Log: http://pastebin.com/3bJLasnp

**Comment by iTitus** [comment]
With newest commit you mean the one that is called 'Big Broken commit [...]'? It is broken.

**Comment by palaster** [comment]
I just checked over the commit, their was only a few issues, and the issue where that the PlayerKnowledge.class was missing some methods, you substitute in some "sudo fixed" methods that fix those errors, other than that I didn't see anything that changed that would cause this error from our side.
