### ISSUE TITLE
Crash report after removing mod

### ISSUE THREAD

**Issue by pieisnotpi** [pahimar/Equivalent-Exchange-3#764]
If you remove a mod after EE3 has initialized the EMC values for the items within the mod, the game crashes on world-load. Crash report: http://pastebin.com/dQ4BKi9L

**Comment by pahimar** [comment]
Confirmed. Will have a fix in the morning

**Comment by pahimar** [comment]
@pieisnotpi in my testing I see it dump the exception to the log, but the server doesn't crash and the player still receives values from the server. Can you confirm?

**Comment by pieisnotpi** [comment]
Huh. After testing in a more isolated environment, the exception does not seem to cause a crash. Not really sure why it did in my environment, but it's worth noting that it was heavily modded (even though that should theoretically not make a difference).

**Comment by OliviOlive** [comment]
I am also experiencing this crash.
I also have a heavily modded setup.
I have also very recently removed a mod after EE3 has initialised values.

However, the crash does not occur on first world load. After exiting the world and joining it again, then it crashes. I have also crashed while dying in the Nether and being respawned back in the Overworld.

**Comment by pahimar** [comment]
Should be fixed now that we've changed to using json to store data as opposed to NBT
