### ISSUE TITLE
Build Issue: setupCiWorkspace

### ISSUE THREAD

**Issue by haza1608** [pahimar/Equivalent-Exchange-3#765]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\h\Desktop\EE3\Equivalent-Exchange-3\build.gradle' line: 168

* What went wrong:
A problem occurred evaluating root project 'Equivalent-Exchange-3'.
> Could not find property 'ee3_curseforge_projectid' on root project 'Equivalent-Exchange-3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.515 secs

**Comment by pahimar** [comment]
Not a bug, simple fix on your end to supply a property with that name and a dummy value.

**Comment by haza1608** [comment]
Sorry, but can you tell me how to do this?

**Comment by 50Wliu** [comment]
Try this:
In `build.properties` just add a new line called `ee3_curseforge_projectid = hahano`.

**Comment by haza1608** [comment]
Nope still not working

**Comment by haza1608** [comment]
Ok I have finally fixed this by changing line 168 from:projectId = project.ee3_curseforge_projectid
to:projectId = project.ext.config.ee3_curseforge_projectid. And line 169 from:apiKey = project.ee3_curseforge_apikey to:apiKey = project.ext.config.ee3_curseforge_apikey.

Also I had to do what 50Wliu said in the build.properties for projectid and apikey.
