### ISSUE TITLE
API Feature Request - Add custom crafting handlers

### ISSUE THREAD

**Issue by TheJulianJES** [pahimar/Equivalent-Exchange-3#769]
Some mods have a custom handler for crafting, maybe allow to register this with EE3 API?

**Comment by WolfAmaril** [comment]
Seconded. It would make it much easier to transmute stuff from thaumcraft/blood magic/basically any magic based mod.

**Comment by pahimar** [comment]
It already exists. Look at RecipeRegistryProxy

**Comment by pahimar** [comment]
https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/api/RecipeRegistryProxy.java

**Comment by TheJulianJES** [comment]
@pahimar I'm so sorry that I derped... Sorry...
