### ISSUE TITLE
Exception in thread "DynamicEV Thread" java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ultrasn0w** [pahimar/Equivalent-Exchange-3#770]
Not really a crash or a serous bug and did not cause any problems, but just for Information purposes:
After closing a world I noticed the DynamicEV Thread throws an Execption (using 0.2.427):
http://pastebin.com/NYNLvENu

Close if this is normal/intended or not important.

Greetings
ultrasn0w

**Comment by pahimar** [comment]
Looks like this is likely a problem with the FluidHelper comparator. Will have a look at it.

**Comment by pahimar** [comment]
Fixed
