### ISSUE TITLE
Crash when using "U" NEI Again

### ISSUE THREAD

**Issue by Neodark7** [pahimar/Equivalent-Exchange-3#771]
Same as https://github.com/pahimar/Equivalent-Exchange-3/issues/758 but with the latest version...

Version: EquivalentExchange3-1.7.10-0.2.429
Crash Repor: http://pastebin.com/7kb7jQQA

**Comment by Neodark7** [comment]
New issue with the 0.2.430

Crash report : http://pastebin.com/HCCLZT3x
FML Log : https://www.dropbox.com/s/0wfzb779ht3zjy2/latest.log?dl=0

**Comment by pahimar** [comment]
Can I get the steps to reproduce this? There are quite a few things that could be null on that line of code and I'm trying to narrow down to understand what is the problem

**Comment by pahimar** [comment]
Try build 431

**Comment by pahimar** [comment]
Try build 432 (build 431 hung for some reason...)

**Comment by Neodark7** [comment]
Fixed with 432 :)
