### ISSUE TITLE
Server crash when placing Calcinator

### ISSUE THREAD

**Issue by GirafiStudios** [pahimar/Equivalent-Exchange-3#774]
There seems to be going some issues on with the latest version of EE3.
Whenever you place a Calcinator on server, it casues it to crash. It works fine in singleplayer tho.
If you load up a wolrd with a calcinator placed in the world in a earlier version of EE3, where this crash was not happening, and update to the latest version of EE3 this crash will also happen.

I can't refuse that this crash will also happen with other blocks. The Calcinator was just my choosed block to test this with.

Equivalent Exchange 3 Version: 0.2.433
Minecraft Forge Version: 10.13.2.1291

Crash report: http://pastebin.com/Jd4KvZNa
This issue is most likely related to #773 and #772

**Comment by pahimar** [comment]
Not related at all to any EE3 blocks, it's related to this line - https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/handler/PlayerEventHandler.java#L50

This happens (currently) when mods update on the server and the server is not set to regen values when mods change. The short term fix is to delete the data/ee3/energyvalues/ directory on the server. The long term fix is something I'm working on.

Could you please have the server owner delete the ./data/ee3/energyvalues/ directory on the server and restart the server? This will force the energy values to regenerate with the new set of mods. Also have them change the ee3 config for regenerating values from "Never" to "When Mods Change"

**Comment by GirafiStudios** [comment]
Ahh, i see ^^

I'm the owner of the server - and already tried to delete data/ee3/energyvalues/ , that did not fix it.
But changing the config option to "When Mods Change" fixed it!

Thanks for the help ^^

**Comment by pahimar** [comment]
Did you shut down the server, delete the folder, then start up the server again?

**Comment by GirafiStudios** [comment]
Yeah, multiple times. I deleted all EE3 folders, which were to find anywhere inside the world map folder ^^

**Comment by CubeWrench202** [comment]
DId u fix it?
