### ISSUE TITLE
Crash Report: Updating Screen Events

### ISSUE THREAD

**Issue by stephenmc608** [pahimar/Equivalent-Exchange-3#775]
I was using the Calcinator to create Minium Dust. I put 8 Diamonds in the input slot and some Coal in the fuel slot. When I tried to take the Minium Dust out of the Calcinator, my game crashed with this report:
https://gist.github.com/stephenmc608/268534d0a8937bb9f52f

EE3 Version: 0.2.433.
Forge Version: 10.13.2.1307

**Comment by Dynious** [comment]
You should report this to the devs of BluePower. BluePower is not checking the size of the inventory when a crafting event is called and (probably) assumes it's a 3x3.

**Comment by stephenmc608** [comment]
Ok. I just submitted it to the BluePower Github.
https://github.com/Qmunity/BluePower/issues/309
