### ISSUE TITLE
Minium stone recipes not working

### ISSUE THREAD

**Issue by mayumi7** [pahimar/Equivalent-Exchange-3#779]
Not sure if they're even supposed to work but they were implemented for 1.6.4 so I just assume they should still work.

Playing on 1.7.10 with your standard mod set, BC, TE, AE, Minefactory and galacticraft with some minor mods too.

NEI doesn't show any transmutation recipes for the minium stone, just that I can melt it down in the calcinator.

Another mod interfering, a bug, or not implemented yet?
![image](https://cloud.githubusercontent.com/assets/7888465/6435337/20d07e3c-c094-11e4-93a3-99379e5dccf2.png)

**Comment by pahimar** [comment]
Not a bug. Transmutation is coming back in a way different than before. Soon too.
