### ISSUE TITLE
crashing on removing items from calcinator

### ISSUE THREAD

**Issue by chanzie** [pahimar/Equivalent-Exchange-3#780]
http://pastebin.com/FcPwKNbm

this is what is happening each time I try to remove something from the calcainator, if I break the calcanitor the items are fine its just when trying to removing the items

**Comment by pahimar** [comment]
This is not a ee3 bug. The stack is indicating the another mod (enderbook by the look of it) is attempting to remove an item from a slot that doesn't exist. Please report this bug to the appropriate mod developer.
