### ISSUE TITLE
Idea: Decorative Sigils

### ISSUE THREAD

**Issue by WolfAmaril** [pahimar/Equivalent-Exchange-3#785]
So I've been thinking, and I was wondering how easy it would be to pull in the glyph system from build 354 (back when rotation worked, and you could still layer glyphs over each other slightly offset) as a purely decorative option. I know I'd love to have strange--if useless--transmutation circles covering the walls and floors of my alchemy--and other magic--rooms.

**Comment by pahimar** [comment]
The system is pretty much the same except that you cannot overlay multiple glyphs/arrays on top of each other. That system was just too complex.

However, rotation does work. The differences are tiny in the only implemented alchemy array so far (it's mostly symmetrical), but rotation works the same as before
