### ISSUE TITLE
NEI Alchemical Bag/Dust Crash

### ISSUE THREAD

**Issue by Soundtoxin** [pahimar/Equivalent-Exchange-3#786]
I was on my server and remembered I'd just added EE3, so I typed "@equivalent" into NEI and decided to click on Alchemical Bag to see its recipe. It requires a machine and dust I'm not familiar with, so next I clicked on the dust it uses. My game completely crashed to desktop afterward.

Here's the client log:
http://sprunge.us/KAGc

**Comment by equivalent** [comment]
typing "@equivalent" is like typing Voldemort :) , ...I've receive notification
