### ISSUE TITLE
Dark Matter Tools Ideas... and other ideas

### ISSUE THREAD

**Issue by Boss314159** [pahimar/Equivalent-Exchange-3#788]
make EMC like a power system for the tools maybe

dark matter pick -> modes like insta-mine or change mining range (1x1,3x3,5x5, etc.)

make dark matter stuff pretty hard to get and more OP

**Comment by WolfAmaril** [comment]
That seems kind of contrary to the point of the mod, wherein you make stuff form EMC.
What if you had a mode on the Dark Matter Pickaxe where it converted anything it mined into EMC and stored it in whatever stores EMC

**Comment by Boss314159** [comment]
That mode will be cool. I know about the EMC usage thing.
