### ISSUE TITLE
Trying to display usage on an item can crash the game.

### ISSUE THREAD

**Issue by Borkmeir** [pahimar/Equivalent-Exchange-3#791]
I have been experiencing a crash in my in developent modpack that appears to be attributed to EE3 for the past couple of weeks now.  It seems that EE3 really doesn't like it when the ore dictionary entries change in a world without a mod being added/removed/updated, at least that's when I have consistently encountered this crash.  Here's the crash report;

http://paste.ee/p/rsO6Y

However, I am now getting the crash regardless of whether or not I have changed anything.  Now every time I try to get the usage of Refined Iron Ingots from IC2, in my current save, the game insta-crashes.  The crash does not appear to occur in a newly generated world.  It could be due to some interactions with another mod but EE3 is the first thing in the list so I thought I'd start here.

I'm using build 461 of EE3 and have Fast Craft 1.21 installed in the current instance.  The problem has persisted across multiple builds of Forge, the current instance is using 1389, but I have used 1360, 1358, 1355, & 1351 and encountered the crash on all of them.  Light Loader is also installed in the instance and has been build 04 during every documented instance of this crash.  I have also had Optifine installed on past versions, but it does not appear to have any effect on this problem either way.

If needed I can provide you with a private link to the development instance, but it is currently a very resource hungry pack.

**Comment by pahimar** [comment]
Fixed, it was a NPE related event where an OreStack wouldn't have had a nae
