### ISSUE TITLE
Crash when connecting to a world

### ISSUE THREAD

**Issue by Gwanunig** [pahimar/Equivalent-Exchange-3#796]
Crash when entering a world; http://pastebin.com/LcFRKfhz

**Comment by pahimar** [comment]
Did you have an earlier version of EE3 installed at some point?

**Comment by pahimar** [comment]
Also can I get the FML log?

**Comment by Gwanunig** [comment]
No, fresh world, fresh install just to test EE3.  Unfortunately pastebin is in two parts due to size; part 1http://pastebin.com/LHh5FEL8 part 2 http://pastebin.com/pDfALaA6

**Comment by Gwanunig** [comment]
Working with recommended version of forge.

**Comment by Deckee** [comment]
Im having the same crash bug, my understanding is there is a fatal error when the client connects to the local sever.

**Comment by pahimar** [comment]
Fixed
