### ISSUE TITLE
Multiple bags with common UUIDs

### ISSUE THREAD

**Issue by Phyn** [pahimar/Equivalent-Exchange-3#800]
This is the issue found on Soaryn's stream.

There seem to be corner cases where the UUID exists in multiple bags, and the inventory updates the first matching bag it finds.

[This](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/inventory/InventoryAlchemicalBag.java#L43-L51) seems to be backwards, given that [this](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/inventory/InventoryAlchemicalBag.java#L20-L41) has already set it and made sure that it exists.

**Comment by Dynious** [comment]
If I remember correctly there was a bug where when copying the bags in
creative mode (middle mouse button) the UUID wouldn't change. Not sure if
that was fixed, there were a bunch of fixes for the bags lately.

Op zo 3 mei 2015 06:24 schreef Phyn <notifications@github.com>:

**Comment by Phyn** [comment]
This is related to creative copying, but I'm referencing the fact that the inventory code is searching for the ItemStack that it already has a reference to.

**Comment by Phyn** [comment]
This entire issue will go away when the bag system is finalized, but it also serves as an example of why not to combine elements of multiple inventory systems.

The issue seems to stem from the fact that the bag code is written to work from a central registry, but is instead using the player inventory as the registry.
