### ISSUE TITLE
Crash: Shift Clicking more items them I can hold out of the Transmutation Table

### ISSUE THREAD

**Issue by LuigiHutch** [pahimar/Equivalent-Exchange-3#802]
EE3: 1.7.10-0.3.478
I had 550,430 emc in my transmutation table. And then I tried to shift click as many wooden wooden pressure plates (worth 16 emc) into my inventory and then i crashed:
https://gist.github.com/LouisHutch/95ff7937d1457b1c0667

**Comment by Navruz009** [comment]
I had the same issue.

**Comment by plumpudding** [comment]
Seems to occur when you try to shift out more than your inventory can hold
@lhenrique03 maybe rename this to "crash when shifting too many items" or something

[similar crash with latest version](https://gist.github.com/plumpudding/7a44f497f4c3ad9d210d)

could be related to the changes of https://github.com/pahimar/Equivalent-Exchange-3/commit/34cda981c049a202ba1a0316521468cce95e1ca3 in ContainerTransmutationTablet.java

**Comment by Staegrin** [comment]
Had the same crash. Thought I should report it and found it was a known problem.
crashlog:
http://pastebin.com/4NpqRSZA

**Comment by plumpudding** [comment]
actually this is pretty major I think

**Comment by SeanMooney** [comment]
i appear to have hit the same error in EquivalentExchange3-1.7.10-0.3.507.jar
http://pastebin.com/s0QmCQMS

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
