### ISSUE TITLE
Fluid Reqistry Crash

### ISSUE THREAD

**Issue by WolfAmaril** [pahimar/Equivalent-Exchange-3#804]
http://pastebin.com/uvPkB5s5

I get this crash when using a fresh instance with only EE3, NEI, and CCCore

**Comment by pahimar** [comment]
Update to a newer version of Forge

**Comment by WolfAmaril** [comment]
Ohright, forgot to add, using the most recent recommended version of forge.
That too old?

**Comment by laz2727** [comment]
Recommended is *always* too old.

**Comment by WolfAmaril** [comment]
But it is usually stable, which is nice.
Any suggestions on what version to try EE3 with?

**Comment by laz2727** [comment]
Latest. Forge is almost never unstable.

**Comment by MCShammer** [comment]
I had success with forge build # 10.13.3.1388 the newest didn't like other mods in the pack I'm using.
