### ISSUE TITLE
Crash with EE3

### ISSUE THREAD

**Issue by lhenrique03** [pahimar/Equivalent-Exchange-3#805]
Version: 0.3.478; Forge Version: 1399
-Steps: Put diamond in trasmutation table; remove 4 gold; put 4 gold in; remove 32 iron; 32 iron in; shift click stone out, crash.
-Crash Report: http://pastebin.com/DgZrrMF5
I don't know if it matters but the items taught were: redstone, stone, diamond, gold and iron.

**Comment by plumpudding** [comment]
Seems to occur when you try to shift out more than your inventory can hold

similar crash: https://gist.github.com/plumpudding/7a44f497f4c3ad9d210d

**Comment by lhenrique03** [comment]
Sorry, I didn't check :P

**Comment by plumpudding** [comment]
So you can close this
