### ISSUE TITLE
Bug: Unable to create EMC values

### ISSUE THREAD

**Issue by Gwanunig** [pahimar/Equivalent-Exchange-3#806]
EE3 seems to be unable to create energy values for vanilla items when another mod adds an alternate recipe for the item (i.e. iron blocks) containing items that don't have an energy value. Could it be possible for it to default to the vanilla recipe? I'm not expecting a fix any time soon, as its early days and this issue only exists alongside other mods.

**Comment by Sky2hawkZ** [comment]
I would just like to add to the list of people having this exact problem!

**Comment by pahimar** [comment]
This is likely due to people using the OreDictionary in funny ways. You can always set the correct values yourself in your instances using /ee3 set-energy-value
