### ISSUE TITLE
No exchange value for sticks

### ISSUE THREAD

**Issue by stiener** [pahimar/Equivalent-Exchange-3#813]
Sticks don't have an exchange value as well as a few other items like pistons. The values are fine with just EE3 installed but with a modified version of the DW20 pack with an updated forge the values aren't there.

![2015-05-05_18 12 52](https://cloud.githubusercontent.com/assets/11169059/7478992/77f85e4c-f356-11e4-9ef3-cba2f165ad6c.png)

**Comment by Keltas** [comment]
I have very similar problem, however with a lot of items. The only thing they have in common that I have noticed is the fact that each of these items has an alternative recipe using items with no exchange value. For example I have no exchange value on an axe, it is made of sticks, with no exchange value and 2 sticks can be made from an oak twig from steve's carts 2, which has no exchange value.

**Comment by stiener** [comment]
white wool and blue wool have values but none of the other ones do and I haven't seen any strange recipes for the others that isn't also true for white and blue, same thing for hardened clay (the non coloured version) and blue stained clay. Sticks that ore dictionaryed work so something like natura sticks work. It's a bit weird anyway I'm going to backup my instance and remove mods one by one, I tried doing it yesterday but the curse client was being twitchy and not liking mods being disabled and enabled again

**Comment by pahimar** [comment]
If something doesn't have a value that you would expect, you can always assign it. Use the /ee3 set-energy-value command to set a post-assigned value to an item and it will stick :).

**Comment by stiener** [comment]
ok thank you
