### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by randysdoom** [pahimar/Equivalent-Exchange-3#814]
Crashed when placing a research table in creative. 

http://pastebin.com/wsALeL65

**Comment by pahimar** [comment]
Can you get me your FML log for the crash?

**Comment by randysdoom** [comment]
http://pastebin.com/p50aEYCG

This is the best I can do.

And I went skimming through this, funny thing is, there was no aludel placed in the world.

**Comment by pahimar** [comment]
Only could have been called if there was a Aludel Base somewhere near your player when you logged in. Can you confirm if you are still crashing with latest EE3? 0.3.505 at the time of this comment

**Comment by randysdoom** [comment]
It Does not seem to be happening anymore. Can not seem to replicate the crash.
