### ISSUE TITLE
EMC shenanigans

### ISSUE THREAD

**Issue by Deathlymad** [pahimar/Equivalent-Exchange-3#815]
!! Disclaimer !! This is my own opinion you don't have to share it. Feel free to comment though

Most important thing AWESOME MOD!!
okay now lets get to it.
1. I don't think that the Transmutation Table should be able to permanently store EMC... at least not in the beginning.
1.1 Apparently is Ash Stone (the basis of the transmutation Table) rather unaffected by EMC. Maybe one could build a chamber out of ash stone to prevent EMC loss. 
1.2 Depending on how you think of EMC it might jump over to other to other alchemical construct or it could have "unforseen consequences". If you don't have ideas for unforeseen consequences ask evil people like jaded they will probably come up with something :).
2. If I think of EMC as an energy like gaseous resonating somethingness I fell like manipulating large amounts of ...things... should have effect on the surroundings. Some Materials should be more immune than others ( see 1)
3. I am not sure if I already posted that somewhere if I did sorry for reapeating. But I would love threedimensional crafting and some ind of technical/designual challenge to design an efficient setupto efficiently manipulate EMC.

4. Nothing comes without cost even the equivalent exchange (I can't help thinking about Fullmetal alchemist on this one.... I am sorry). But seriously one can't just convert one item into another without cost, if one could go overboard with that on a server he would get a book from someone who researched everything and just keeps utilizing the same EMC over and over (i bet you could change machine for machine at some point.). Add Some tiers, some complexity some challenge some cost to not make that hopelessly OP. 
4.1 Just an Idea but see the crafting steps from hardcoded objects to desired object as tier steps which make the transmutation process more complex.

**Comment by pahimar** [comment]
Not an issue, but thanks for the ideas

**Comment by Deathlymad** [comment]
wait so it was right to post here?
