### ISSUE TITLE
Not able to change edit EMC values

### ISSUE THREAD

**Issue by MinecraftB0ss** [pahimar/Equivalent-Exchange-3#816]
I am working on a modpack centered around using EE3 as the main way of getting items(through transmutation). To do this i have to edit/assign new emc values for items to balance the pack out.

Im not exactly sure what the "pre/post" does in the "/ee3 set-energy-value" command, but i change it on both(pre/post). The value sticks until i leave the world, then it reverts back to nothing/the old value. 

Im also not entirely sure wht the template sub command does either.

Im not sure if its a bug, or if im just not doing it right, but if its a mistake on my part, it would be great to be informed of the correct way to do it, as i didnt see any documentation on this/

**Comment by pahimar** [comment]
Thorough documentation is coming but the short of it is;

pre - this is the stage of DynEMC where values are initially loaded. This is before the dynamic calculations are done. Use this stage if you want to assign a few values and have the rest be dynamically calculated

post - this is the stage of DynEMC AFTER dynamic calculations are run. Any values added here override any previously assigned/calculated values.

Other than that, the commands in game should outline the syntax for how to use the commands.
