### ISSUE TITLE
Compiling Failed

### ISSUE THREAD

**Issue by Kosti1** [pahimar/Equivalent-Exchange-3#817]
i run command "gradle SetupCiWorkspace" and i got this text:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/********/GitHub/Equivalent-Exchange-3/Build.gradle' line: 5

* What went wrong:
A problem occurred evaluating root project 'Equivalent-Exchange-3'.
Cause: Could not find method maven() for arguments [build_4bjj70hedgmm13okv8scp3qfoq$_run_closure1_closure2_closure4@2a3502] on resolver container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

then i run gradle -version for version numbers :)

Gradle 1.0-milestone-3

Groovy: 1.8.6

Ant: Apache Ant(TM) version 1.8.2 compiled on December 3 2011

Ivy: non official version

JVM: 1.6.0_35 (Sun Microsystems Inc. 23.25-b01

OS: Linux 3.2.0-82-lowpatency-pae i386

**Comment by iTitus** [comment]
Please update Java and Gradle.

**Comment by Kosti1** [comment]
i try :smile:

**Comment by Kosti1** [comment]
thx it works
