### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by Abchrisabc** [pahimar/Equivalent-Exchange-3#818]
Where and how do I hook into the api to add EMC values for my own mod?

**Comment by pahimar** [comment]
API: https://github.com/pahimar/Equivalent-Exchange-3/tree/master/src/main/java/com/pahimar/ee3/api

Some tutorials on how to use @API annotations: http://forum.feed-the-beast.com/threads/mod-developers-read-up.47091/

Example of how to use the EE3 API: https://github.com/MineMaarten/PneumaticCraft/blob/master/src/pneumaticCraft/common/thirdparty/ee3/EE3.java
