### ISSUE TITLE
[Suggestion] Change the chalk increase key

### ISSUE THREAD

**Issue by JAWSAWN** [pahimar/Equivalent-Exchange-3#819]
V key is used by lots of mods. And thus creating conflicts. Also I find that meanless to put it on a other key. My suggestion is to set it to either shift or control like Ztones.

**Comment by pahimar** [comment]
The use of V for the Charge key has been used for over 4 years in EE. We're not changing because other people jumped on board.

Like always, if you have a keybinding conflict, adjust it to your needs (also Shift by default is Sneak, so that's a terrible keybinding suggestion)
