### ISSUE TITLE
DynEMC dosent recalculate vanilla items properly

### ISSUE THREAD

**Issue by MinecraftB0ss** [pahimar/Equivalent-Exchange-3#820]
The DynEMC system looks like it dosent recalculate vanilla crafted items when an item is changed from its default value. (Ex. redstone changed to 5 but piston EMC value not adjusted to match, or any vanilla crafting recipe using redstone).

From what i understood, it calculated crafted items from their base items used to craft. Any mod-added items that used redstone in their crafting recipe got calculated properly however. If these values are actually supposed to be static, that would be great to know.

**Comment by Yellbana** [comment]
All of the static values are in this class.
https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/init/EnergyValues.java

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
