### ISSUE TITLE
EMC shennanigamc [Sugestion]

### ISSUE THREAD

**Issue by bsaksida** [pahimar/Equivalent-Exchange-3#821]
I have noticed that sometimes (Most of the times) EMC doesn't properly assing by not assigng EMC to items. I can add EMC by command. However since its DynamicEMC i would expect to get EMC recalulated but it didn't. Based on config i saw how recalculation works. And i fell it is not enough.

Can you please add a command to forcefully recalculates everything.

PS: when adding EMC to current item i saw word PRE and POST. What's the difrrence betwen these two?

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
