### ISSUE TITLE
Crash with Direwolf20 pack cont..

### ISSUE THREAD

**Issue by yetma** [pahimar/Equivalent-Exchange-3#822]
I have posted this as a comment on my original issue but figured that i should make a new one as the original has been closed.

Updated to the Direwolf20 1.3.0 version so as to be using the newer version of forge and added ee3 0.3.501 to it i am now suffering a new crash error.

http://pastebin.com/jX4bn9bw

**Comment by Parker8283** [comment]
Update Pneumaticcraft. That's the mod at fault here.

**Comment by yetma** [comment]
Thats done it, cheers
