### ISSUE TITLE
Clearing knowledge tome

### ISSUE THREAD

**Issue by Cutrone** [pahimar/Equivalent-Exchange-3#824]
So while I was testing out a world, I ran into a bug, when I broke my transmutation tablet with the knowledge tome inside of it, the knowledge tome was cleared. I was able to add the items back to it, but my knowledge was entirely lost. Not entirely sure of the cause of this. 

I had thought that the knowledge was stored on the player, but if that was the case, then loosing the knowledge by the book not storing the data properly when dropped should not cause it.

**Comment by Qsandas** [comment]
Did it perhaps unbind itself from you? If so, you may have to re-bind it to yourself before putting it back in a tablet.

**Comment by pahimar** [comment]
Solved with #834
