### ISSUE TITLE
Item duping.

### ISSUE THREAD

**Issue by Smither007** [pahimar/Equivalent-Exchange-3#825]
Double clicking provides a bonus 2 items from thin air. (images to explain further) http://imgur.com/a/KyfrF#3

**Comment by pahimar** [comment]
The images don't really explain anything. A video would be better. Also, a log.

**Comment by Smither007** [comment]
So basically what is happening whenever I do that is I put in 2 (or more) items of the same kind that stack in separate slots and when I double click the items to remove all of them it provides 2 extra items regardless of the amount in there (i.e. I put in 2 stone and will get back 4 stone). Running 0.3.502.
One note is it's iffy sometimes where it works on some things then sometimes it doesn't work, like with the minium dust it worked perfectly then it just stopped working but it would still work with stone/beef or other random items.

**Comment by nhdadmin** [comment]
it appears to have been fixed in commit e6faf84, can someone confirm
