### ISSUE TITLE
Full Inventory, EMC Deleted

### ISSUE THREAD

**Issue by Unknown-88** [pahimar/Equivalent-Exchange-3#830]
In the transmutation tablet, when inventory is full, shift clicking out an item will give no items in inventory or in world, and consumes the energy of one item.

**Comment by IntelliSun** [comment]
Now fixed with 10e51931c6b605aeff0385ef959750d5ae21e508.
Thank you!

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
