### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Shad0wB1ade** [pahimar/Equivalent-Exchange-3#835]
So I made a video about the duplication bug with the alchemical bags (this one is after the bug that RWTema found with the bags): https://www.youtube.com/watch?v=fBVTtvz0SnA

**Comment by krzys-h** [comment]
You don't even need to throw the bag on the ground, it's enough if you shift-click while the bag is on your mouse cursor and then reopen the gui.

**Comment by Shad0wB1ade** [comment]
Yeah and there is another bug that I can not really test because its easily doable only in multiplayer... if a player is looking at a alchemical chest GUI and another player breaks the chest, the player looking at the gui still has the gui open and can take stuff out so it is just a duplication bug. As I said it was some versions back and I can not really test it now :/. I just didn't see anything about that bug in the changelog.

**Comment by nhdadmin** [comment]
Confirmed to still be present in 0.3.507

**Comment by pahimar** [comment]
Fixed with #904
