### ISSUE TITLE
Ore processing Emc loop.. Should ores really have emc values?

### ISSUE THREAD

**Issue by Unknown-88** [pahimar/Equivalent-Exchange-3#836]
Should ores really have emc values? As I am sure your aware, at present I can put a gold ore costing 2048 in a pulverizer, and receive 2 gold dust... smelt, and now I have 2 * 2048 emc gold... rinse and repeat. Yes, this can easily have a specific handling code build around, but there are many different mods, with many different ore processing mechanics, so it seems unlikely that an emc loop will not be present.

**Comment by krzys-h** [comment]
You can't pull gold ore from the transmutation tablet because you can't learn anything that has ore dictionary name starting with "ore"
See https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/init/Abilities.java#L12-L27

**Comment by pahimar** [comment]
Addressed with the Ability system.

Please try the thing you are reporting before reporting it :)

**Comment by Unknown-88** [comment]
I was able to learn gold, and iron ore... I will do some testing and further research + screenshot in a little bit.

**Comment by pahimar** [comment]
Update

**Comment by Unknown-88** [comment]
Just did, dident realize I dident have the latest version, although current ores remain researched, new ores can not be learned. Thank you for your time, sorry for pointing out a false bug.
