### ISSUE TITLE
Knowledge doesn't save on a per world basis

### ISSUE THREAD

**Issue by cgwheeler96** [pahimar/Equivalent-Exchange-3#839]
Version: 0.3.505
OS: Ubuntu 14.04.2

Whenever I learn an item in one world (like a creative world) the knowledge I gain persists for all of my other worlds (like my survival world) this is very annoying as I can't test things in creative without it affecting my survival world.

Steps to reproduce:
Create two different worlds.
Create a research table and tome in both.
Learn an item in one world.
Open the other world and see that the knowledge has transferred to the other tome.

Even deleting the player data in the each save file does not prevent this from happening, it just refreshes.

**Comment by pahimar** [comment]
Yup this is a bug and is on my list. Work around for now is to restart your minecraft instance. Fix incoming tomorrow.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
