### ISSUE TITLE
{Question} EMC Assigning

### ISSUE THREAD

**Issue by randysdoom** [pahimar/Equivalent-Exchange-3#840]
Will you be handling the EMC Values for modded ingots (Eg. Copper, Tin..etc.etc) Or are you going to leave that up to the Mod's Author?

**Comment by squirrelkiller** [comment]
As a short term fix I can suggest you can temporarily handle that yourself by assigning your own EMC. I need to look into how the code works to make an addon for my own server that just adds those EMC values based on some numbers that I felt are fair based on a few ratios I randomly decided on (2copper>1iron, 1platinum>2gold, 1iron>1tin, 1lead>1iron, 1nickel>1lead).

In the world save folder there is an ee3 folder, follow that to EnergyValues then in there are two archives. In these archives are jsons. Add the following to each of the .jsons in each archives. It handles the ingots. This is my temporary fix.

,
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotCopper",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 128.0
    }
  },
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotSilver",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 1024.0
    }
  },
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotTin",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 256.0
    }
  },
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotPlatinum",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 4096.0
    }
  },
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotLead",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 256.0
    }
  },
  {
    "wrappedStack": {
      "type": "orestack",
      "stackSize": 1,
      "objectData": {
        "oreName": "ingotNickel",
        "stackSize": 1
      }
    },
    "energyValue": {
      "value": 256.0
    }
  }

**Comment by pahimar** [comment]
You can also use the commands in game, just use /ee3 set-energy-value. Use the post option

**Comment by squirrelkiller** [comment]
That seems to keep disappearing each time I reopen the world. I kind have gave up on that. I have a theory that the EMC values are being wiped by the dynamic EMC calculation at the start, removing custom additions.

**Comment by pahimar** [comment]
I have my own theory and it's not that. DynEMC is set to run only when mods change by default, otherwise it attempts to load the saved values from file. A temp fix right now is to change the EE3 config from 'When Mods Chnage' to 'Always'

**Comment by squirrelkiller** [comment]
My theory to the reason for all these issues is DynEMC is a brilliant idea and as a result it will never work how its intended the first time because reasons. But so long as there are fixes that makes it all better.

**Comment by Parker8283** [comment]
I think EE3 should handle the common oredict stuff between mods, like copper, tin, etc, stuff that's found in a lot of mods. If a mod dev wants to change it, they can set their own energy value for their specific whatever. But I think it makes for less of a headache for mod devs if EE3 handles the common mod oredict stuff.

But that's just me.
