### ISSUE TITLE
Curse - outdated version of EE3

### ISSUE THREAD

**Issue by leSamo** [pahimar/Equivalent-Exchange-3#841]
There is a really old version of EE3 on curse. You should update it or delete it. It might cause some issues with Curse Voice. Thanks.

**Comment by pahimar** [comment]
That's because you are downloading the last Release build of EE3, which was for Minecraft 1.5. It clearly even says what version of Minecraft it's for.

You should always grab the latest, highest promoted version for the current version of Minecraft you are playing.

**Comment by leSamo** [comment]
Curse launcher thinks it's for MC 1.7.10.

**Comment by pahimar** [comment]
Then thats an issue with the Curse launcher and not with EE3

**Comment by leSamo** [comment]
Yep, sorry than.
