### ISSUE TITLE
Can't seem to insert custom EMC values

### ISSUE THREAD

**Issue by cibastian** [pahimar/Equivalent-Exchange-3#842]
Hi, so when I try to use the command to set a certain emc value to copper ingot for example if I use the post method it assigns it but the value gets forgotten after I quit and re-enter the client (playing in a single player world), and when I use the pre method it doesn't remember it at all. 
I'm using forge 10.13.3.1401 and EE3 version 0.3.505 (latest at the time of this post)

**Comment by Yellbana** [comment]
Use the pre method and in the config change the regenerateEnergyValuesWhen setting to Always

**Comment by THEminer72** [comment]
How do you use the post method?

**Comment by IntelliSun** [comment]
Current workaround discussed on #944, issue discussion on #952 and #953.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
