### ISSUE TITLE
[Suggestion] Pulling items out of tranmutation tablet

### ISSUE THREAD

**Issue by bsaksida** [pahimar/Equivalent-Exchange-3#843]
Because of AE2, i am used with shift-Click to get a single stack of items. But instead i get Filled inventory with items. I suggest that shift-click will get single stack, while Shift+Ctrl click to do pull out and fill full inventory

**Comment by WolfAmaril** [comment]
That's just an AE thing, designed to keep the default shift-click functionality of "pull as many as possible" from flooding your inventory and world with a couple million cobble.

I wouldn't count on it being changed.

**Comment by Unknown-88** [comment]
A way to only remove a single stack at a time would be very nice, as clicking 64 times for a stack of items takes a bit

**Comment by ClarSco** [comment]
You could always fill the others slots with other items, ie. if you have 5 empty slots split one of the filled slots between 4 of the slots (1 item per slot is all that is required). Then when you Shift+Click, only the empty slot will get filled.

**Comment by IntelliSun** [comment]
If feasible I may enable such behavior through a config option, but I'll wait for @pahimar input on that.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
