### ISSUE TITLE
not a bug, suggestion/hopefull addition.

### ISSUE THREAD

**Issue by reapersremorse** [pahimar/Equivalent-Exchange-3#844]
hello pahimar
could you add a feature where the mod prints an ee3-emc.cfg ??

you could have it print every registered item and block in the game with the emc value beside it
if there is no emc value you could make it print zero
ex:
minecraft
   minecraft:stick=4
tinkersconstruct
   tinkers'construct:blankpattern=0
   (i manually added the blank patter to be 6 emc)

i dont know the way they would actually be printed but this would be cool, if you could add this then it would be much easier to add and change recipes when making packs and such. playing with over 100 mods kinda makes it hard to add a lot of values ingame. 

ee3 version on curse use is the latest at this moment
   EquivalentExchange3-1.7.10-0.3.505.jar (5/8/2015)

**Comment by pahimar** [comment]
It already does this. Look at the energy-values.json.gz file in data/ee3/energyvaluez

**Comment by reapersremorse** [comment]
Thats in the saves/world/data/ee3 folder.
Will this file be used for every world or just the world that its edited
in??
(Because its in that worlds folder)

I figured that if there was a config file in the config folder then the
whole instance itself could use the values. But i may be wrong about the
per workd thing.

**Comment by reapersremorse** [comment]
I also do not see the items and blocks without emc values in this file.

There are also see items and blocks in this cfg that say they have emc
balues but dont ingame.

Ex: Milk bucket in th config says 0.064

In game it says 0

**Comment by pahimar** [comment]
Items without values do not appear in the file. That's the point of a list of things that have values; if it doesn't have a value then it's not in the list.

MILK (the fluid) has an EMC value of 0.064 per 1mb. Therefore 1000mb of Milk would have an EMC value of 64. It's important to read what the TYPE of the object is.

As for why something doesn't have a value in game, that's likely something overriding/replacing the object. You can always set your own values in game with the /ee3 set-energy-value command.

**Comment by pahimar** [comment]
And to your earlier question, it's saved per INSTANCE. If you were to change save files, you would get a different EMC value setup (potentially, if you changed values in one of them, etc).

**Comment by reapersremorse** [comment]
with the milk bucket, there is no value for buckets in game and i understand that now,

if you set the file to print blocks and items with emc as well as the files without emc (ones without would value 0) then people would have an easier time setting values out of game.

by instance do you mean minecraft instance? which would mean i could use set values in other worlds. or did you mean each save instance because you said "its saved per instance" then followed by saying "if you were to change save (to me a save would be a world file save) files, you would get a different emc value setup."

if values are per save file then that would mean i could not make a pack and let people play it without using a world that i personally create and add values to that world.

i am in the process of building a hardcore questing mode map using ee3, you get the new ingots and such via completing quests (kinda like old ftb complete the monument but with hqm and ee3) you start in the void with just a piece of bedrock and items in your inventory, the difficulty decides what items and what amount of items will be in your inventory when you spawn

i appreciate all the work your doing on the mod and dont want to be a bother or aggravate you, im good at doing so without knowing so sorry if I'm getting annoying.
