### ISSUE TITLE
Chalk Stop Working

### ISSUE THREAD

**Issue by MokahTGS** [pahimar/Equivalent-Exchange-3#845]
So the chalk has stopped working and I'm not able to draw the symbol on the ash infused stone to make the transmutation tablet. Any idea why? It started when I pressed V to toggle the size...the symbol disappeared and now I can't get it to appear at all.

https://dl.dropboxusercontent.com/u/9882100/Minecraft/2015-05-09_12.15.21.png

**Comment by pahimar** [comment]
Hit Shift+V to make the size decrease

**Comment by MokahTGS** [comment]
Thank you.  I'm assuming that this will all be detailed in a book of instruction some day.  Great work on this BTW.

**Comment by Jinteiplays** [comment]
shift+v is not decreasing the size for me in the latest version. additionally I tried rebinding the keys to remove any possible conflicts there. but this also did not change the result.

any tips?

**Comment by MokahTGS** [comment]
This is still an issue...some how the chalk size gets stuck.  I've open a new issue.
