### ISSUE TITLE
[Suggestion]  Shift + Mouse Over Item = You Have Reserached This Item

### ISSUE THREAD

**Issue by MokahTGS** [pahimar/Equivalent-Exchange-3#847]
I was wondering if you could add the functionality of the Tome to any item in any container instead of just mousing over items in the research table.  It would be useful for finding items I haven't researched.

**Comment by pahimar** [comment]
Added in https://github.com/pahimar/Equivalent-Exchange-3/commit/15180e406b561528b8e09628af6f0112d2a21be2
