### ISSUE TITLE
ore gravel can still be learnt and contains the same EMC as the ore equivalent

### ISSUE THREAD

**Issue by kurokuno** [pahimar/Equivalent-Exchange-3#849]
resulting in a dupe bug with any ingot doubler

already flagged it for personal use but just felt this might be one that should be known

**Comment by pahimar** [comment]
What "ore gravel"?

**Comment by krzys-h** [comment]
Probably the one from Tinkers Construct

**Comment by pahimar** [comment]
Ah wasn't sure if it was that, or the ore gravels from Ex Nihilio

**Comment by WolfAmaril** [comment]
I'd think for completeness sake, cover both. If one is doing it the other probably is as well.

**Comment by reapersremorse** [comment]
for personal play, if you do not like people being able to learn something
you can use the command
/ee3 set-item-not-learnable (item) (data) 
renders the item or blocks unable to be learned by anyone on server or world/lan

**Comment by pahimar** [comment]
I only add ores to the player knowledge blacklist that are registered in the OreDictionary with a name that starts with 'ore' (https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/init/Abilities.java#L13-L18)

Other items can be added to this blacklist with the commands listed above, manually editing the player knowledge blacklist json file, or by having mod authors use my API to register what should not be learnable.
