### ISSUE TITLE
Set-energy-value-current-item <post> not working or incorrect usage

### ISSUE THREAD

**Issue by Unknown-88** [pahimar/Equivalent-Exchange-3#850]
I would like to add emc to certain items on the server, used /Set-energy-value-current-item post XXX, restarted server, and all values had been reset? Am I using this wrong, or is there a bug? I have not tested with pre instead of post.

**Comment by JadeDrgn** [comment]
Set the energy value regen entry in the config file to Never, that'll prevent it from resetting.

**Comment by Unknown-88** [comment]
Thanks, that fixed it, still not sure what pre/post is but this works.
