### ISSUE TITLE
Render issue at Transmutation Table

### ISSUE THREAD

**Issue by EwyBoy** [pahimar/Equivalent-Exchange-3#852]
When placing slabs around the top around the Transmutation Table it is not rendering properly at 1 of the sides. Note this rendering bug is only happening at 1 of the sides of the Transmutation table. Hard to describe who it is but you can test it yourself. Here is a series of picture showing how it is not rendering the sides properly at one of the corners.

http://imgur.com/a/bj1ha

Hope this help!

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992

**Comment by pahimar** [comment]
Won't be resolving this issue in MC 1.7.10. The new rendering in MC 1.9.* should resolve this issue in the future :)

**Comment by EwyBoy** [comment]
Okey, nice :dancers:
