### ISSUE TITLE
Energy Values not calculating correctly

### ISSUE THREAD

**Issue by Yellbana** [pahimar/Equivalent-Exchange-3#853]
The energy values for wooden items are not being calculated. This includes the vanilla crafting table. Can I assume this is another mod not declaring OreDictionary registers correctly?

Also after adding values for all of the copper and tin ingots, recipes using them are not being calculated either. I have the config set to regenerate Energy Values always.

**Comment by Wulfson** [comment]
The wood thing is probably the same Extra Utilities issue that's been discussed in numerous other issues, such as #828

**Comment by Yellbana** [comment]
Extra Utilities is not installed. Are there other mods that have the same issues with OreDict?

**Comment by WolfAmaril** [comment]
Could Chisel be doing it?

**Comment by Yellbana** [comment]
The recipes with cobble are working so I assume not

**Comment by Yellbana** [comment]
Actually it looks like any recipe crafted with an ore dictionary item is not having a value calculated

**Comment by LouisHutch** [comment]
Believe the wood issue is caused by Forestry

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
