### ISSUE TITLE
Transmutation Tablet

### ISSUE THREAD

**Issue by GrimPod** [pahimar/Equivalent-Exchange-3#855]
Currently using 0.0.8 ME^-1 server, Trying to use the Transmutation tablet as seen in direwolfs spotlight, Doesn't seem to be working, Tried putting Minium Stone/sanguine Star in the middle as direwolf said that might be a new thing in the mod, But just cant seem to pull anything out of the tablet.
If i put items into it, it shows me the EMC Value in the bottom left but cant seem to do much else.

**Comment by WolfAmaril** [comment]
1) Did you watch all of DW20 spotlight?
2) Do you have a tome of alchemical knowledge?
3) Does it actually have knowledge in it?
4) Is it in the transmutation tablet?

**Comment by GrimPod** [comment]
Yes
Yes
Yes
Yes

**Comment by GrimPod** [comment]
Tried the exact same thing as DW20 but the item just wont make when i click on it on the right of the tablet to make it

**Comment by Staegrin** [comment]
Works for me. Is there material on the left that you want to turn into something (example: cobble)

**Comment by GrimPod** [comment]
"But just cant seem to pull anything out of the tablet. If i put items into it, it shows me the EMC Value in the bottom left but cant seem to do much else."
I said that in the first post, i can put items into the left slots but i just cant pull anything out of the right, i see the items there on the right but if i click them nothing happens

**Comment by GrimPod** [comment]
What version of the modpack were you playing?

**Comment by GrimPod** [comment]
ok updated to 0.1.0 and tried on single player and it worked, so im not sure why it didnt work, now just to see if theres a way to set the server up for 0.1.0

**Comment by pahimar** [comment]
What are you talking about that is version 0.1.0?

**Comment by Parker8283** [comment]
The pack version 0.1.0
