### ISSUE TITLE
Custom EMC values not saving across reboots

### ISSUE THREAD

**Issue by Deefster10k** [pahimar/Equivalent-Exchange-3#856]
When the game is rebooted, heck, when the world is reloaded, any custom emc values I've set disappear, which leads me to think that they aren't actually saving to the file. I've only actually used it for the carpenters blocks - cause it saves me so much time, and I make sure it's balanced, though considering it's just sticks and planks, I would've originally thought that they would've been calculated by the DynEMC system, but you've had enough issues about the problems with DynEMC I figure you have enough to deal with there. Anyways, as the issue title suggests, when I reload the world up, those values are gone, which can make it a pain to have to reset them each time.

**Comment by Deefster10k** [comment]
Ok, it's been fine on my most recent load, but it may happen again on the next one, I'll update here when I do that. And it having happened at all would still be a bug, would it not?

**Comment by Unknown-88** [comment]
There is a value in the configs regarding regening emc values, you need to set it to never I believe, not sure what the point of regening them is.

**Comment by CatDany** [comment]
@Unknown-88 Regen-ing in DynEMC means reanalyzing all the recipes. For example, a mod was added recently, and it has a new item. If you say "Never regen EMC", it won't set an EMC value for it, when it could, just by looking at its recipe. That's how it works AFAIK.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
