### ISSUE TITLE
Fire Charge

### ISSUE THREAD

**Issue by skint101** [pahimar/Equivalent-Exchange-3#857]
1x Gunpowder + 1x Blaze Powder + 1x Coal make 3x Fire Charge with almost 1 Million EMC combined

MC 1.7.10
EquivalentExchange3-1.7.10-0.3.501

**Comment by iTitus** [comment]
Can you provide a screenshot? Maybe you misread the tooltip ;)

**Comment by skint101** [comment]
![ee3_charge](https://cloud.githubusercontent.com/assets/12442335/7639558/3a5a8b54-fa7d-11e4-898f-6a5119f66329.jpg)

**Comment by skint101** [comment]
![ee3_charge2](https://cloud.githubusercontent.com/assets/12442335/7639588/78a63a84-fa7d-11e4-9340-6da109e25b7f.jpg)

**Comment by skint101** [comment]
![ee3_charge3](https://cloud.githubusercontent.com/assets/12442335/7639615/9ebea3f0-fa7d-11e4-8f40-91f0eb854df1.jpg)

**Comment by WolfAmaril** [comment]
Yeah, that's a decimal, not a comma.

it's about 330 each

**Comment by skint101** [comment]
oh, nevermind then :)
