### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by leSamo** [pahimar/Equivalent-Exchange-3#858]
I was doing some screenshots for EE3 wiki and I got a crash when I opened my Tome of Alchemical Knowledge.
http://pastebin.com/NzSML5qs

**Comment by WolfAmaril** [comment]
There is nothing in that crash log that points directly at EE3 as the casue.

Does this same crash happen every time you open the ToAK or just that time?
If every time: What version of EE3 are you using?

**Comment by leSamo** [comment]
It happened only once and not the first time I openned it. Latest version.

**Comment by WolfAmaril** [comment]
Most likely cause: Minecraft being kind of stupid with memory handling.

nothing Pahimar can do for you there.

**Comment by leSamo** [comment]
Oh well
