### ISSUE TITLE
[Suggestion] Aludel remove recipe API

### ISSUE THREAD

**Issue by Nincodedo** [pahimar/Equivalent-Exchange-3#861]
Would it be possible to include a remove recipe method in the AludelRecipeProxy?

**Comment by pahimar** [comment]
Can you explain the use case?

**Comment by Nincodedo** [comment]
I'm trying to place EE3 later in my modpack's progression. I figured the easiest way to do that would be to make the Tome of Knowledge recipe much later. Currently my idea is to use Thaumcraft's infusion crafting however I don't want to remove the Aludel all together, but just the Tome of Knowledge's recipe from it.

**Comment by pahimar** [comment]
In the Minecraft 1.9 version of the mod I will make sure that custom recipes that my "machines" use will have API points to add and remove recipes.

**Comment by Nincodedo** [comment]
Greatly appreciated. Thank you!
