### ISSUE TITLE
Transitive dependency on Waila 1.5.6 causing problems when including

### ISSUE THREAD

**Issue by cpw** [pahimar/Equivalent-Exchange-3#864]
Hey dude, you have a compile time dependency on Waila. It shouldn't be transitive (it means EE3 is declared as dependent on Waila at all times, whereas Waila probably doesn't need to exist for EE3 to work, it is strictly for compilation of EE3).
Example for removing the transitivity of a compile dependency here:
https://discuss.gradle.org/t/how-to-exclude-transitive-dependency/2119/2

Also, pinging @AbrarSyed since he should probably verify this. 

At present, this is breaking integration of EMC into AE2 since they also have a *conflicting* dependency on Waila (pinging @fireball1725), also pinging @profmobius just because.

**Comment by pahimar** [comment]
Resolved some time ago in a commit I can't remember :-p
