### ISSUE TITLE
chalk circle issue

### ISSUE THREAD

**Issue by elderpokey** [pahimar/Equivalent-Exchange-3#865]
found a bug when going through the circles, it gets stuck on the two largest circles and will not go back to the 3x3 or the 1x1
version:equivalentexchange3-1.7.10-0.3.505.jar

**Comment by pahimar** [comment]
Use Shift+V to reduce the size of the circle.

**Comment by elderpokey** [comment]
ok i forgot i changed the keybinding to numberpad7 and it didnt work. but a
default it works, sorry for the durp and thank you for the help
