### ISSUE TITLE
[Bug] Accidental Duplication for ee3 1.7.10-0.3.0.505

### ISSUE THREAD

**Issue by LucatusDavitus** [pahimar/Equivalent-Exchange-3#866]
In a transmutation tablet, when clicking a number key while hovering over one of the items to transmute another item into, it will place it into the corresponding hotbar slot, without consuming exchange energy.

**Comment by SargonRose** [comment]
Confirmed. Was able to reproduce on mine as well.

**Comment by nhdadmin** [comment]
Confirmed to still be present in 0.3.507.

**Comment by pahimar** [comment]
Fixed with #904
