### ISSUE TITLE
Balance.

### ISSUE THREAD

**Issue by SargonRose** [pahimar/Equivalent-Exchange-3#867]
Glow stone and soul sand may need to have there emc values lowered.

After one trip to the nether you can create stacks of diamond from just 2-3 veins of glow stone.

**Comment by Unknown-88** [comment]
Lets say an averg vein is 20 blocks, and you average 3.5 dust per block, that means 70 glowstone per vein * 3 veins = 210 glowstone. 210*384 = 80640 EMC, or 9.8 diamonds. I agree this might be a bit too much, although its hard to automate glowstone mining

**Comment by SargonRose** [comment]
True, I was just going by i was able to get 30 diamonds after one trip. 

Balance is a hard issue. If it means anything i have since made 8 trips to the nether get more. It inst a amazingly renewable item because you start having to go further and further.

It did give a fairly high jump in power early game though. It felt like i was able to skip quite a few steps that other mods have and go straight to diamonds

**Comment by KlutzLament** [comment]
Maybe if transmutation wasn't instantaneous it would even things out a bit.

**Comment by WolfAmaril** [comment]
I'd say that one of the largest balancing factors of EE3 is that you have to have already obtained one of the thing you want to make using the standard method.

That said, making transmutation non-instantaneous would defeat the whole purpose of EE3.

**Comment by Nincodedo** [comment]
I'm pretty sure you can lower the values yourself if you're an OP. You can use /ee3 set-energy-value-current-item to set the energy of an item in your hand.

**Comment by SargonRose** [comment]
Having played quite a bit more. IRON and GLOWSTONE have bcome the trading economy of my server. XD

**Comment by tekacs** [comment]
Perhaps bear in mind that lowering Glowstone's EMC will in turn make it much easier to get Glowstone. :P
Glowstone is used as a moderating/hard-to-get item in other mods due to its in-world scarcity, is it not?

**Comment by laz2727** [comment]
Usually not. I don't remember any recipes that require glowstone as a gate,
except for energetic alloy, and it's mid tier.

**Comment by tekacs** [comment]
I was thinking Lumium from Thermal Expansion and Glowstone Ingots from Mekanism but sure.

Either way I think the reason they're set so high is just the basic rule of rarity in the world - perhaps Glowstone is 'easier' to harvest because it's out in the open, but equally it's not that easy to harvest without flight.

**Comment by pahimar** [comment]
If you would like values to be lower you can do that by setting a custom energy value on the items
