### ISSUE TITLE
Tome is forgetting recipes

### ISSUE THREAD

**Issue by Harelex** [pahimar/Equivalent-Exchange-3#872]
I just put EE3 in a server, playing with some friends. Everything is working fine, but I don't know why or how or w/e, but sometimes the Tome of Alchemical Knowledge is forgetting every one and single item I've let it learn, and it's being a pain :(

**Comment by pahimar** [comment]
1) when reporting bugs attach the fml log
2) update to ee3 0.3.504

**Comment by pahimar** [comment]
0.3.505

**Comment by RoloEdits** [comment]
I Am Also Experiencing Tome Knowledge Loss And I Am Running  0.3.505, It Happened After My Client Crashed In Single Player Mode And I Am Also Having An issue With My Post Assigned Energy Vales Loading With My World. A Work Around For Now Is Moving The File To My Desktop And Then Back When The Minecraft Screen Says "Loading World". I Don't Know If These Are Connected So I Just Presented Them Both. This Is My First Time Reporting An Issue So I Dont Know What FML Log I Should Post.

**Comment by RoloEdits** [comment]
And Also In An Attempt To Require My Knowledge I Executed "/ee3 template-learn-everything" And It Did Not Work, I'm Not Sure If I'm Doing It Wrong Or If This Hasn't Been Implemented Yet Given The "template" At The Beginning.

**Comment by pahimar** [comment]
@RoloEdits the "template" is used to give players a starting set of knowledge when they first get into a world/server for the very first time. Teaching the template anything after you have already gotten in does nothing for you.

@Harelex can you confirm that an update solved your issue?

**Comment by RoloEdits** [comment]
OK I Understand Know Thank You For Clearing That Part Up. By The Way I Love This Mod, Easily My Favorite Mod.

**Comment by chippydip** [comment]
I just ran into this issue (using version 0.3.507).

I rolled a couple of single player maps last night before settling on one to play. I taught a bunch of stuff to my tome before calling it a night. When I came back today to continue my game, the Tome was empty.

After digging around in the saves a little, it looks like my Tome data was saved to the wrong place. The map I finally settled on was called "Solo #5" which had this in the json file:
{
    "knownTransmutations": []
}

In my "Solo #4" folder (the second to last map I loaded) I found an ee3 file that looks like it has all the right known transmuatations. I had deleted this map in game before rolling the final map, but apparently EE3 didn't get the memo (the only two files in this directory are EE3-related: my saved transmutations and the template.json file).

Exiting to the main menu and copying the file into the correct directory didn't work (the file was just reset to being empty) but closing the game completely before copying seems to have fixed the issue.

**Comment by stahscream** [comment]
Having this issue right now in Daybreaker on my server. I'm going to do a fresh install and just copy over my world, for troubleshooting sake.

But yeah, I'll teach the tome something, and if I exit the game and go back into the world, it says there are no recipes.  I'm surprised there aren't more people having  (or acknowledging) this issue?

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
