### ISSUE TITLE
Help doesn't work with /ee3 command

### ISSUE THREAD

**Issue by HellishINC** [pahimar/Equivalent-Exchange-3#877]
Currently I am unable to access any /ee3 commands. Trying to simply does nothing. No console output, no chat output. Cannot add custom values aside from manually editing the json though that is a relative pain.

Tried using latest Forge 13.3.1408 as well as 13.3.1388 with EE3 Build 505 and 501. SSP world no other mods.

Example video (please note it is loud): https://www.youtube.com/watch?v=KgRVlkroU_I

I should also point out that at one point (it only happened twice and haven't seen it since) I did receive an error with /help after trying /ee3 which was something along the lines of "An unknown internal error has occurred."

**Comment by bsaksida** [comment]
Its a issue with help command.

Type /ee3 , and then press space bar. After that press tab key. Keep pressing and it will cycle throuh commands

**Comment by HellishINC** [comment]
Thanks for the work around, I'll give it a try and edit this post.

**Comment by pahimar** [comment]
Without restructuring how ee3 does its commands, I don't think I can support this. For now please use the tab completion options to find out more about the commands
