### ISSUE TITLE
Adding EE3 to Ethos pack causes an error

### ISSUE THREAD

**Issue by CameronMurray11** [pahimar/Equivalent-Exchange-3#878]
here is what comes up and im new to modded minecraft so im not sure what to do and this only occured when i added ee3:

Forge Mod Loader has found a problem with your minecrfat installation
The mods and versions listed below could not be found
Forge: minimum version required is 10.13.3
The file 'ForgeModLoader-client-0.log' contains more information

where do i find this version? so my minecraft will work

**Comment by pahimar** [comment]
Ipdate your Forge

**Comment by pahimar** [comment]
*update

**Comment by CameronMurray11** [comment]
wherer do i download a more updated version of forge multipart?

**Comment by pahimar** [comment]
Update MinecraftForge not ForgeMultipart

Go to files.minecraftforge.net

I will not help you install forge. Loads of tutorials out there for that
