### ISSUE TITLE
EE3 crashing client

### ISSUE THREAD

**Issue by HeroUltraOmega** [pahimar/Equivalent-Exchange-3#879]
With EE3 by itself, it's just fine, but with the other mass amounts of mods I have installed on curse launcher, the minecraft client crashes upon loading the game with it. Without EE3, it's just fine. I think there may be a conflict with one or two of the mods with EE3, but I wouldn't know what.
The only report I have is from Launcher log and game output from the minecraft launcher.
Game Output:
http://pastebin.com/gqqYw84f
Launcher Log:
http://pastebin.com/JcfSL9cD

**Comment by SquidDev** [comment]
Update PneumaticCraft.

**Comment by HeroUltraOmega** [comment]
Probably should have made sure all my mods were up to date before sending an issue.
My bad, and thanks for the help
