### ISSUE TITLE
Shift-Click + Full Inventory = Crash

### ISSUE THREAD

**Issue by SteGr** [pahimar/Equivalent-Exchange-3#880]
If you shift-click something out of the transmutation table and you have a full inventory it will crash.

Crash-Report: http://pastebin.com/3cBrFHT2

**Comment by Rictas** [comment]
This does not only happen if you have an full inventory. I guess it also happens if your are able to transmute more items than your inventory can hold.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
