### ISSUE TITLE
Change path in build.gradle

### ISSUE THREAD

**Issue by FireBall1725** [pahimar/Equivalent-Exchange-3#883]
This section of code in your build.gradle will copy the chicken bones mods to ./run/mods.  The path should be changed to ./eclipse/mods since EE3 doesn't change the name of the run folder (like AE2 does).

```
task copyChicken(type: Copy, dependsOn: "extractUserDev") {
    from { configurations.compile }
    include "**/*Chicken*.jar", "**/*NotEnoughItems*.jar"
    exclude "**/CodeChickenLib*" // because CCC downloads it anyways.. -_-
    into file("./run/mods") // paralell to the assets dir
    mustRunAfter "deobfBinJar"
    mustRunAfter "repackMinecraft"
}
```

**Comment by FireBall1725** [comment]
If you wanted to change the run directory, personally i don't like the eclipse folder name for the run directory you can add this code to your build.gradle

```
minecraft {

    ... other code here ...

    runDir = "run"
}
```

**Comment by pahimar** [comment]
The task is removed in a yet to be commit set of changes, so closing
