### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Aubron** [pahimar/Equivalent-Exchange-3#885]
This was mentioned in #835, but is a new issue altogether

Expected Results: Broken chest, broken dreams.

Results: Item duplication up to a stack at a time.

Method:
1. Acquire an alchemical chest, a friend (or autonomous activator) and 2 of the items you need to duplicate.
2. Place chest, insert 1 of the to be duplicated item.
3. Get the friend (or activator friend) to break the chest while you have the chest's GUI open.
4. Scroll wheel the item into your inventory from the chest, it will gain an increasing large negative EMC value, and the stack in your inventory will increase until it maxes the stack.
5. For extra laughs, manually move the negative EMC item to your inventory, it will become a version of the item with 0 EMC when the gui is closed.

**Comment by nhdadmin** [comment]
Tried to replicate this error in build 507, the item in the chest dropped to zero, did not go into negatives, so kinda almost fixed?

**Comment by Aubron** [comment]
To confirm, and since I don't want to set up a manual test environment again, it still duplicates the item though, correct?

**Comment by nhdadmin** [comment]
Correct, testing with the new version from the repo to see if it still exists

**Comment by Aubron** [comment]
Confirmed fixed via Virtuoel PR
