### ISSUE TITLE
Issue With Chisel

### ISSUE THREAD

**Issue by WolfAmaril** [pahimar/Equivalent-Exchange-3#887]
This may be a duplicate and I just didn't catch it.

That said, with chisel installed, any vanilla blocks that can be chiseled lose their EMC values, and the EMC values for the "base" chisel block are not calculated.

**Comment by Landrash** [comment]
I'm farily certain this is the same problem as #888 . Since the "base" block can be crafted trough a mechanism that EE is not familiar with it doesnt give the "base" block a EMC value.

It migth be a good idea to report it as a bug to the chisel project and have them integrate EE3 support. =)

**Comment by WolfAmaril** [comment]
Just a small quibble, wouldn't that make theirs a duplicate of mine?

Will now go tell Chisel about it.

**Comment by Landrash** [comment]
Yes ofc.
Sorry for the misunderstanding, English is my second language :-)

**Comment by WolfAmaril** [comment]
No problem.

**Comment by pahimar** [comment]
This is best handled by Chisel devs adding EE3 support to Chisel :)
