### ISSUE TITLE
Adding global Exchange Energy values?

### ISSUE THREAD

**Issue by Gideonseymour** [pahimar/Equivalent-Exchange-3#897]
I'll preface this by saying that I know that Exchange Energy is global - but my concern is that the custom exchange energy values (added via the commands, for example) are not. Is there any way currently (or a way planned in the future) to add values globally, instead of per world?

**Comment by CatDany** [comment]
Define "global". If you mean global for modpack, you can work around it for now: copy and paste /world/data/ee3/energy-values and /world/data/ee3/abilities from one world to another.

**Comment by Gideonseymour** [comment]
Yeah, I know that. It just isn't ideal for a modpack in which I kind of expect people to generate their own worlds :P

**Comment by pahimar** [comment]
It's on the list of things being worked on. However you could be a little more specific in what you mean by "global" in your initial issue post.

And for clarity, the values are stored per instance, not per world (Overworld is a world, Nether is a world, etc)

**Comment by CatDany** [comment]
@pahimar Oh, right. I call them worlds just because their "fancy (localized) name" is world, but I know that they called "world" in code...

**Comment by Gideonseymour** [comment]
Yeah, sorry for the confusion. Generally from a pack developers perspective, worlds are referred to as dimensions. Should have used "saves" to prevent confusion, though.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
