### ISSUE TITLE
abilities.json keeps being regenerated

### ISSUE THREAD

**Issue by CatDany** [pahimar/Equivalent-Exchange-3#898]
So, I added new unlearnables and unrecoverables. Some of them are added internally using commands, some of them I've done myself, just by copypasting JSON clusters and changing the IDs.

Sometimes when I relog into my world (modlist didn't change), file resets to default (only ores are unlearnable), which is weird and annoying. I need to go and grab the last one from backups :angry: 

What can cause this theoretically? I can provide the log or my "abilities" JSON, maybe the formatting is wrong or something.

**Comment by MrPotatoGaming** [comment]
Did you change the string-value in the config file that is labeled "S:energyvalues.regenerateEnergyValuesWhen="? Change this value, and you shouldn't have a problem.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #991
