### ISSUE TITLE
EMC values not saving

### ISSUE THREAD

**Issue by IeuanK** [pahimar/Equivalent-Exchange-3#900]
After setting values with `/ee3 set-energy-value-current-item <pre|post> <value>` and restarting the server some values are reset. `/ee3 sync-energy-values` does not seem to have any effect.

Can be reproduced by setting values then restarting the server (possibly reloading SSP world).

Changing values in the json file then restarting keeps those values meaning it is not saving the values to disk when you set them using the commands.

Is this intended (in that case, some way to force it to save)?

**Comment by GeoTerra** [comment]
It should be noted that this issue was discussed in #856. It comes back to an issue where the EE3 configs are set by default to regen EMC values on world load, meaning that any custom values are lost.

**Comment by pahimar** [comment]
Biting back frustration that no one reads code or what the config comments say, but by default EE3 will regen values WHEN MODS CHANGE. Custom values should save but are not. Its a known issue. The workaround is set ee3 to regen Always

**Comment by porteriscool** [comment]
Does the regen feature work pahimar because within the config file it states:

    # When to regenerate EnergyValues. Options are "When Mods Change" (when mods are added, removed, or updated) or "Never" (only generate the first time). [default: When Mods Change]
    S:energyvalues.regenerateEnergyValuesWhen=When Mods Change

Will the workaround to set the EE3 file to regen Always work even though it's not mentioned?

**Comment by pahimar** [comment]
Yes. The documentation is out of date from the current code in github

**Comment by porteriscool** [comment]
Okay thank you.

**Comment by ron7s** [comment]
I have the same problem, I try to set basic values so the calculation will work even that I have so many mods, I try to add chest for example, with the command, and from the .json but its still not working, its not work in my private server, and not in the single player, I don't know what the problem
I tried set the regen to Always and it still not working.
you have any suggestions for me
and sorry about my bad english.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
