### ISSUE TITLE
Crash when spam clicking items in transmutation table

### ISSUE THREAD

**Issue by utoc** [pahimar/Equivalent-Exchange-3#901]
Greetings

Crashlog here:  http://pastebin.com/9nHHL5Cr

Modlist here: https://www.reddit.com/r/BBQSauce/comments/32wr8o/bbqsauce_server_and_client_modlist/

User was spam clicking in the transmutation table converting diamonds into grass blocks.  Have a nice day!

**Comment by dogamusprime** [comment]
Same issue, except crash came upon shift-click. 

Mod pack is infinity with "ex-nihilo","Morph" and "iguanatweaks for tinkers". That's sooo much crap. I'm not even sure you could even help. 

http://pastebin.com/YsUy43JF crash report.

Also, the dynamic emc system doesn't appear to be working. Most items have no emc value at all. This includes vanilla things like wool and pistons. If it's a core item that isn't made of other items it works fine. Once again, it's a great deal of crap so I'm amazed it works at all.

**Comment by SelBast** [comment]
The shift-clicking crash i can confirm to be happening and concerning the dynEMC system the oreDict breaks it most of the time, that is known and pahimar tries his best to fix that

**Comment by utoc** [comment]
Server crash appears to happen when there are 28 inventory slots open.  Client crash when there are 29+ slots open.  There appears to be no crash when the user has 27 or fewer slots open.  I closed the extra issue I opened and am consolidating the issues to one thread.

Here is a crashlog from a server http://pastebin.com/SJt918w1

**Comment by LemADEC** [comment]
Any workaround configuration to prevent the crash until we get a proper fix?

**Comment by utoc** [comment]
Tell your users to make sure they never have more than 27 inventory slots open.  Thats about all you can do.

**Comment by LemADEC** [comment]
I've increased server side callstack for now, at least it'll only crash on client side for now.

**Comment by IntelliSun** [comment]
Fixed with 2230f58a435043d5b5f9f846303655114ae03c42

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
