### ISSUE TITLE
A possible implementation

### ISSUE THREAD

**Issue by BLSK** [pahimar/Equivalent-Exchange-3#903]
Ay pahimar,

I would like to ask if we could have a special optional aspect to EE3.
I was hoping by default(false) we could have an option 'requires catalyst to operate' for emc using devices.
The next one asks(String) 'catalyst required is' (Modid:itemname:meta maybe nbt too?) however the requested item was required.  A gui having an extra slot would be enabled if set to true would maybe even show the item when hovering over it.  The item wouldn't be used but allows such devices to work.

Reasoning is I am currently using ProjectE as I can balance it out some for the modpack I have constructed and I think EE3 right now actually crashes if I recall...I will look at that once I have a few more minutes in a few days.  I hope you may consider the request as I can see a fair few uses for it...heck maybe even have an optional default(false) for 'uses catalyst on operation'

Just thought I would ask in either case.  I like how things are looking in it XD

**Comment by pahimar** [comment]
For one the mod doesn't crash now.
For two, wat

**Comment by dragontox** [comment]
After a long time studying this form of communication I think I may be able to get the message out of it. I think he would like an option that would make it so any emc devices(currently just the transmutationtablet) would require a special item to be able to function and he says he would like to be able to set the item in the configs.

**Comment by BLSK** [comment]
It did crash on me... maybe a newer build after the one I grabbed came out.  I'll go look for it but um...
Thought I wrote decently XD.  Guess I may not of.  I hadn't had much time to look here but yes... Dragontox seems to have deciphered it.  What I mean is:
Here's a visual representation of what I mean:
![687474703a2f2f692e696d6775722e636f6d2f7377336d48634e2e706e67](https://cloud.githubusercontent.com/assets/8443396/8022021/048c92ee-0c87-11e5-967f-3ea618f595ca.png)

**Comment by ClarSco** [comment]
By crashing, do you actually mean the bug where you sometimes have to reinsert the book to refresh the list of items? If so, https://github.com/pahimar/Equivalent-Exchange-3/issues/914.

**Comment by BLSK** [comment]
No ClarSco,  That would be totally Irrelevant to what I was talking about.  LOL its only been 13 days since I started this....felt like it has been months XD.  I had an actual crash not a GUI bug.

**Comment by pahimar** [comment]
Not really something I see as happening with the transmutation system, sorry
