### ISSUE TITLE
EMC Wierdness

### ISSUE THREAD

**Issue by Thiana** [pahimar/Equivalent-Exchange-3#905]
A diamond pick should have an emc of 24,584 but DynEMC shows it at no emc.

Diamonds are 8192 (oreDic gemDiamond(1 entry, 8192emc); MainInfusionMaterial(3 entries(gold  block 18432, diamond 8192, emerald 8192), sticks are 4 (oreDic stickWood(9 entries; all 4 emc); woodStick(1 entry; 4emc))

So *everything* in its crafting chain has an emc value, and everything in the oreDic chain has an emc value. So the pick should have an emc to 24,584 yet ... nothing. I'm confused.

Additionally the diamond pick recipe specifies Diamonds, not gemDiamond or MainInfusionMaterial so I'm not sure why it even would care about the oredict in that case and the sticks are all the exact same emc.

**Comment by 14anthony7095** [comment]
What are you using besides EE3? (if anything)

**Comment by Thiana** [comment]
I'm using 148 mods. I think the problem is within EE3 specifically since everything in the chain has emc and the recipes in question are standard shaped crafting. So the problem is likely within EE3s DynEMC system, perhaps something to do with an item belonging to multiple oredics?

**Comment by Thiana** [comment]
DynEMC does seem to just break as soon as anything in the oredic has no emc. I'm not sure why it does that though since it would be logical to just select the largest emc cost in that oredict entry rather than just say that since something in the dict has no emc, everything derived from it must have no emc :(

**Comment by Sprocks59** [comment]
If you have IC2 installed it could be breaking the DynEMC system with its Industrial Diamond. Direwolf has had this problem in his Forgecraft2 series with the AE2 processors that take diamonds. I'd suggest assigning a value to this item is you have it and see if that works.

**Comment by Thiana** [comment]
IC2 isnt installed. I went through each item in the recipe and in every oredic connected to the recipe, they all have values.

**Comment by kurokuno** [comment]
just a quick reminder dynEMC will only run when mods change unless you set the configs to run on each startup

**Comment by Thiana** [comment]
I've set it to regenerate every restart, not just when mods change.

**Comment by linuxdemon1** [comment]
Have you tried launching with the ae2ee3emcaddon mod disabled? There currently seems to be a bug with it crashing dynemc

**Comment by Thiana** [comment]
I dont have that mod active. It crashes my minecraft instance if its enabled.

**Comment by linuxdemon1** [comment]
Could you please provide your fml-client-latest.log?

**Comment by Lordmau5** [comment]
I'm pretty sure it has to do with mods that add custom sticks + recipes for vanilla items (in this case, e.g. a Stone Pickaxe, Diamond Axe, Gold Shovel, ...)

Since those sticks don't have a EMC value registered to them, EE3 can't apply a DynEMC to the items that they are being used for in crafting recipes.

**Comment by Thiana** [comment]
Except that as mentioned in my initial post, all 9 variants of 'stickWood' and 'woodStick' have an EMC of 4.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
