### ISSUE TITLE
Mobius and Aeternalis Fuel missing EMC values

### ISSUE THREAD

**Issue by Cobra1117** [pahimar/Equivalent-Exchange-3#906]
Mobius Fuel and Aeternalis Fuel don't have EMC values in 0.3.507. I couldn't find any documentation stating that this was intentional, so I'm guessing that it's a bug.

**Comment by WolfAmaril** [comment]
What other mods are you using?

**Comment by Cobra1117** [comment]
I have quite a few installed. Here's the full list: http://pastebin.com/36RjAXiQ

**Comment by WolfAmaril** [comment]
Yeah, I'd say look through there for anything that adds an oreDict coal entry.
that's probably what's causing it, just like 95% of the other "suddenly no EMC value" bugs.

**Comment by Cobra1117** [comment]
I'll see if I can root around a bit tomorrow. The weird thing is that Alchemical Coal still has an EMC value, but the two higher-teir fuels don't. It's also possible that something is weird in my manual EMC configs.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
