### ISSUE TITLE
[ IDEAS ]

### ISSUE THREAD

**Issue by Carbon-Ghost** [pahimar/Equivalent-Exchange-3#908]
I have a few ideas for EE3, since I know EMC will be able to be transported in tubes + I know they will be passive emc gen, here are a few ideas : 

Passive gens : 

- Aqua Alchemical accumulator : Uses water on top of the block to generate a small amount of EMC, water can be pumped in, relatively expensive, generates 1 emc / Bucket of water. 

- Luxus Alchemical accumulator : Somewhat similar to the old collectors, but nerfed : will generate up to 0.5 - 2 EMC per second while in sunlight ( depends on the strengh of it ), artificial light can be used for generating EMC, but it will be 2x less efficient, so 0.25 to 1 EMC per second only. 

- Ignis Alchemical accumulator : Generates EMC at a variable rate, depending on what is next to it, for instance, fire will make it produce 0.5 emc every second, lava 1 emc * second^-1, and maybe foreign mod integration, with pyrotheum 2 emc * second^1 and hot coolant from IC2 having the same value. 

- Terra Alchemical accumulator : Scans a cube of 3x3x3 centered on itself ( so it's included ), and generates EMC based on what is in the area, the equation of the EMC that is produced is the following : ( EMC of the cube without counting the Accumulator itself * 2 ) / ( number of blocks scanned with an emc value  * 73728 ) = n , please note than the minimum value of n would be 1 if there is at least 1 block having an EMC value and max value would be 32 EMC per second for balance reasons. 

So that are my ideas, feel free to comment ;)

**Comment by KlutzLament** [comment]
Personally, the only type passive EMC generator I'd like to see is a cobble generator feeding into something like a condenser.

**Comment by TheOnlyQueue** [comment]
Passive EMC gen breaks any semblance of balance though. Especially boring
old cobble gens.

**Comment by chazwarp923** [comment]
The cobble idea is flawed as well considering how broken compressed cobble is

**Comment by Carbon-Ghost** [comment]
But Pahimar said passive EMC gen would be back in another form, so I just gave a cool idea ;(

**Comment by silvernocte** [comment]
Yeah, they all seem a little too much like the old collector, maybe have something that works like a furnace, getting EMC based on burn time. In reality, I just can't see passive EMC gen as not being the ridiculously overpowered "I'm at endgame and I should be able to get whatever I want" option.

**Comment by Carbon-Ghost** [comment]
Then it's not passive ;(

**Comment by SelBast** [comment]
carbon, with passive emc-gen i think that for balance reasons it needs to generate so little amounts that a real use of them only works if you don't rely on matter generation but rather on transmutation with the passive emc-gen just supplementing. else a cobble-gen with Extra Utilities and compacting drawers beats pretty much anything

**Comment by Carbon-Ghost** [comment]
That's why passive EMC should NOT be early game, it should be endgame, to a level similar to gemmed stuff of EE2, and the values are actually pretty balanced for what it does imo, but should be configurable also ;)

Everything should be expensive as hell, and as you may have understood with the terra alchemical accumulator, it's endgame ;)

**Comment by Carbon-Ghost** [comment]
Let's see what Pahimar thinks ;) He said he will include other ways to produce passive EMC in EE3, and I am quite curious to see what was his ideas + if he likes mine ;)

**Comment by pahimar** [comment]
I have some ideas on passive EMC gen

**Comment by Carbon-Ghost** [comment]
May you give us some hints about what the ideas ? :D
