### ISSUE TITLE
Output-Items (possible Transmutations) in Transmutation Tablet disappear?

### ISSUE THREAD

**Issue by Lordmau5** [pahimar/Equivalent-Exchange-3#914]
http://ss.lordmau5.com/2015-06-14_17-53-24.gif

This GIF also shows how to reproduce it...

I gotta note that I only experienced this in SMP, not in SSP (even with _just_ EE3, as in, the dev-environment)

**Comment by BLSK** [comment]
The Referenced posted above #903 is irrelevant.  It was an actual crash I was speaking of not a GUI bug.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
