### ISSUE TITLE
Crash on loading any world

### ISSUE THREAD

**Issue by MexRex** [pahimar/Equivalent-Exchange-3#918]
So I compiled EE myself like the instructions say, everything works fine.
When I load up Minecraft, it's no complaining but when I load a world it crashes after a second of loading time.
This is definitly caused by EE because this doesn't happen without it being installed..
Crash Log : http://pastebin.com/eqHGCw0K
I know it doesn't mention EE in the crash log, but as I said, without EE this does not happen, also, I already updated, reinstalled, did everything to Java RE and JDK so yeah :P
<3

**Comment by talwyn** [comment]
I had a similar issue, The crashlog doesn't show it, but further up in the fml log, it traces the error back to Equivalent Exchanges serialization helper. I was able to resolve by updating from forge 10.13.3.1408 to the latest version of forge for the client (10.13.4.1448). YRMV. 

I'm not great with java (and less familiar with forge modding), but it seems that the recent changes to how the mod handles it's data files doesn't work with older versions of forge (I don't know what the cutoff is, haven't tested that yet.) I've pastebin'ed the error from my log with forge version 10.13.3.1408 here: http://pastebin.com/TdArxQeY

**Comment by talwyn** [comment]
Well, I just had the error again, even with the latest version. Seems to be a mod interaction. Tracing now.

**Comment by S0llux** [comment]
I have the same error on both versions of forge mentioned above, i'll do some further testing in the meantime.

**Comment by MexRex** [comment]
Ok at least I am not the only one with this problem :)
Now wait for Pahimar or someone from forge I guess <.< <3

**Comment by pahimar** [comment]
@MexRex @talwyn can either of you reproduce this with the latest build again and provide me with full latest.log and fml-client-latest.log files (mediafire or dropbox links would work fine)?

**Comment by trismegistis** [comment]
Hi. I am running a forge server. It has 290+ mods so it is very possible I am getting the issue from other sources, but this is the closest I could trace my error to. When I run minecraft and my modpack manually through MC's launcher, I can connect to my server and everything is fine. When I run it through technic, I get this error: [pool-4-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@e16c1d9[id=[redacted- was hex],name=[redacted],properties={},legacy=false]
[B#313]  com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
[B#313]  	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
[B#313]  	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [YggdrasilMinecraftSessionService.class:?]
[B#313]  	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [brm.class:?]
[B#313]  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
[B#313]  	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
[B#313]  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
[B#313]  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
[B#313]  	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

I just updated a lot of mods on the server, and EE3 was one of them. Trying to restore back to an older version of EE3 to see, and I'm running 1492. My game hangs and freezes when trying to connect to the server or make a single player world via Technic.

**Comment by trismegistis** [comment]
I'm sorry, the above was a mistake. I only have Project E not EE3... :<

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
