### ISSUE TITLE
I gotta suggestion

### ISSUE THREAD

**Issue by TheSilverBeacon** [pahimar/Equivalent-Exchange-3#919]
I think that there should be some kind of auto-transmuter. It would use extra emc but would allow app-eng automation.

**Comment by Lordmau5** [comment]
Automation in general.  
I'd really like it to have e.g. ComputerCraft support, or ISided in general (Or is the later one a thing already?)

**Comment by chazwarp923** [comment]
You can already pipe in and out of the calcinator and into the research table

**Comment by Lordmau5** [comment]
Ye, but not into / out of the Transmutation Tablet :P  
That's what I was talking about hehe

**Comment by chazwarp923** [comment]
As for automating the transmutation tablet I doubt that will be implemented, it's bot inted for that, just wait until he has time to code back in the condenser

**Comment by chazwarp923** [comment]
Stupid autocorrect, please excuse my typos

**Comment by pahimar** [comment]
A condenser is planned in the future
