### ISSUE TITLE
(Question) The basis of this mod + (Suggestion) The Doorway of Truth

### ISSUE THREAD

**Issue by border999** [pahimar/Equivalent-Exchange-3#920]
I am correct in assuming that this mod was inspired by the anime Fullmetal Alchemist? Or possible the brotherhood arc? If either is the case, Pahimar, do you have any desire to creat the Door for players that attempt the taboo?

**Comment by Lomeli12** [comment]
The mod is based on alchemy in general. There may be some items inspired by the anime (x3n0ph0b3 made a proper post somewhere explaining it with previous versions of EE), but the entire mod itself is not.

**Comment by border999** [comment]
Though the Doorway would be a very interesting feature in general
