### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by utoc** [pahimar/Equivalent-Exchange-3#921]
Good Morning,

I'm running EE build 307 with FML 1448.  We had a server crash this morning.

http://pastebin.com/SJt918w1

The user(s) that were on at the time of the crash have not logged back in so I do not know what actions they were performing at the time of the crash.

I find my crash very similar to https://github.com/pahimar/Equivalent-Exchange-3/issues/895 but it seems like it had a different trigger.

**Comment by pahimar** [comment]
They shift clicked out of the Transmutation Tablet, it's a known bug and being worked on.

**Comment by utoc** [comment]
I just confirmed it with the user, spam clicking just like a previous bug I had reported only the previous one only crashed the client, this one crashed the server.  Thanks for updating me though, I appreciate it :)

**Comment by utoc** [comment]
Duplicate of https://github.com/pahimar/Equivalent-Exchange-3/issues/901, closing this ticket so that the issue tracker remains uncluttered
