### ISSUE TITLE
Sever Crash- java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by ProsperCraft** [pahimar/Equivalent-Exchange-3#924]
http://pastebin.com/PbqkcfL7

The users tell me someone was shift clicking a stack of soul sand from the tablet and it filled their inventory.

Shouldn't shift click do a stack not your entire inventory?

**Comment by ProsperCraft** [comment]
Here is another server crash - http://pastebin.com/H6TfdGEG

**Comment by McyD** [comment]
Same issue was just reported on my server as well.  If you want the logs, though they look the same, I can provide them.

**Comment by utoc** [comment]
This is probably a duplicate, see https://github.com/pahimar/Equivalent-Exchange-3/issues/901

**Comment by ProsperCraft** [comment]
Closing, same as #901
