### ISSUE TITLE
DynEMC thread crash with NPE

### ISSUE THREAD

**Issue by AstralSorcerer** [pahimar/Equivalent-Exchange-3#925]
I don't know how, but Chisel seems to be crashing the DynEMC thread.  I have reported this to the Chisel authors (Chisel-2/Chisel-2#350), but I think it is worth reporting here as well, as it seems to me that another mod should not be able to do something that causes a crash in EE3.  [Here](http://pastebin.com/Z4rwxHZM) is the FML log (Note: I had to strip out the DEBUG-level lines in order to get the file under Pastebin's size limit).

EDIT: I forgot to mention I'm using EE3 version 0.3.507

**Comment by AstralSorcerer** [comment]
A little more info:
Adding Chisel did not by itself cause this problem, but after removing and re-adding Chisel, this did occur, along with the serialization error mentioned in #918.

**Comment by AstralSorcerer** [comment]
So, it seems that the comparison of wrapped stacks is not working.  As in ```preCalculationMappings.contains(wrappedStack)``` will return false when ```wrappedStack``` was in the set returned by ```preCalculationMappings.keySet()```.

**Comment by AstralSorcerer** [comment]
So the issue stems from EE3 using item IDs to compare ItemStacks.  Since FML remaps item IDs when a save is loaded in order to match those in the save, the item ID used when an item is registered is not necessarily the same as it is once the server starts.  This causes two items, say X and Y, where X.compareTo(Y) < 0 before server start, to reverse once the server starts, which messes with the TreeMap's ordering, making it unable to find the item.  I managed to fix it by using the registered name of the item.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
