### ISSUE TITLE
Creating the tablet

### ISSUE THREAD

**Issue by ash1688** [pahimar/Equivalent-Exchange-3#929]
Hi 
I have a problem with trying to make the tablet but i pressed the charge key to many times by accident and the chalk outline doesn't show on the 3x3 ash infused blocks but if i go 4x4 or higher the chalk outline does show, I have tried pressing the other 3 keys but nothing happens.
Yes I have changed the keys so they are no longer conflicting so it's not that

**Comment by Virtuoel** [comment]
If the chalk is too large you can hold shift and charge to make it smaller. The tablet can only be made on a 3x3. Or am I misunderstanding your problem?

**Comment by ash1688** [comment]
yeah I know that it can only be made on a 3x3 it just when i was trying to make it i clicked once to many and lost the outline and it would only show on a bigger grid and thanks I didn't know about holding shift and charge to make it go smaller

**Comment by ash1688** [comment]
nah hold shift and pressing charge or any of the keys doesn't reduce the outline size

**Comment by ash1688** [comment]
sorted it was the key binding I had it didn't like me using the numpad
