### ISSUE TITLE
EMC Retaining Knowledge

### ISSUE THREAD

**Issue by porteriscool** [pahimar/Equivalent-Exchange-3#934]
When I start up my game, or create a new instance for a minecraft world, I lose the EMC knowledge I have for the transmutation tablet, and have to teach each item all over again. I am currently using version  0.3.507. If you need anymore information, feel free to ask.

**Comment by DrasticDemise** [comment]
Every time you join your existing world or create a new world? It is world specific just like the thaumonomicon.

**Comment by porteriscool** [comment]
No, what I mean is, whenever I create a new world, and go back over to my old world that already has knowledge, that knowledge is lost.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
