### ISSUE TITLE
Multiple entries with same key error

### ISSUE THREAD

**Issue by utoc** [pahimar/Equivalent-Exchange-3#935]
Today I encountered the following:

[23:12:17] [DynamicEMC Thread/INFO] [Equivalent Exchange 3]: Beginning dynamic value computation
Exception in thread "DynamicEMC Thread" [23:12:17] [DynamicEMC Thread/INFO] [STDERR]:
[java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Multiple entries with same key:
1000xfluidStack.oil=[[1xitemStack[item.for.canOil@0]], [1xitemStack[item.bucketOil@0]], [1xitemStack[item.for.waxCapsuleOil@0]],
[1xitemStack[item.for.refractoryOil@0]]] and 1000xfluidStack.oil=[[1xitemStack[item.oilBucket@0]]]

I'm pretty sure EE is upset that there are two kinds of oil: one from BC and one from PneumaticCraft.  This stopped DynEMC from being able to run.  I searched the issue tracker and it looks like this was brought up before in https://github.com/pahimar/Equivalent-Exchange-3/issues/486.

I hve EE3 build 507 and am running FML 1448 with [the following mods](https://www.reddit.com/r/BBQSauce/wiki/modlist)

**Comment by IntelliSun** [comment]
Can you please provide the full FML log? It's very interesting that it happens as pahimar made a lot of effort to prevent that

**Comment by utoc** [comment]
See the log here: http://bbqsauce.terron.com/bbqsauce.gz (Gzip format)

Interestingly enough, the error has also popped up for the different variations of "fuel" as well.

**Comment by IntelliSun** [comment]
Next time you send a log use pastebin.
I could not find the lines you were referring to in the log file.

**Comment by utoc** [comment]
I've forced a DynEMC update and have a full forge log.  I cannot upload it to pastebin as it exceeds their limit;  It is 8mb.  The file is viewable here and it opens as plain text which should be a better alternative than zipping:  http://bbqsauce.terron.com/fml.txt

Let me know if I can assist in any other way.

**Comment by IntelliSun** [comment]
Still no match, wish I could say otherwise.

**Comment by utoc** [comment]
Its at line 43667 (about 1100 lines from the bottom).  You'll find it right after the following:

`[DynamicEMC Thread/INFO] [Equivalent Exchange 3/]: Beginning dynamic value computation`

**Comment by IntelliSun** [comment]
OK, found it, in [RecipeRegistry](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/recipe/RecipeRegistry.java#L81) there is an attempt to copy a `MultiMap` (which support key duplicates) to a `Map` (which doesn't). I'll fix that with my next pull request. (Please don't close the issue until then)

Thank you!

**Comment by belovres** [comment]
This bug is presented when the assembly is installed Thermal Foundation v1.2.0 or later . Checked by experience , including one fashion.
Sorry for my english , I'm from Russia , and use Google.Translate.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
