### ISSUE TITLE
OPiness of EE and possible solutions

### ISSUE THREAD

**Issue by ovju** [pahimar/Equivalent-Exchange-3#936]
Everyone knows that ability to exchange one material to other is one of most over powered mechanics in modded minecraft. Not sure though if author considers it an issue. If not, then just ignore this. 

But otherwise what if to transmutation mechanic you'd add some negative mechanics? Like if someone wants to exchange very low EMC cost material into very high cost material then that player might get really hurt or get a negative effect or maybe even a biome might change to something sinister, or maybe mob spawn rate would increase around that area, or there would be a possibility of some kind of negative effect. 

I'd like to see this mechanic implemented into EE3. :)

**Comment by GTMelo** [comment]
> Everyone knows that ability to exchange one material to other is one of most over powered mechanics in modded minecraft.

Meeeh, that's kind of relative. I think that there are already tools to control transmutation to a degree (for example, you can forbid <insert item here> to be researched or used, can tweak EMC values, etc.)
That said, I wouldn't mind we getting some hooks added to the transmutation process. Maybe something that signals when a transmutation is done, and maybe output some basic info about what was done. I could totally see, for example, one using that to if(transmuteToSomethinginTheHaxRules()){ lightningInTheFace(); createMassiveAmountsofTaint();}

**Comment by anti344** [comment]
I'd love to see that mechanic, but EE is jus about OP and nothing else =P
Probably somebody could make some kind of ASM addon.

**Comment by ovju** [comment]
OR! If original idea does not fit in EE3 frame, then what about adding:

The Law of Natural Providence, which states that an object or material made of a particular substance or element can only be transmuted into another object with the same basic makeup and properties of that initial material. In other words, an object or material made mostly of water can only be transmuted into another object with the attributes of water.

**Comment by luanpotter** [comment]
Maybe a simpler solution to make the mod less OP is requiring XP for every transmutation. Just a small amount, that might scale with the EMC value involved, would totally nerf the mod in my opinion, actually reaching equilibrium with other mods. Of course latter could be automated with liquid xp farm, but even then I think it would be a fairer price for auto transmutation (if that is ever enabled).

**Comment by GTMelo** [comment]
Again, this is all well and good, but it would be a more elegant solution to have it as implementing an undefined framework first, them think of the fun stuff it can be used.

Just watch and fire a signal signalWhatever() whenever a transmutation is done.

Entirelly in separate, define what triggers whenever the signal is heard. This allows for flexibility, letting EE behave the way it wants to be (for example, it may even ship with some sample reactions as examples, like "nothing", "denyIfNotEnoughXP();", "explodesIfHax();", "ninaAlexanderMuchCryingItStillHurtsInside()", etc.), while allowing for the eventual third party to create reactions of their own. Going the crazy stretch, something like this would even eventually allow for things like Accidentally Circumstantial Events to integrate, firing scripts as signalWhatever() fires.

**Comment by Josephur** [comment]
I think items of a higher energy value should take longer to learn, lets say item with 1 energy = default time (what is it about 10 seconds?), item with 1000 energy = 60 second wait time to add it to your book.  This of course could be configurable in the config files to leave it default, or base it off of items energy value.  Also a second option could allow mod authors to override the time it takes an item to be learned into the book, therefore making items completely customizable by other mod authors.

**Comment by pahimar** [comment]
For now the transmutation mechanic is how I'd like it to be, but I might open up more possibilities for it in the future. Closing.
