### ISSUE TITLE
Middle scroll - Looses stored EMC

### ISSUE THREAD

**Issue by PawnedSauce** [pahimar/Equivalent-Exchange-3#938]
When having to take out items using the scroll method that Inventory Tweaks provide, the EMC that is storage in the Transmutation Table is suddenly lost mostly all of it after taking one item.

Mods using
EE3 0.3.507
Inventory Tweaks

**Comment by IntelliSun** [comment]
I believe it was fixed with #904.
It works fine with the current code.

**Comment by pahimar** [comment]
Resolved with #904
