### ISSUE TITLE
DynEMC thread crash with Forestry(?) and BuildCraft

### ISSUE THREAD

**Issue by D3add3d** [pahimar/Equivalent-Exchange-3#942]
So after a small update to our modpack suddenly EMC value disappeared for half of vanilla items so I tried to investigate the issue and downloaded EE3 Helper to make assigning the values easier(it doesn't even work)... There is a command to run the DynEMC so I ran it. This is what the console told me: http://pastebin.com/JDbFADPz

**Comment by RoloEdits** [comment]
yes the same problem was happening to me i made a report in #937

**Comment by IntelliSun** [comment]
See issue #935
