### ISSUE TITLE
Pre values not retained after reboot

### ISSUE THREAD

**Issue by alexgeek** [pahimar/Equivalent-Exchange-3#944]
I just spent a while setting pre values for various items such as certus quartz and botania flowers and petals. I expected the values for these items and those crafted with the items to be calculated on rebooting the server. However none of the values were retained on reboot.
I found a reddit thread that suggested the sync command but still the values were lost on reboot.

**Comment by IntelliSun** [comment]
What file did you edit to enter these values?

**Comment by alexgeek** [comment]
I was using the /ee3 command as a player (as opposed to from the server console).

**Comment by IntelliSun** [comment]
Ok... which flag did you use, `pre` or `global-pre`?

**Comment by alexgeek** [comment]
Pre and Post, does global-pre set it server side?

**Comment by IntelliSun** [comment]
Well as far as I know both commands should run server-side. The global flags set the values instance wide (in the config) and the other two does it for the world you're in.

Can you check please the folder `[server dir]/[world name]/data/ee3/energyvalues` and post here its contents?

**Comment by alexgeek** [comment]
Do you need all of them? This is the pre values JSON file: http://pastebin.com/vCAN4r0W
Is it due to the damage values?

**Comment by IntelliSun** [comment]
Well I meant the content of the directory as file names. Regardless the values are still there, but they are not being used for some reason. The file is called `pre-calculation-energy-values.json` right?

**Comment by alexgeek** [comment]
No its called pre-assigned-energy-values.json. 
The directory contains the following files:
9f8f2fab15c1e95edec21a7c8f944ce7.json.gz,  post-assigned-energy-values.json, energy-values.json.gz, pre-assigned-energy-values.json.

**Comment by IntelliSun** [comment]
I think the last bit of information I'll need to make sure is your config settings and logs, but before you do that, I want you to change two things in the config.
1. Set `B:debug.logTraceToInfo` to `true`.
2. Set `S:energyvalues.regenerateEnergyValuesWhen` to `Always`.

Then check the values again, if nothing changed please send my the log file (after you entered the world).

**Comment by alexgeek** [comment]
Ah that seems to have worked. I guess the energy values were not being recalculated as the mod list hadn't changed. 
Since it doesn't take a great deal of time to calculate the values, shouldn't the config default be Always?

**Comment by IntelliSun** [comment]
It actually is in the current code-base, that's why I assumed you had it that way, should have asked :|

**Comment by alexgeek** [comment]
My bad should have stated my version in the original post. 
Is it possible to shift click/right click a single stack out the transmutation table in the current version? If not I may fork and see what I can do.
