### ISSUE TITLE
Suggestion: Recalculate Command

### ISSUE THREAD

**Issue by king05** [pahimar/Equivalent-Exchange-3#947]
Hi,
Can you add an recalculate command so a server admin can run this command to let ee3 recalculate the energy values?

Sincerly,
king05

**Comment by RoloEdits** [comment]
You can try ee3 helper it has a command /ee3h regen which forces a recalculation

**Comment by IntelliSun** [comment]
By the looks of it there is not command to do so right now, I'll probably make a pull request later today to support that.

**Comment by king05** [comment]
Ok,
No problem.
