### ISSUE TITLE
Crash with RFTools: ConcurrentModificationException

### ISSUE THREAD

**Issue by AstralSorcerer** [pahimar/Equivalent-Exchange-3#948]
RFTools adds recipes during the world load event, causing a ConcurrentModificationException EE3's registration of vanilla recipes with the RecipeRegistry.  Removing RFTools fixed the issue.

**Comment by IntelliSun** [comment]
This information is in not enough to help you, please provide the crush log.

**Comment by AstralSorcerer** [comment]
Derp!  [Here](http://pastebin.com/1ZkzGPdj) is the tail of the log (I can't post the whole thing due to Pastebin's 500kB limit).  It seems that RFTools is adding recipes as EE3 is iterating over the recipe list.  Check out [this](https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/WorldLoadEvent.java#l30) line and [this](https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/items/dimlets/KnownDimletConfiguration.java#l678) function from the RFTools code.

**Comment by IntelliSun** [comment]
Well there is not much to say about this, it's a problem with Minecraft not considering multi-threaded scenarios, `getRecipeList` should return an immutable copy of the list. Or provide a sync-root. Unfortunately this is not the case. IMHO the best course of action to copy the list on the main thread and then pass it to calculation on the worker threads.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #993
