### ISSUE TITLE
Crashing on startup:

### ISSUE THREAD

**Issue by Conmyster** [pahimar/Equivalent-Exchange-3#949]
Hello I have a few mods installed via the Curse launcher, I install EE3 and when it loads It crashes here is the crash log: http://pastebin.com/6qFX3gR7

The mods installed are:

AE2 Stuff
AE2
BdLib
Darkcore
Ender IO
EE3 (Obviously)
Extra Utilities
ExtraCells2
TARDIS Mod
Waila
Waila Harvestability

If I remove EE3 it loads fine.

**Comment by IntelliSun** [comment]
The log says that you EE3 version is:
EE3{pre1g (build 12)} [Equivalent Exchange 3] (ee3-universal-pre1g-12.jar)

The curse version is maybe outdated, It claims to be for MC 1.5, according to your logs you're playing 1.7.10, please download the recommended version from here: http://ee3.pahimar.com/

**Comment by Conmyster** [comment]
Ahh ook there must be an issue with the curse mod downloader then.
