### ISSUE TITLE
DynEMC Lost When Adding/Removing Mods

### ISSUE THREAD

**Issue by arachnotron** [pahimar/Equivalent-Exchange-3#950]
Hello. I first would like to note the similarity to other issues opened on this repo. I open this to showcase a new problem that I'm seeing, which may or may not get buried under unrelated information.

When adding a mod to my game and loading up my already-existing world, all of the dynamic EMC values for any item, vanilla or mod, cease to exists. Nothing has EMC except the very base parts. HOWEVER, when I create a new world with the updated modlist, everything has properly-calculated EMC.

There appears to be an issue in recalculating the dynamic EMC values if you're not generating a new world.

Now, I assume this can be worked around by copying the ee3 data from a new save to an old one (and it's something I'm going to try), but it's something to look into.

**Comment by RoloEdits** [comment]
it seems that the old files are still remaining after new ones are generated i just delete mine when that happens to let it run again and then things have emc again

the files that im talking about are in the world saves folder data/ee3/energyvalues  you'll see the energy-values.json and anther one with bunch of numbers and letters i just delete these and let them regen

**Comment by IntelliSun** [comment]
The code attempts to load from file first [here](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/exchange/EnergyValueRegistry.java#L341). I'm not certain as of why it won't use the old values, but I deleting the values will work as it forces EE3 to regenerate all values.

Before I dog through the code to try and find the problem, what version of EE are you using? (just paste the .jar file name)

**Comment by arachnotron** [comment]
Right. Some additional information:

1. Using the latest (from my last check) release, 0.3.507
2. I know about data/ee3/energyvalues. Deleting the stored values and forcing regeneration this way does nothing. However, replacing with values generated upon creation of a new world does in fact work.

Interestingly, when I check the console to try and find where and when it logs calculating dynamic EMC anew, it seems to be loading from file despite being set to regenerate. I wonder if it could simply be recreating the file without new data, then loading in the now-empty file when it recognizes that it exists, somehow.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
