### ISSUE TITLE
shouldRegenNextRestart problems

### ISSUE THREAD

**Issue by IntelliSun** [pahimar/Equivalent-Exchange-3#952]
The flag `shouldRegenNextRestart` makes if possible to force EMC values regeneration after they were changed in-game. The current functionality seems to not work correctly right now, these are the issues I've found so far:

* Issue #944 - according to this issue the changes made in-game (using [CommandSetEnergyValue](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/command/CommandSetEnergyValue.java)) were saved to disk, but no regeneration happened afterwards. Forcing a regen through the config did indeed solve issue.

* No regen forced for post-calculation values - if you look at [this](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/command/CommandSetEnergyValue.java#L115) and [loadEnergyValueRegistryFromFile](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/exchange/EnergyValueRegistry.java#L727) you can see that the `post` option does not force a recalculation (my assuming that post values are always loaded) while the reality they are not loaded as you can in `loadEnergyValueRegistryFromFile`.

* Regen is forces only world-wide - the [save](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/exchange/EnergyValueRegistry.java#L698) method checks to the flag `shouldRegenNextRestart`, if the flags if set to `true` a regen is forced by deleting the current values forcing [loadEnergyValueRegistryFromFile](https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/exchange/EnergyValueRegistry.java#L727) to return `false` next time. The problem is that is only deletes values in the world directory - the config-wide values wont be affected.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
