### ISSUE TITLE
EMC recalculation discussion [#944]

### ISSUE THREAD

**Issue by IntelliSun** [pahimar/Equivalent-Exchange-3#953]
Currently the EMC values are very customizable, you can edit both pre and post values. But for these values to take effect the EMC value dictionary needs to be recalculated after each change. The config gives users the option to decide when such recalculation happen - always, when mods change, and never. 
To allow values that were set during gameplay to take effect regardless of the current configuration there is a flag called `shouldRegenNextRestart` that forces a value regen. Right now it seems as if it does not function correctly (see #952 and #944)

The implementation around `shouldRegenNextRestart` should definitely be fixed, but I'd argue that the system altogether is flawed.

The calculated values are auto generated and could change at any time - basically they should never be used by the user. Taking that to account there is not reason to not regenerate these file single time. That will solve the issues above and will allow offline changes (editing the pre and post files outside a play session) to be applied without deleting files manually. This also will render the config option obsolete.

If we wish to keep the option to not regenerate the calculated files we should keep hashes of the pre and post file so it is possible to act once their contents change.

**Comment by Entoarox** [comment]
DynEMC is to slow (In the larger modpacks) for "Always" to be reasonable, what would be much better is for a equivalent of the /ee3h regen command of EE3Helper to be moved into EE3 itself, in short, allow server admins (Or SSP with cheats on) to regenerate the DynEMC as needed, without needing to restart or have it happen all the time.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
