### ISSUE TITLE
EE3 crash on DW20 1.7 Pack

### ISSUE THREAD

**Issue by BeastOfTheLands** [pahimar/Equivalent-Exchange-3#955]
Everytime i open the DW20 modpack on curse voice it seems to crash, i have a crash report at http://pastebin.com/EhMU5peJ please help since i was very excited to get started with EE3, my twitter is BeastOTL if you need to contact me. Thanks in advance.

**Comment by IntelliSun** [comment]
When you disable EE3 does the game still crushes?

**Comment by pahimar** [comment]
They are using a version of EE3 for Minecraft 1.5. Its a known bug with the Curse launcher. Go to the Versions tab and grab 0.3.507. Please see similiarly closed duplicate issues.
