### ISSUE TITLE
EE3 crash when using tablet

### ISSUE THREAD

**Issue by BeastOfTheLands** [pahimar/Equivalent-Exchange-3#956]
I tried taking out some cobblestone from the tablet forgetting that it fills the inventory so i shift clicked with 4k exchange energy in the tablet and the game crashed.

Crash Report: http://pastebin.com/DVUVdTQ9

**Comment by utoc** [comment]
This is likely a duplicate of https://github.com/pahimar/Equivalent-Exchange-3/issues/901

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
