### ISSUE TITLE
Latest dev version cannot create transmutation tablet

### ISSUE THREAD

**Issue by devryb** [pahimar/Equivalent-Exchange-3#959]
I have the latest dev version compiled for EE3 and when I shift right click the 3x3 grid of ashstone with a 3x3 chalk on top it will not turn into a transmutation tablet.  Nothing shows in the logs when I try to make it.  Am I doing something wrong?

**Comment by Ben880** [comment]
I believe you have to shift right-click with an empty hand.

**Comment by devryb** [comment]
Doesn't work on the latest compiled dev version.

**Comment by pahimar** [comment]
Post pics or a video showing step by step what you are doing. It most definitely works but we can help.

**Comment by Lomeli12** [comment]
You have to press V to change what type of Transmutation circle to draw. I can't remember of the top of my head which circle you need.

**Comment by devryb** [comment]
http://www.twitch.tv/devryb/v/8254263

**Comment by devryb** [comment]
That is with Forge 1448 and only the latest EE3 dev compiled version installed

**Comment by Lomeli12** [comment]
Sorry, wrong key. It's G by default to toggle the types of circles.

![gif](https://cloud.githubusercontent.com/assets/637246/8837799/1c4e158c-307d-11e5-95a4-9b27658e4420.gif)

**Comment by devryb** [comment]
Ah success!  It seems to only work with that design though,  The others give me the issue

**Comment by Lomeli12** [comment]
That's because that design IS FOR making the tablet. The others will probably have other uses in the future.

**Comment by pahimar** [comment]
Lomeli12 is correct
