### ISSUE TITLE
plz pahimar help

### ISSUE THREAD

**Issue by abdullahatea** [pahimar/Equivalent-Exchange-3#960]
how can i set the value of items with out commands just auto item value set like forgecraft 2

**Comment by MrPotatoGaming** [comment]
Alright, first, EE3 auto-values already. If for some reason your world does not have EMC values, open up the config file and read what it says. It should say how to do so in the file. At this current time, it is nearly impossible to set values up using an editor of sorts. The easiest way to set up custom values is commands.

**Comment by pahimar** [comment]
DynEMC should auto set values - its no different on FC2 as it is for anyone else using the mod
