### ISSUE TITLE
No EMC Values for crafted items unless removing mods?

### ISSUE THREAD

**Issue by catzs** [pahimar/Equivalent-Exchange-3#963]
Without installing EE3 Helper, every time I loaded up my HorizonsII world without removing a mod, I would only have EMC values for the base items.
EE3 Version:0.3.507

**Comment by utoc** [comment]
Without removing what mod?  Have you reviewed your Forge client log to see what EE errors you're getting?

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
