### ISSUE TITLE
Chalk does not het bigger

### ISSUE THREAD

**Issue by deemsen** [pahimar/Equivalent-Exchange-3#964]
My chalk does not het bigger when i hover over the 3x3 ash block thingy i see a 1x1 circle i press V and it doesnt het bigger why? (Btw its in the modpack crazy craft 3)

**Comment by pahimar** [comment]
Check your keybindings. You want to be hitting the Charge button to make it bigger. You hit Shift + Charge to make it smaller

**Comment by deemsen** [comment]
Okay thnx ill try it in a minute
