### ISSUE TITLE
Transmutation Tablet not working 

### ISSUE THREAD

**Issue by Draik09** [pahimar/Equivalent-Exchange-3#965]
When i Shift-Right click (or right-click for that matter) on the transmutation tablet multiblock structure, it will not form a transmutation tablet.
![2015-07-30_18 09 16](https://cloud.githubusercontent.com/assets/9831601/8998734/21bb1280-36e6-11e5-9628-ca1dcf5bc4e9.png)

**Comment by DTM450** [comment]
thats the incorrect circle design you need the one here https://github.com/pahimar/Equivalent-Exchange-3/wiki/Transmutation-Tablet

**Comment by Lomeli12** [comment]
*sigh* Here is how you make a tablet now. https://github.com/pahimar/Equivalent-Exchange-3/issues/959#issuecomment-123869828
