### ISSUE TITLE
EE3 not keeping Stuff in the book

### ISSUE THREAD

**Issue by DjDerpsalot** [pahimar/Equivalent-Exchange-3#966]
Good morning Pahimar,

I am using your EE3 on my server. It is included with the Horizons: Daybreak package.

I have used this in the past with no issues. Now there is an issue.

I have a research table with a book in it which is bound to me as well as a transmutation tablet with a book which is bound to me as well.  I have tried using the same book in both and I get the same results.

I have "researched" a bunch of items into the research table book and they stay there with no problem throughout my game session. However, when I log off for the night, all the items in the books are lost.

The transmutation tablet retains any energy that I leave in over night but, again, any items that were in the book are lost. 

What is going on?

Note: I have added EnderIO and Treecapitator to the server but nothing else. 

How can I fix this?

Thanks,

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989
