### ISSUE TITLE
Crash when using EE3 and Chisel 2

### ISSUE THREAD

**Issue by bigyihsuan** [pahimar/Equivalent-Exchange-3#972]
Crash report: [Pastebin](http://pastebin.com/hJ9NXiTz)

Info:
* Forge 10.13.4.1448 for Minecraft 1.7.10
* Mods: [Picture](http://i.imgur.com/zep6Z93.png)
* Using Chisel2, version 2.4.1.40, EE3 v1.7.10-0.3.501

**Comment by Entoarox** [comment]
You need the latest version (507) of EE3 for the chisel integration to work.

**Comment by bigyihsuan** [comment]
Hooray, it works! Thanks!
