### ISSUE TITLE
World not loading with latest COFHCore?

### ISSUE THREAD

**Issue by jermangarc** [pahimar/Equivalent-Exchange-3#973]
Not sure if this has been reported, I have found what seems to be similar issues but none describe my exact issue. I have been trying to get my world to load for two days now and I finally got a clue as to what might be the problem. The only issue is, there is no crash report, the game just hangs up on loading a world. Once it gets past the DynamicEMC initialization the world loading just hangs. It's happening on my existing world as well as new world loading. Here is a list of the mods (I know, it's big. Hosting it on a dedicated server like ForgeCraft). This all started happening after an update to COFHCore/TE. When I remove EE3 from the pack world loads fine.

http://pastebin.com/GL6Xmqqc

FML Log (partial):
http://pastebin.com/5aEdDRiF
At the end of the log is where it gets stuck.

https://github.com/pahimar/Equivalent-Exchange-3/issues/937#issuecomment-128503220

**Comment by pahimar** [comment]
What does your latest.log say? And if I could get a full FML log (mediafire or dropbox links would work) I could help more

**Comment by jermangarc** [comment]
I ended up disabling EE3 integration in ThermalExpansion /ThermalFoundation configs to get it to work. I've been running a uber-ForgeCraft-like server for over a year now, so I'm not sure if you want to see the logs, it can be quite lengthy. But if you still want it I can provide it in a zip file over dropbox. Oh and thanks for the reply Pahimar! I've been watching your tutorials on modding, good stuff brother!

**Comment by pahimar** [comment]
Please try again with version 0.3.0.519 and report back in this issue if you are still having problems :)
