### ISSUE TITLE
Shift-Clicking items out of Transmutation Tablet crashing client

### ISSUE THREAD

**Issue by ajay1770** [pahimar/Equivalent-Exchange-3#975]
Anytime I open the transmutation tablet and shift-click bulk items out, my client will crash. But if I pull a single item out, then shift-click, it seems to work fine. I have a server up and it does nothing to the server as far as I can tell. It only crashes the client. 

Crashreport: http://pastebin.com/Dm7WqwVc

Also it does this while in a fresh test world as well. So it does crash the client in SSP.

**Comment by Wulfson** [comment]
Probably a dupe of #956 and #901

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #992
