### ISSUE TITLE
Knowledge not Saving after relogging 

### ISSUE THREAD

**Issue by lokilore** [pahimar/Equivalent-Exchange-3#976]
FTB Horizons II Daybreaker v1.1.0 Unable to save EE3 Knowledge after relogging. WIIEMC v1.0.1-Universal. Removed WIIEMC and EE3 Works Correctly.

https://github.com/Lomeli12/WIIEMC/issues/2

**Comment by lolking12345** [comment]
I have the same problem, Re-researched three times. It's infuriating.

**Comment by Novtalath** [comment]
Some people say that deleting WIIEMC mod helps. I have noticed that saving research works fine on single player it's the MP version that has a problem.

Not a fix but helps - if you have your own server and fixed number of users you can start server setting up in server.properties online-mode to false, have everyone log in and cheat the book for each person and have them set the book for themselves. Then you can stop server, change back to online-mode=true and it all should work fine with everyone using the cheated book (any new book will not work but making a copy of existing "offline mode" one will). That method works other way round too... At least it did on my server.

**Comment by lolking12345** [comment]
okay, thanks. i'll try.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #989

**Comment by Tyras91** [comment]
This is still happening, i play on a server where we all are having knowledge loss when we logg out.
