### ISSUE TITLE
EE3 Crash On Startup

### ISSUE THREAD

**Issue by Andrene** [pahimar/Equivalent-Exchange-3#977]
I only have EE3 installed, I've Tried to  Use EE3 with other mods and I still get the same crash. 

--Crash Log--
http://pastebin.com/9fA9rhLn

Would love some help with this

**Comment by 50Wliu** [comment]
Please download the latest .jar from http://equivalent.exchange, not from the Curse Launcher.

**Comment by Andrene** [comment]
Thanks
