### ISSUE TITLE
EMC auto generating and then not generating 

### ISSUE THREAD

**Issue by jusitnboggs** [pahimar/Equivalent-Exchange-3#978]
Sometimes it doesn't generate EMC for things like chests or torches or other items and other times out of the blue starts generating without reloading my game.

**Comment by Entoarox** [comment]
Have you tried using the /ee3 sync-energy-values command to see if it is simply a client/server desync issue?

**Comment by jusitnboggs** [comment]
Yes and it doesn't do anything

**Comment by Entoarox** [comment]
Please list if you have any of the following mods:

- Thermal Expansion
- Thermal Dynamics
- Chisel 2
- Extra Utilties

**Comment by jusitnboggs** [comment]
i use all 4 but i downgraded Chisel 2 and
Extra Utilties

**Comment by Entoarox** [comment]
Did you disable the EE3 compatibility in the thermal expansion & thermal foundation common.cfg files?

**Comment by jusitnboggs** [comment]
I just rechecked my version numbers with the ones you posted in the other issues and I grabbed the wrong one... after downgrading for real this time it seems to be working fine with TE still enabled.

**Comment by Entoarox** [comment]
Yes, there is a chance for it to still work, the issue is some form of desync/duplicate mapping problem that prevents DynEMC from being able to resolve anything and getting stuck, a fix is already known, but @Pahimar hasnt been able to pull it due to real life making him its wipping boy. (The poor guy!)

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
