### ISSUE TITLE
Chalk Circle Resizing Issue

### ISSUE THREAD

**Issue by viktro78** [pahimar/Equivalent-Exchange-3#981]
I accidentally pressed V and extra time and now the chalk circle is stuck on 5x5. Pressing Shift+V does nothing at all.
Edit: I have the Key bound to its original with no other mods using this key.

**Comment by pahimar** [comment]
Shift + the charge keybinding will reduce the size of the chalk circle. If you continue to have issues, try resetting your keybindings

**Comment by viktro78** [comment]
I have the Keybinding Set Properly and have attempted to do just that many times.

**Comment by pahimar** [comment]
I have no idea what's going on with your set up - you are literally the only person to report this issue and there are thousands of people successfully using this.

I'm going to need some logs (full fml-latest-client.log and latest.log) in order to get more info as to what's going on.

**Comment by viktro78** [comment]
Bizarre... Just Bizarre. Its Started working after I opened and closed the GUI for a progressive automation stone chopper... Sorry I Cant get logs as I am leaving home soon.

**Comment by viktro78** [comment]
Hmm... Sorry for the trouble. Would give you logs but fml doesn't seem to be writing to log files correctly I'm not really gonna worry about it though because im getting a new computer soon anyways.
