### ISSUE TITLE
Feature request: On/Off switch for The Condenser.

### ISSUE THREAD

**Issue by SgtCookie** [pahimar/Equivalent-Exchange-3#984]
As the title says, basically. A button on The Condenser that switches it on or off would be extremely useful.

**Comment by Entoarox** [comment]
To my knowledge EE3 itself currently has no condenser functionality in the first place.

**Comment by Lomeli12** [comment]
*awkward cough* https://github.com/Lomeli12/SimpleCondenser

**Comment by pahimar** [comment]
There is no condenser in the mod yet
