### ISSUE TITLE
Issues with Source-Code Build Documentation

### ISSUE THREAD

**Issue by gabor6505** [pahimar/Equivalent-Exchange-3#985]
So, this is the first time I ever tried to do this Code Build with Gradle and get the Jar thing, and the Readme seems to be a little bit wrong for me. And I had to figure out what worked for me, so I gonna be write this down.

I have `Windows 8.1 x64 Professional` Operation System, and:

* I successfully installed `JDK 7 (v79) x64` and `Java 7 (v79) x64` and added the Variables correctly.
* I successfully installed `Gradle v1.11` and added the Variables correctly. (Because I tried to solve things, I followed to download this version instead of v2.6) 
* I successfully installed `Git 2.5.0 x64`.

Then I came to this: **Setup EE3**

The first thing that was not the same in my case is I didn't got an `mcdev` folder. I didn't deal with this issue.

And the second, very important thing is if I download EE3's source into the `C:\Github\Equivalent-Exchange-3\` directory, the actual files will be in this directory: `C:\Github\Equivalent-Exchange-3\Equivalent-Exchange-3\`, because the download creates another folder. And hardly I figured out that's why the `gradle setupCiWorkspace` command didn't want to work, because the instructions didn't say to navigate to `C:\Github\Equivalent-Exchange-3\Equivalent-Exchange-3\`, and everytime I tried to execute the command, it didn't work, because I was navigated to the `C:\Github\Equivalent-Exchange-3\` folder (the steps before this said to navigate to here) and there was nothing here except another `Equivalent-Exchange-3` folder.

I already solved the problem, just wanted to note that I think at least the second thing is not documented correctly, and I hope you understand what I try to say. If you want the gradle error that was before I figured out the problem, here it is:
```
C:\Windows\system32>cd C:\GitHub\Equivalent-Exchange-3\

C:\GitHub\Equivalent-Exchange-3>gradle setupCiWorkspace

FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupCiWorkspace' not found in root project 'Equivalent-Exchange-3'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option
to get the stack trace. Run with                                               -
-info
or                                                                             -
-debug
option to get more log output.

BUILD FAILED

Total time: 1.425 secs
```

**Comment by 50Wliu** [comment]
The docs could be a bit clearer on the cloning part I suppose.  In addition, mcdev` isn't an actual folder:
>Navigate to a place where you want to download EE3's source [...] this location is known as `mcdev` from now on.

**Comment by gabor6505** [comment]
Okay, but then what type of thing is `mcdev` ? Just we call it `mcdev` ?

**Comment by Entoarox** [comment]
Its whatever you named the folder that you downloaded EE3 into locally.
The directory you should be in when building is the directory that holds the build.gradle file

**Comment by gabor6505** [comment]
Okay, I get it. So I actually don't have to worry about this mcdev thing. But this should be documented too. Because people who start from nothing, and has no knowledge about this gets a little bit confused. 
I also couldn't find anything useful about this in Google Search. But sorry it may be just me. 

Anyway, thanks for the help, and I don't really know how Github Pull Request etc. works, but someone should correct the Readme file and the front page about my second from the OP (The Clone thingy). :smile:

**Comment by 50Wliu** [comment]
I'll try to get around to it if I remember :)

**Comment by gabor6505** [comment]
Thanks! :smile:
