### ISSUE TITLE
Energy values not automatically generating

### ISSUE THREAD

**Issue by CrayolaBlues** [pahimar/Equivalent-Exchange-3#986]
Nothing crafted with items with EE Values automatically gets assigned an energy value. This includes everything from redstone blocks to speed upgrades

**Comment by Entoarox** [comment]
There is a known issue where vanilla items crafted from redstone dust do not get an EMC value, but there is currently no solution to that problem other then manually assigning the items in question an EMC value.

As to the other items not getting EMC, do you have the following mods installed:
- Thermal Dynamics
- Thermal Expansion
- Chisel 2
- Extra Utilities

If you do, then you need to at least downgrade Chisel to the version before EE integration was added, and depending on your exact mod-pack may need to disable EE integration in TD/TE and may even need to downgrade ExU aswell.

A fix is known and tested but @pahimar hasnt had the time to accept the pull request just yet, reality has kidnapped him and none of us webizens knows what this "life" thing that it is demanding in ransom is.

**Comment by pahimar** [comment]
Closing in order to track issues on the unified ticket #990
