### ISSUE TITLE
Crash with git version of EE3

### ISSUE THREAD

**Issue by mrsteyk** [pahimar/Equivalent-Exchange-3#999]
Hello everyone! I got this error when i run ftb lite 3 with ee3 git version built on java 8: http://pastebin.com/u3jaCYB2 . Please help me! This version is stable for emc generating!

**Comment by pahimar** [comment]
Please post the fml latest log

**Comment by mrsteyk** [comment]
Recreated issue log: https://gist.github.com/mrsteyk/cf643a4adcbb8d731799 . Main stuff is: 1) i'm on linux (that makes a lot of difference) 2)"Exception in thread "DynamicEMC Thread" AL lib: (EE) alc_cleanup: 1 device not closed"

**Comment by mrsteyk** [comment]
This is also on dw20 pack.

**Comment by mrsteyk** [comment]
Tried to run thrgough (sorry if i mistaked) java 7 - no luck :disappointed: !

**Comment by HadesDurin** [comment]
when i see it right you update your ee3 to latest version
which you can get here: http://minecraft.curseforge.com/mc-mods/65509-ee3/files

**Comment by mrsteyk** [comment]
Off-topic: Pahimar do you know how to fix emc (for compressed cobble and other stuff)? And when emc fixes will be part of EE3

**Comment by mrsteyk** [comment]
@HadesDurin i built git version! I dont really want to use realeses, cuz they are cutted in my opinion.

**Comment by mrsteyk** [comment]
@pahimar i think i know why minecraft is crashing! In Anti-Material Energy i changed settings and crash is simillar! I will test soon!

**Comment by border999** [comment]
wait, stupid question but is the source code for ee3 that's posted on Github different from the latest release on the official site?

**Comment by Wulfson** [comment]
What's on Github has the potential to be more updated than a given release, but it's not like things have been removed to make a release. If you compile it yourself it's just more "bleeding edge", which can possibly be less stable.

**Comment by pahimar** [comment]
Please try with version 0.3.0.519, and if you still experience issues please report it again in this ticket :)
